export interface FeatureFaqItem {
  question: string
  answer: string
}

export interface FeatureSeoData {
  key: string
  pageTitle: string
  pageDescription: string
  path: string
  keywords: string[]
  serviceName: string
  serviceDescription: string
  h2: string
  overview: string
  benefits: string[]
  useCases: string[]
  tips: string[]
  faqs: FeatureFaqItem[]
}

const FEATURE_SEO_DATA: Record<string, FeatureSeoData> = {
  'phuc-dung-anh': {
    key: 'phuc-dung-anh',
    pageTitle: 'Phục dựng ảnh cũ online bằng AI',
    pageDescription: 'Phục dựng ảnh cũ, ảnh mờ, ảnh xước bằng AI nhanh và tự nhiên. Tăng chi tiết khuôn mặt, khử nhiễu, nâng chất lượng ảnh để lưu trữ và in ấn.',
    path: '/phuc-dung-anh',
    keywords: ['phục dựng ảnh cũ', 'khôi phục ảnh mờ', 'repair photo ai', 'nâng cấp ảnh cũ'],
    serviceName: 'Phục dựng ảnh cũ bằng AI',
    serviceDescription: 'Khôi phục ảnh cũ, ảnh mờ và ảnh xuống cấp thành phiên bản rõ nét, tự nhiên.',
    h2: 'Phục dựng ảnh cũ online nhanh, giữ cảm xúc gốc của bức ảnh',
    overview: 'Phục dựng ảnh cũ là nhu cầu phổ biến với gia đình, studio ảnh và đơn vị lưu trữ tư liệu. Công cụ này giúp làm rõ ảnh mờ, giảm xước và tăng chi tiết để ảnh dễ xem, dễ chia sẻ và dễ in hơn.',
    benefits: ['Tăng độ nét và giảm nhiễu trên ảnh cũ', 'Giữ khuôn mặt tự nhiên, không bị nhựa hóa', 'Phù hợp ảnh gia đình, ảnh tư liệu, ảnh scan cũ'],
    useCases: ['Phục hồi ảnh gia đình nhiều năm bị mờ', 'Làm lại ảnh scan giấy trước khi in khổ lớn', 'Chuẩn hóa ảnh cũ cho profile thương hiệu'],
    tips: ['Ưu tiên ảnh đầu vào đủ sáng, không nén quá mạnh', 'Nếu có nhiều bản ảnh, chọn bản ít nhiễu nhất', 'Nên lưu cả bản gốc và bản phục dựng để đối chiếu'],
    faqs: [
      { question: 'Ảnh quá cũ có phục dựng được không?', answer: 'Có. Ảnh càng rõ vùng chủ thể thì kết quả càng tốt. Trường hợp ảnh mất chi tiết nặng vẫn có thể cải thiện đáng kể.' },
      { question: 'Công cụ có làm thay đổi khuôn mặt không?', answer: 'Mục tiêu là giữ nhận diện tự nhiên, tăng độ rõ và giảm nhiễu thay vì thay đổi khuôn mặt.' },
      { question: 'Dùng cho ảnh scan được không?', answer: 'Được. Ảnh scan là nhóm đầu vào phổ biến và thường cải thiện rõ sau xử lý.' },
      { question: 'Nên chọn 2K hay 4K?', answer: '2K phù hợp dùng online hằng ngày. 4K phù hợp khi cần hậu kỳ hoặc in ấn.' },
      { question: 'Có thể xử lý ảnh chân dung nhóm không?', answer: 'Có. Công cụ hỗ trợ tốt ảnh có nhiều người nếu ảnh gốc đủ rõ.' },
    ],
  },
  'lam-net-anh': {
    key: 'lam-net-anh',
    pageTitle: 'Làm nét ảnh online bằng AI',
    pageDescription: 'Làm nét ảnh mờ online bằng AI cho ảnh chân dung, sản phẩm và tài liệu. Tăng độ chi tiết, giảm bệt màu, xuất ảnh sắc nét nhanh.',
    path: '/lam-net-anh',
    keywords: ['làm nét ảnh', 'tăng độ nét ảnh ai', 'ảnh mờ thành rõ', 'sharpen image online'],
    serviceName: 'Làm nét ảnh bằng AI',
    serviceDescription: 'Tăng độ nét ảnh mờ và khôi phục chi tiết tự nhiên chỉ trong vài bước.',
    h2: 'Làm nét ảnh mờ để dùng ngay cho bán hàng, social và tài liệu',
    overview: 'Khi ảnh bị mờ do rung tay, nén file hoặc chụp thiếu sáng, việc làm nét giúp cải thiện khả năng truyền tải nội dung ngay lập tức. Công cụ AI phù hợp cả người mới lẫn đội nội dung cần xử lý nhanh.',
    benefits: ['Khôi phục chi tiết quan trọng của ảnh', 'Giảm cảm giác bệt màu và nhòe viền', 'Tối ưu tốc độ xử lý cho workflow hằng ngày'],
    useCases: ['Làm nét ảnh sản phẩm trước khi đăng sàn', 'Làm rõ ảnh profile cá nhân và doanh nghiệp', 'Tăng độ rõ ảnh tài liệu để dễ đọc hơn'],
    tips: ['Không nên dùng ảnh đã nén nhiều lần', 'Giữ bản gốc để đối chiếu chất lượng', 'Chọn chất lượng đầu ra theo mục đích hiển thị'],
    faqs: [
      { question: 'Làm nét có làm ảnh bị giả không?', answer: 'Hệ thống ưu tiên nét tự nhiên, hạn chế tạo cảm giác gắt hoặc viền giả.' },
      { question: 'Ảnh điện thoại cũ có xử lý được không?', answer: 'Có. Đây là trường hợp sử dụng phổ biến và thường cho cải thiện rõ ràng.' },
      { question: 'Dùng cho ảnh sản phẩm được không?', answer: 'Rất phù hợp, đặc biệt khi cần tăng rõ chi tiết trước khi chạy quảng cáo.' },
      { question: 'Có hỗ trợ ảnh chân dung không?', answer: 'Có, và vẫn giữ ưu tiên nhận diện khuôn mặt tự nhiên.' },
      { question: 'Bao lâu có kết quả?', answer: 'Thông thường chỉ mất từ vài giây đến khoảng 1 phút tùy ảnh và chất lượng chọn.' },
    ],
  },
  'lam-dep-anh': {
    key: 'lam-dep-anh',
    pageTitle: 'Làm đẹp ảnh chân dung AI tự nhiên',
    pageDescription: 'Làm đẹp ảnh chân dung như studio bằng AI: retouch da, ánh sáng, màu sắc tự nhiên. Giữ khuôn mặt thật và nền gốc, chỉ làm mờ nền theo mức chọn.',
    path: '/lam-dep-anh',
    keywords: ['làm đẹp ảnh', 'retouch chân dung', 'chỉnh ảnh studio', 'xóa phông chuyên nghiệp'],
    serviceName: 'Làm đẹp ảnh chân dung bằng AI',
    serviceDescription: 'Retouch chân dung tự nhiên, giữ nhận diện khuôn mặt và giữ nền gốc.',
    h2: 'Retouch chân dung như studio nhưng vẫn giữ gương mặt thật',
    overview: 'Làm đẹp ảnh online cần vừa đẹp vừa tự nhiên. Tính năng này tập trung vào da, ánh sáng và tổng thể chân dung, đồng thời giữ nhận diện gương mặt để ảnh dùng được cho profile, CV và social.',
    benefits: ['Làm da mịn và sáng hơn có kiểm soát', 'Giữ nguyên khuôn mặt thật của người chụp', 'Cho phép làm mờ nền chuyên nghiệp theo nhu cầu'],
    useCases: ['Ảnh profile cá nhân và doanh nghiệp', 'Ảnh chân dung dùng cho hồ sơ nghề nghiệp', 'Ảnh social cần chỉn chu nhưng tự nhiên'],
    tips: ['Chọn ảnh gốc đủ sáng để ra màu đẹp', 'Tránh ảnh bị che mặt quá nhiều', 'Ưu tiên nền gốc sạch để blur đẹp hơn'],
    faqs: [
      { question: 'Có thay nền hoặc xóa nền không?', answer: 'Không. Tính năng này giữ nguyên nền gốc, chỉ làm mờ nền theo mức chọn.' },
      { question: 'Khuôn mặt có bị biến dạng không?', answer: 'Mục tiêu là giữ nhận diện thật, chỉ cải thiện chất lượng tổng thể.' },
      { question: 'Dùng cho ảnh nhiều người được không?', answer: 'Có, công cụ hỗ trợ ảnh có nhiều người trong cùng khung hình.' },
      { question: 'Phù hợp ảnh CV/LinkedIn không?', answer: 'Rất phù hợp vì kết quả ưu tiên tự nhiên và chuyên nghiệp.' },
      { question: 'Ảnh đầu ra dùng in được không?', answer: 'Có thể, đặc biệt khi chọn mức chất lượng cao hơn.' },
    ],
  },
  'ghep-anh': {
    key: 'ghep-anh',
    pageTitle: 'Ghép ảnh online bằng AI tự nhiên',
    pageDescription: 'Ghép ảnh online bằng AI nhanh và tự nhiên. Kết hợp nhiều ảnh, tối ưu hòa trộn ánh sáng và bố cục để dùng cho social, quảng cáo, kỷ niệm.',
    path: '/ghep-anh',
    keywords: ['ghép ảnh online', 'ghép nhiều ảnh', 'photo collage ai', 'ghép ảnh tự nhiên'],
    serviceName: 'Ghép ảnh bằng AI',
    serviceDescription: 'Kết hợp nhiều ảnh thành một bố cục tự nhiên, hài hòa màu và ánh sáng.',
    h2: 'Ghép ảnh nhanh để tạo nội dung mới cho social và quảng cáo',
    overview: 'Ghép ảnh là nhu cầu thường xuyên trong marketing, bán hàng và nội dung cá nhân. Với AI, bạn có thể rút ngắn đáng kể thời gian thử bố cục và tạo ra ảnh hoàn chỉnh dễ dùng ngay.',
    benefits: ['Kết hợp ảnh nhanh không cần thao tác phức tạp', 'Hài hòa màu sắc và ánh sáng tổng thể', 'Tiết kiệm thời gian so với ghép tay thủ công'],
    useCases: ['Tạo ảnh khuyến mãi sản phẩm', 'Ghép ảnh kỷ niệm gia đình hoặc team', 'Làm nội dung minh họa cho bài đăng'],
    tips: ['Chọn ảnh có góc chụp gần nhau để ghép đẹp', 'Ưu tiên ảnh chất lượng tương đồng', 'Kiểm tra bố cục trước khi xuất chất lượng cao'],
    faqs: [
      { question: 'Có cần biết Photoshop không?', answer: 'Không. Công cụ tối ưu cho người dùng phổ thông.' },
      { question: 'Ghép được bao nhiêu ảnh?', answer: 'Tùy flow của trang, bạn có thể ghép theo cấu hình được hỗ trợ.' },
      { question: 'Ảnh ghép có bị giả không?', answer: 'Hệ thống ưu tiên hòa trộn tự nhiên để hạn chế cảm giác cắt dán.' },
      { question: 'Dùng cho quảng cáo được không?', answer: 'Có, đặc biệt khi cần tạo nhanh nhiều biến thể ảnh.' },
      { question: 'Có thể tải về để chỉnh tiếp không?', answer: 'Có, bạn có thể tải kết quả và hậu kỳ thêm nếu cần.' },
    ],
  },
  'tao-banner': {
    key: 'tao-banner',
    pageTitle: 'Tạo banner online bằng AI cho quảng cáo',
    pageDescription: 'Tạo banner AI online nhanh cho Facebook, Google, Zalo và website. Tối ưu bố cục, chữ và điểm nhấn để tăng tỷ lệ nhấp.',
    path: '/tao-banner',
    keywords: ['tạo banner ai', 'thiết kế banner online', 'banner quảng cáo', 'banner facebook'],
    serviceName: 'Tạo banner bằng AI',
    serviceDescription: 'Thiết kế banner quảng cáo nhanh với bố cục trực quan và dễ chuyển đổi.',
    h2: 'Tạo banner quảng cáo nhanh để chạy chiến dịch liên tục',
    overview: 'Trong vận hành quảng cáo, tốc độ tạo banner mới ảnh hưởng trực tiếp đến khả năng test và tối ưu chiến dịch. Công cụ này giúp đội marketing tạo nhanh mẫu banner dùng được ngay trên nhiều kênh.',
    benefits: ['Rút ngắn thời gian từ ý tưởng đến banner', 'Dễ tạo nhiều biến thể để A/B testing', 'Phù hợp cả in-house team và freelancer'],
    useCases: ['Banner chạy ads theo mùa', 'Banner ưu đãi ngắn hạn cho shop', 'Banner landing page cho sản phẩm mới'],
    tips: ['Giữ thông điệp ngắn gọn và dễ đọc', 'Chọn màu nền tương phản với chữ', 'Tạo nhiều phiên bản để test hiệu quả'],
    faqs: [
      { question: 'Có dùng cho Facebook Ads được không?', answer: 'Có, bạn có thể dùng kết quả cho các kênh quảng cáo phổ biến.' },
      { question: 'Có cần file thiết kế gốc không?', answer: 'Không bắt buộc. Bạn có thể tạo nhanh trực tiếp từ mô tả.' },
      { question: 'Banner có phù hợp mobile không?', answer: 'Có, bạn có thể chọn bố cục theo mục tiêu hiển thị.' },
      { question: 'Bao lâu tạo xong 1 banner?', answer: 'Thường chỉ mất từ vài giây đến khoảng 1 phút.' },
      { question: 'Có thể tạo nhiều mẫu liên tiếp không?', answer: 'Có, đây là cách phổ biến để test hiệu quả quảng cáo.' },
    ],
  },
  'tao-anh-the': {
    key: 'tao-anh-the',
    pageTitle: 'Tạo ảnh thẻ online chuẩn kích thước',
    pageDescription: 'Tạo ảnh thẻ online bằng AI, hỗ trợ nền trắng/xanh và kích thước phổ biến như 3x4, 4x6. Kết quả nhanh, phù hợp hồ sơ cá nhân và công việc.',
    path: '/tao-anh-the',
    keywords: ['tạo ảnh thẻ online', 'ảnh 3x4', 'ảnh 4x6', 'ảnh thẻ ai', 'ảnh hồ sơ'],
    serviceName: 'Tạo ảnh thẻ bằng AI',
    serviceDescription: 'Chuẩn hóa ảnh thẻ nhanh với nền và bố cục phù hợp nhu cầu sử dụng.',
    h2: 'Tạo ảnh thẻ online nhanh để dùng ngay cho hồ sơ và thủ tục',
    overview: 'Tạo ảnh thẻ thủ công thường tốn thời gian vì phải căn khung, xử lý nền và chuẩn kích thước. Công cụ AI giúp rút gọn toàn bộ quá trình để bạn có ảnh dùng ngay cho hồ sơ, CV và các thủ tục cơ bản.',
    benefits: ['Chuẩn hóa ảnh thẻ nhanh theo nhu cầu phổ biến', 'Giữ khuôn mặt tự nhiên, không bị giả', 'Tiện cho cá nhân, HR và dịch vụ hồ sơ'],
    useCases: ['Ảnh hồ sơ xin việc', 'Ảnh thẻ cho giấy tờ cá nhân', 'Ảnh profile chuẩn chỉ cho doanh nghiệp'],
    tips: ['Chụp ảnh thẳng mặt, đủ sáng', 'Tránh tóc che mắt hoặc phụ kiện lớn', 'Chọn kích thước đúng mục đích trước khi xuất'],
    faqs: [
      { question: 'Có hỗ trợ 3x4 và 4x6 không?', answer: 'Có, đây là hai kích thước được dùng nhiều nhất.' },
      { question: 'Có đổi nền trắng/xanh được không?', answer: 'Có, bạn có thể chọn nền phù hợp nhu cầu.' },
      { question: 'Ảnh có dùng nộp hồ sơ online được không?', answer: 'Có, kết quả phù hợp cho hầu hết nhu cầu nộp hồ sơ số.' },
      { question: 'Có cần máy ảnh chuyên nghiệp không?', answer: 'Không, ảnh điện thoại đủ sáng là có thể dùng tốt.' },
      { question: 'Bao lâu có ảnh thẻ?', answer: 'Thông thường chỉ vài giây đến khoảng 1 phút.' },
    ],
  },
  'thiet-ke-logo': {
    key: 'thiet-ke-logo',
    pageTitle: 'Thiết kế logo online bằng AI nhanh',
    pageDescription: 'Thiết kế logo AI online cho thương hiệu cá nhân, shop và doanh nghiệp nhỏ. Tạo nhanh nhiều ý tưởng logo để chọn phương án phù hợp.',
    path: '/thiet-ke-logo',
    keywords: ['thiết kế logo ai', 'tạo logo online', 'logo thương hiệu', 'logo cho shop'],
    serviceName: 'Thiết kế logo bằng AI',
    serviceDescription: 'Tạo ý tưởng logo nhanh cho thương hiệu mới và chiến dịch sản phẩm.',
    h2: 'Thiết kế logo nhanh để chốt nhận diện thương hiệu sớm',
    overview: 'Logo là điểm chạm đầu tiên của thương hiệu với khách hàng. Công cụ AI giúp bạn tạo nhanh nhiều hướng logo để chọn phong cách phù hợp trước khi đi vào bộ nhận diện đầy đủ.',
    benefits: ['Có nhiều concept logo trong thời gian ngắn', 'Giảm thời gian thử ý tưởng ban đầu', 'Phù hợp startup, shop và dự án mới'],
    useCases: ['Logo cho shop online', 'Logo cho thương hiệu cá nhân', 'Logo cho sản phẩm hoặc chiến dịch mới'],
    tips: ['Nêu rõ ngành hàng trong mô tả', 'Chọn phong cách nhất quán với tệp khách hàng', 'Giữ logo đơn giản để dễ ứng dụng'],
    faqs: [
      { question: 'Logo AI có dùng thương mại được không?', answer: 'Bạn có thể dùng theo chính sách sử dụng của nền tảng và quy định pháp lý hiện hành.' },
      { question: 'Có tạo nhiều phiên bản logo không?', answer: 'Có, bạn nên tạo nhiều biến thể để chọn bản tốt nhất.' },
      { question: 'Phù hợp cho thương hiệu mới không?', answer: 'Rất phù hợp cho giai đoạn khởi tạo ý tưởng nhận diện.' },
      { question: 'Có thể dùng cho social avatar không?', answer: 'Có, logo tạo ra có thể dùng cho avatar và ấn phẩm số.' },
      { question: 'Có thay đổi màu phong cách được không?', answer: 'Có, bạn có thể mô tả lại để tạo phiên bản khác.' },
    ],
  },
  'ke-chuyen-bang-hinh-anh': {
    key: 'ke-chuyen-bang-hinh-anh',
    pageTitle: 'Kể chuyện bằng hình ảnh với AI',
    pageDescription: 'Tạo ảnh kể chuyện bằng AI từ ý tưởng ngắn. Phù hợp làm nội dung social, giáo dục, truyền thông và bài đăng thương hiệu.',
    path: '/ke-chuyen-bang-hinh-anh',
    keywords: ['kể chuyện bằng ảnh', 'storytelling ai', 'tạo ảnh có nội dung', 'ảnh minh họa câu chuyện'],
    serviceName: 'Kể chuyện bằng hình ảnh AI',
    serviceDescription: 'Biến ý tưởng thành ảnh kể chuyện có ngữ cảnh rõ ràng và dễ truyền tải.',
    h2: 'Biến ý tưởng ngắn thành ảnh kể chuyện có cảm xúc',
    overview: 'Thay vì chỉ tạo một ảnh đẹp, storytelling image giúp ảnh có bối cảnh và thông điệp rõ ràng hơn. Đây là hướng nội dung phù hợp cho social, giáo dục và truyền thông thương hiệu.',
    benefits: ['Ảnh có ngữ cảnh giúp người xem hiểu nhanh', 'Tăng tính cảm xúc cho bài đăng', 'Dễ xây chuỗi nội dung theo chủ đề'],
    useCases: ['Post kể chuyện thương hiệu', 'Nội dung giáo dục trực quan', 'Ảnh minh họa cho chiến dịch cộng đồng'],
    tips: ['Mô tả bối cảnh và cảm xúc mong muốn', 'Giữ thông điệp ngắn, rõ', 'Tạo theo series để tăng nhận diện'],
    faqs: [
      { question: 'Có cần viết prompt dài không?', answer: 'Không bắt buộc, ý tưởng ngắn vẫn có thể tạo ảnh kể chuyện tốt.' },
      { question: 'Phù hợp cho fanpage không?', answer: 'Có, đặc biệt với các nội dung cần cảm xúc và bối cảnh.' },
      { question: 'Có tạo được ảnh theo chủ đề giáo dục?', answer: 'Có, đây là nhóm use case phổ biến.' },
      { question: 'Dùng cho quảng cáo được không?', answer: 'Có thể dùng ở giai đoạn thu hút nhận diện và kể giá trị sản phẩm.' },
      { question: 'Có cần kỹ năng thiết kế không?', answer: 'Không, công cụ tối ưu cho người dùng phổ thông.' },
    ],
  },
  'tao-nhan-gian': {
    key: 'tao-nhan-gian',
    pageTitle: 'Tạo nhãn dán sticker bằng AI',
    pageDescription: 'Tạo nhãn dán sticker bằng AI nhanh, phù hợp bán hàng, in ấn và social. Dễ tạo mẫu nhãn dán theo phong cách thương hiệu.',
    path: '/tao-nhan-gian',
    keywords: ['tạo sticker ai', 'tạo nhãn dán', 'sticker online', 'nhãn dán nền trong suốt'],
    serviceName: 'Tạo nhãn dán AI',
    serviceDescription: 'Tạo sticker và nhãn dán theo ý tưởng nhanh, dễ dùng cho bán hàng và truyền thông.',
    h2: 'Tạo sticker và nhãn dán nhanh cho shop và thương hiệu',
    overview: 'Nhãn dán là tài sản hình ảnh nhỏ nhưng rất quan trọng trong truyền thông và đóng gói. Công cụ AI giúp bạn tạo nhanh nhiều mẫu sticker để dùng cho social, quà tặng và in tem sản phẩm.',
    benefits: ['Tạo nhanh nhiều ý tưởng nhãn dán', 'Đồng bộ phong cách thương hiệu', 'Dễ dùng cho social và in ấn'],
    useCases: ['Sticker tặng kèm đơn hàng', 'Nhãn dán cho chiến dịch social', 'Tem mini cho bao bì sản phẩm'],
    tips: ['Ưu tiên mô tả ngắn gọn, rõ thông điệp', 'Giữ màu sắc nhất quán thương hiệu', 'Tạo nhiều mẫu để test phản hồi khách'],
    faqs: [
      { question: 'Sticker tạo xong dùng in được không?', answer: 'Có, bạn có thể dùng kết quả cho in ấn tùy nhu cầu kích thước.' },
      { question: 'Có phù hợp cho shop nhỏ không?', answer: 'Rất phù hợp vì thao tác nhanh và dễ lặp lại.' },
      { question: 'Có dùng cho social post được không?', answer: 'Có, sticker giúp bài đăng sinh động hơn.' },
      { question: 'Có cần biết thiết kế không?', answer: 'Không, người mới vẫn có thể dùng tốt.' },
      { question: 'Có tạo theo phong cách thương hiệu được không?', answer: 'Có, chỉ cần mô tả phong cách mong muốn.' },
    ],
  },
  'tao-nhan-gioi-thieu-san-pham': {
    key: 'tao-nhan-gioi-thieu-san-pham',
    pageTitle: 'Tạo nhãn giới thiệu sản phẩm bằng AI cho đóng gói',
    pageDescription: 'Tạo nhãn giới thiệu sản phẩm AI online nhanh cho đóng gói. Tải 1–6 ảnh sản phẩm, nhập nội dung. 1,5 credit (2K) / 3 credit (4K) mỗi lượt.',
    path: '/tao-nhan-gioi-thieu-san-pham',
    keywords: ['tạo nhãn sản phẩm ai', 'nhãn đóng gói', 'nhãn giới thiệu sản phẩm', 'thiết kế nhãn bao bì'],
    serviceName: 'Tạo nhãn giới thiệu sản phẩm bằng AI',
    serviceDescription: 'Thiết kế nhãn đóng gói chuyên nghiệp từ ảnh sản phẩm và nội dung ghi trên nhãn.',
    h2: 'Tạo nhãn sản phẩm nhanh để đóng gói chuyên nghiệp',
    overview: 'Nhãn giới thiệu sản phẩm là phần quan trọng của bao bì. Công cụ AI giúp bạn tạo nhanh nhãn từ 1–6 ảnh sản phẩm và nội dung, phù hợp in dán trên hộp, túi và sản phẩm.',
    benefits: ['Rút ngắn thời gian từ ảnh đến nhãn hoàn chỉnh', 'Nhiều kích thước nhãn để chọn', 'Phù hợp shop nhỏ và doanh nghiệp'],
    useCases: ['Nhãn hộp sản phẩm', 'Nhãn túi đựng', 'Nhãn chai lọ, bao bì thực phẩm'],
    tips: ['Chọn ảnh sản phẩm rõ nét', 'Nội dung ngắn gọn, dễ đọc', 'Chọn kích thước phù hợp mục đích in'],
    faqs: [
      { question: 'Có tối đa bao nhiêu ảnh?', answer: '1–6 ảnh sản phẩm mỗi lượt tạo (không tính logo).' },
      { question: 'Chi phí mỗi lượt?', answer: '1,5 credit cho ảnh 2K, 3 credit cho ảnh 4K.' },
      { question: 'Có in được không?', answer: 'Có, kết quả phù hợp in dán trên bao bì.' },
      { question: 'Có chọn kích thước nhãn không?', answer: 'Có, nhiều tỷ lệ: vuông, dọc, ngang.' },
      { question: 'Có tách nền ảnh sản phẩm không?', answer: 'Có, bạn có thể chọn tách nền từng ảnh.' },
    ],
  },
  'mockup-cylinder-wrap': {
    key: 'mockup-cylinder-wrap',
    pageTitle: 'Mockup nhãn chai / lon (cylinder wrap)',
    pageDescription: 'Tạo nhãn phẳng cho chai, lon theo đường kính và chiều cao mm. Chu vi = π×Ø. Tùy chọn tải ảnh. Xuất PNG, PDF chuẩn in.',
    path: '/mockup-cylinder-wrap',
    keywords: ['mockup nhãn chai', 'cylinder wrap', 'nhãn lon', 'label chai', 'bottle label mockup'],
    serviceName: 'Mockup nhãn chai / lon',
    serviceDescription: 'Tạo nhãn phẳng và mockup 3D cho chai, lon. Chu vi = π×đường kính. Xuất PNG, PDF chuẩn in.',
    h2: 'Tạo nhãn chai/lon nhanh theo kích thước',
    overview: 'Nhãn chai, lon là hình chữ nhật phẳng có chiều rộng bằng chu vi (π×đường kính). Công cụ tạo nhãn theo kích thước mm, tùy chọn tải ảnh thiết kế, xem mockup 3D.',
    benefits: ['Nhãn phẳng theo kích thước chính xác mm', 'Mockup 3D xem trước', 'Xuất PNG, PDF chuẩn in'],
    useCases: ['Nhãn chai nước', 'Nhãn lon đồ uống', 'Nhãn sản phẩm dạng trụ'],
    tips: ['Đường kính 20–200 mm, chiều cao 20–500 mm', 'Chu vi = π × đường kính', 'In trên giấy decal dán quanh chai'],
    faqs: [
      { question: 'Có dùng AI không?', answer: 'Không. Nhãn tạo theo công thức từ đường kính và chiều cao, không dùng AI.' },
      { question: 'Có mất phí không?', answer: 'Không. Tạo nhãn và xuất PNG miễn phí. Xuất PDF chuẩn in cần đăng nhập.' },
      { question: 'Chu vi tính thế nào?', answer: 'Chu vi = π × đường kính (≈ 3.14 × Ø mm).' },
      { question: 'Có in được không?', answer: 'Có. PDF có bleed 3mm, crop marks, kích thước mm chính xác.' },
    ],
  },
  'thiet-ke-bao-bi': {
    key: 'thiet-ke-bao-bi',
    pageTitle: 'Thiết kế bao bì AI - Hộp carton, túi đựng',
    pageDescription: 'Thiết kế bao bì bằng AI: hộp carton, túi đựng. Tải ảnh sản phẩm in lên hộp/túi, nhập thương hiệu, sản phẩm. AI tạo mockup chuyên nghiệp, thẩm mỹ cao. 1,5–3 credits/lượt.',
    path: '/thiet-ke-bao-bi',
    keywords: ['thiết kế bao bì ai', 'mockup bao bì', 'thiết kế hộp carton', 'mockup túi đựng', 'in ảnh sản phẩm lên hộp', 'packaging design ai'],
    serviceName: 'Thiết kế bao bì AI - Hộp carton, túi đựng',
    serviceDescription: 'AI tạo mockup bao bì chuyên nghiệp: hộp carton, túi đựng. Tải ảnh sản phẩm in lên bề mặt, nhập thương hiệu, sản phẩm, logo. Xuất ảnh chất lượng cao.',
    h2: 'Thiết kế bao bì AI - Hộp carton, túi đựng',
    overview: 'Trang thiết kế bao bì đóng hàng: hộp carton và túi đựng. Tải ảnh sản phẩm để in lên mặt hộp/túi, AI tạo mockup photorealistic, thẩm mỹ cao, phù hợp quảng cáo và trình bày.',
    benefits: ['Tải ảnh sản phẩm in lên hộp/túi', 'AI tạo mockup chuyên nghiệp, thẩm mỹ cao', 'Hai loại: hộp carton, túi đựng', 'Nhập thương hiệu, sản phẩm, logo tùy chọn', 'Phong cách: hiện đại, cao cấp, tự nhiên, rực rỡ'],
    useCases: ['Mockup hộp đựng sản phẩm', 'Mockup túi đựng có in ảnh sản phẩm'],
    tips: ['Tải ảnh sản phẩm rõ nét để in lên hộp/túi', 'Nhập tên thương hiệu và sản phẩm rõ ràng', 'Upload logo để tăng nhận diện', 'Chọn phong cách phù hợp ngành hàng', '2K cho nhanh, 4K cho chất lượng cao'],
    faqs: [
      { question: 'Có dùng AI không?', answer: 'Có. AI (Gemini) tạo mockup photorealistic từ ảnh sản phẩm và thông tin bạn nhập.' },
      { question: 'Có mất phí không?', answer: 'Có. 1,5 credit (2K) hoặc 3 credit (4K) mỗi lượt tạo.' },
      { question: 'Ảnh sản phẩm dùng để làm gì?', answer: 'Ảnh sản phẩm được in lên mặt hộp/túi trong mockup, như bao bì thật.' },
      { question: 'Hộp và túi khác gì?', answer: 'Hộp: carton 3D đóng hàng. Túi: stand-up pouch hoặc flat bag đựng sản phẩm.' },
      { question: 'Có upload logo được không?', answer: 'Có, logo tùy chọn. AI tích hợp logo vào thiết kế.' },
    ],
  },
  'thiet-ke-tui-dung': {
    key: 'thiet-ke-tui-dung',
    pageTitle: 'Thiết kế túi đựng (mặt phẳng)',
    pageDescription: 'Tạo net triển khai túi đựng có gusset theo kích thước mm (W×H×G). Xuất PNG, PDF chuẩn in.',
    path: '/thiet-ke-tui-dung',
    keywords: ['thiết kế túi', 'net túi đựng', 'túi gusset', 'flat bag design', 'triển khai túi'],
    serviceName: 'Thiết kế túi đựng (mặt phẳng)',
    serviceDescription: 'Tạo net triển khai túi đựng có gusset theo kích thước W×H×G mm. Xuất PNG, PDF chuẩn in.',
    h2: 'Tạo net túi đựng nhanh theo kích thước',
    overview: 'Net mặt phẳng túi đựng là bản triển khai 2D của túi có gusset (hông túi), in trên giấy bìa, kraft hoặc màng PE rồi cắt gấp.',
    benefits: ['Tạo net theo kích thước chính xác mm', 'Nét đỏ: cắt, nét đứt xanh: gấp', 'Xuất PNG, PDF chuẩn in (bleed, crop marks)'],
    useCases: ['Túi đựng quà', 'Túi đựng sản phẩm', 'Túi mẫu thử'],
    tips: ['Gusset G nên nhỏ hơn chiều cao H', 'Kiểm tra net trước khi in hàng loạt', 'In trên giấy bìa, kraft, màng PE'],
    faqs: [
      { question: 'Có dùng AI không?', answer: 'Không. Net tạo theo công thức toán học từ kích thước W×H×G, không dùng AI.' },
      { question: 'Có mất phí không?', answer: 'Không. Tạo net và xuất PNG miễn phí. Xuất PDF chuẩn in cần đăng nhập.' },
      { question: 'Kích thước giới hạn bao nhiêu?', answer: 'W, H từ 20–500 mm. G từ 10–200 mm.' },
      { question: 'Có in được không?', answer: 'Có. PDF có bleed 3mm, crop marks, kích thước mm chính xác.' },
      { question: 'Gusset là gì?', answer: 'Gusset (G) là độ sâu hông túi, tạo không gian 3 chiều khi gấp.' },
    ],
  },
  'tao-ma-vach': {
    key: 'tao-ma-vach',
    pageTitle: 'Tạo mã vạch & VietQR online miễn phí',
    pageDescription: 'Tạo VietQR và mã vạch online. VietQR tích hợp VietQR.io – app ngân hàng quét được. QR Code, EAN-13, UPC-A, Code 128. Không giới hạn, tải PNG miễn phí.',
    path: '/tao-ma-vach',
    keywords: ['tạo mã vạch', 'tạo qr code', 'mã vạch online', 'qr code link', 'mã vạch sản phẩm'],
    serviceName: 'Tạo mã vạch & VietQR',
    serviceDescription: 'VietQR (VietQR.io) cho app ngân hàng. QR Code, EAN-13, UPC-A, Code 128 cho link, văn bản, mã sản phẩm.',
    h2: 'Tạo mã vạch và QR Code nhanh cho nhãn, bao bì, sản phẩm',
    overview: 'QR Code và mã vạch dùng cho nhãn sản phẩm, truy xuất nguồn gốc, thanh toán VietQR, chia sẻ link. Công cụ hỗ trợ QR Code (link, văn bản, số tài khoản...), EAN-13, UPC-A, Code 128.',
    benefits: ['Miễn phí, không cần đăng nhập', 'Nhiều loại mã: QR, EAN-13, UPC-A, Code 128', 'Tải PNG dùng cho in ấn'],
    useCases: ['QR Code cho link website, VietQR', 'Mã vạch EAN-13 cho sản phẩm siêu thị', 'Code 128 cho mã nội bộ'],
    tips: ['QR Code: dán link, số tài khoản, thông tin WiFi', 'EAN-13: đúng 13 chữ số', 'Code 128: chữ và số linh hoạt'],
    faqs: [
      { question: 'VietQR có giới hạn số lượng không?', answer: 'Không. VietQR.io Public Access miễn phí, không đăng ký, không giới hạn. Nếu gặp 429 (quá tải) hãy thử lại sau.' },
      { question: 'QR Code mã hóa được gì?', answer: 'Link, văn bản, thông tin WiFi, vCard, email... VietQR dùng tab riêng cho chuyển khoản ngân hàng.' },
      { question: 'Có mất phí không?', answer: 'Miễn phí. Không dùng AI, không tính credit.' },
      { question: 'EAN-13 và UPC-A khác gì?', answer: 'EAN-13: 13 chữ số (chuẩn quốc tế). UPC-A: 12 chữ số (Bắc Mỹ).' },
      { question: 'Ảnh tải về dùng in được không?', answer: 'Có, PNG phù hợp in nhãn, bao bì.' },
      { question: 'Có cần đăng nhập không?', answer: 'Không bắt buộc.' },
    ],
  },
  'tao-tem-niem-phong-bao-hanh': {
    key: 'tao-tem-niem-phong-bao-hanh',
    pageTitle: 'Tạo tem niêm phong, tem bảo hành, tem hàng chính hãng bằng AI',
    pageDescription: 'AI thiết kế tem niêm phong, tem bảo hành, tem hàng chính hãng. Chọn logo, nhập tên thương hiệu. Xuất PNG, PDF chuẩn in. 1,5–3 credits/lượt.',
    path: '/tao-tem-niem-phong-bao-hanh',
    keywords: ['tem niêm phong', 'tem bảo hành', 'tem hàng chính hãng', 'security seal', 'warranty label', 'tạo tem nhãn', 'AI thiết kế tem'],
    serviceName: 'Tạo tem niêm phong, tem bảo hành, tem hàng chính hãng bằng AI',
    serviceDescription: 'AI thiết kế tem niêm phong (security seal), tem bảo hành (warranty label), tem hàng chính hãng (authentic seal). Upload logo, nhập thương hiệu. Xuất PNG, PDF chuẩn in.',
    h2: 'Tạo tem niêm phong, tem bảo hành, tem hàng chính hãng bằng AI',
    overview: 'Tem niêm phong dùng để đảm bảo sản phẩm chưa bị mở. Tem bảo hành ghi thời hạn và thông tin bảo hành. Tem hàng chính hãng xác nhận sản phẩm chính gốc. AI thiết kế tem chuyên nghiệp từ logo và nội dung, xuất PNG và PDF chuẩn in.',
    benefits: ['AI thiết kế tem chuyên nghiệp', 'Ba loại: niêm phong, bảo hành, hàng chính hãng', 'Upload logo, tên thương hiệu tùy chọn', 'Xuất PNG, PDF chuẩn in (bleed, crop marks)'],
    useCases: ['Tem niêm phong sản phẩm điện tử', 'Tem bảo hành thiết bị', 'Tem hàng chính hãng chống giả mạo'],
    tips: ['Tem niêm phong: nét đứt đỏ thể hiện tamper-evident', 'Tem bảo hành: ghi rõ hạn bảo hành', 'Tem hàng chính hãng: viền xanh, xác nhận chính gốc', 'In trên giấy decal, giấy nhiệt'],
    faqs: [
      { question: 'Có dùng AI không?', answer: 'Không. Tem tạo theo mẫu cố định, không dùng AI.' },
      { question: 'Có mất phí không?', answer: 'Miễn phí. Tải PNG không cần đăng nhập. Xuất PDF chuẩn in cần đăng nhập.' },
      { question: 'Tem niêm phong, bảo hành, hàng chính hãng khác gì?', answer: 'Niêm phong: nét đứt đỏ, chống mở. Bảo hành: nét liền đỏ, ghi hạn. Hàng chính hãng: viền xanh, xác nhận chính gốc.' },
      { question: 'Có in được không?', answer: 'Có. PDF có bleed 3mm, crop marks. Phù hợp giấy decal, giấy nhiệt.' },
      { question: 'Kích thước có sẵn?', answer: 'Có: 25×25, 40×60, 50×50, 50×70, 70×100 mm.' },
    ],
  },
  'che-anh': {
    key: 'che-anh',
    pageTitle: 'Chế ảnh meme online bằng AI',
    pageDescription: 'Chế ảnh meme online bằng AI nhanh và dễ dùng. Tạo nội dung vui nhộn cho social, cộng đồng và chiến dịch truyền thông.',
    path: '/che-anh',
    keywords: ['chế ảnh meme', 'tạo meme online', 'meme ai', 'chế ảnh nhanh'],
    serviceName: 'Chế ảnh meme bằng AI',
    serviceDescription: 'Tạo ảnh chế nhanh cho social và nội dung cộng đồng.',
    h2: 'Tạo ảnh meme nhanh để tăng tương tác mạng xã hội',
    overview: 'Ảnh meme là định dạng nội dung có tốc độ lan truyền cao nếu đúng ngữ cảnh. Công cụ này giúp bạn tạo nhanh ảnh chế từ ý tưởng ngắn, phù hợp cho page cộng đồng và social thương hiệu.',
    benefits: ['Tạo nội dung vui nhộn nhanh', 'Dễ bắt trend theo thời điểm', 'Tiết kiệm thời gian làm visual social'],
    useCases: ['Meme cho fanpage cộng đồng', 'Nội dung tương tác cho thương hiệu', 'Ảnh chế cho chiến dịch bắt trend'],
    tips: ['Theo sát ngữ cảnh thời điểm đăng', 'Giữ caption ngắn và dễ hiểu', 'Tránh nội dung nhạy cảm hoặc dễ gây tranh cãi'],
    faqs: [
      { question: 'Có cần template sẵn không?', answer: 'Không bắt buộc, bạn có thể bắt đầu từ ảnh và ý tưởng riêng.' },
      { question: 'Dùng cho page thương hiệu được không?', answer: 'Có, nếu phù hợp tệp khách hàng và giọng thương hiệu.' },
      { question: 'Ảnh chế có dùng quảng cáo được không?', answer: 'Thường phù hợp cho organic social hơn quảng cáo chuyển đổi trực tiếp.' },
      { question: 'Có thể tạo nhiều phiên bản không?', answer: 'Có, nên thử nhiều biến thể để chọn bản tương tác tốt hơn.' },
      { question: 'Có hỗ trợ người mới không?', answer: 'Có, giao diện đơn giản để thao tác nhanh.' },
    ],
  },
  'xoa-vat-the': {
    key: 'xoa-vat-the',
    pageTitle: 'Xóa vật thể trong ảnh bằng AI',
    pageDescription: 'Xóa vật thể thừa, người đi ngang và chi tiết gây nhiễu trong ảnh bằng AI. Giữ nền tự nhiên, phù hợp ảnh du lịch, sản phẩm, bất động sản.',
    path: '/xoa-vat-the',
    keywords: ['xóa vật thể', 'remove object ai', 'xóa người khỏi ảnh', 'xóa chi tiết thừa'],
    serviceName: 'Xóa vật thể bằng AI',
    serviceDescription: 'Loại bỏ vật thể không mong muốn và giữ nền ảnh tự nhiên.',
    h2: 'Làm sạch ảnh nhanh bằng cách xóa vật thể không mong muốn',
    overview: 'Ảnh đẹp thường bị giảm chất lượng vì vật thể thừa hoặc người đi ngang. Công cụ xóa vật thể giúp bạn làm sạch ảnh nhanh để dùng cho đăng bán, social hoặc tư liệu nội bộ.',
    benefits: ['Loại bỏ chi tiết gây rối khung hình', 'Giữ nền tự nhiên sau khi xóa', 'Giảm thời gian hậu kỳ thủ công'],
    useCases: ['Xóa dây điện, biển báo, vật cản', 'Xóa người đi ngang trong ảnh du lịch', 'Làm sạch ảnh sản phẩm và không gian'],
    tips: ['Chọn vùng xóa vừa phải để nền dễ tái tạo', 'Ưu tiên ảnh đủ sáng và rõ chi tiết', 'Nếu cần, thử lại với vùng chọn tối ưu hơn'],
    faqs: [
      { question: 'Có xóa người trong nền được không?', answer: 'Có, đây là use case phổ biến của công cụ.' },
      { question: 'Nền sau xóa có tự nhiên không?', answer: 'Hệ thống tối ưu để nền liền mạch và tự nhiên nhất có thể.' },
      { question: 'Dùng cho ảnh sản phẩm được không?', answer: 'Có, đặc biệt khi cần làm sạch hậu cảnh nhanh.' },
      { question: 'Có cần kỹ năng chỉnh ảnh không?', answer: 'Không, thao tác đơn giản và trực quan.' },
      { question: 'Bao lâu có kết quả?', answer: 'Thông thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'xoa-nen-png': {
    key: 'xoa-nen-png',
    pageTitle: 'Xóa nền ảnh online ra PNG trong suốt',
    pageDescription: 'Xóa nền ảnh online và xuất PNG trong suốt chất lượng cao cho TMĐT, thiết kế, social và in ấn. Tách chủ thể nhanh, mép tóc mượt, tải xuống PNG alpha.',
    path: '/xoa-nen-png',
    keywords: ['xóa nền png', 'xóa nền ảnh online', 'tách nền trong suốt', 'remove background png', 'tách nền sản phẩm'],
    serviceName: 'Xóa nền ảnh online ra PNG trong suốt',
    serviceDescription: 'Tách nền ảnh thành PNG trong suốt chất lượng cao cho TMĐT, thiết kế và social.',
    h2: 'Xóa nền ảnh online ra PNG trong suốt cho bán hàng và thiết kế',
    overview: 'Xóa nền PNG là bước quan trọng khi làm ảnh sản phẩm và thiết kế quảng cáo. Công cụ này giúp tách nền nhanh, cho file PNG alpha để bạn ghép nền mới và tái sử dụng trên nhiều kênh.',
    benefits: ['Trả đúng định dạng PNG nền trong suốt', 'Giữ viền chủ thể tự nhiên', 'Phù hợp workflow TMĐT và social'],
    useCases: ['Tạo ảnh sản phẩm nền trắng', 'Ghép sản phẩm vào banner quảng cáo', 'Tạo thư viện ảnh trong suốt cho thiết kế'],
    tips: ['Ưu tiên ảnh chủ thể rõ và đủ sáng', 'Tránh nền quá nhiễu hoặc trùng màu chủ thể', 'Chọn 4K khi cần hậu kỳ sâu'],
    faqs: [
      { question: 'Kết quả có phải PNG trong suốt không?', answer: 'Có, kết quả trả về là PNG có kênh alpha.' },
      { question: 'Có tải JPG từ tính năng này không?', answer: 'Không, để giữ nền trong suốt thì chỉ hỗ trợ tải PNG.' },
      { question: 'Phù hợp cho ảnh sản phẩm TMĐT không?', answer: 'Rất phù hợp cho shop online và đội vận hành catalog.' },
      { question: '2K và 4K khác gì?', answer: '2K phù hợp dùng nhanh hằng ngày, 4K phù hợp khi cần độ chi tiết cao hơn.' },
      { question: 'Có xử lý được tóc và viền mảnh không?', answer: 'Có, công cụ tối ưu để giữ rìa chủ thể tự nhiên.' },
    ],
  },
  'thay-nen-san-pham': {
    key: 'thay-nen-san-pham',
    pageTitle: 'Thay nền sản phẩm online bằng AI',
    pageDescription: 'Thay nền ảnh sản phẩm online bằng AI để tạo ảnh quảng cáo, ảnh sàn TMĐT và social nhanh. Giữ sản phẩm nổi bật, bối cảnh phù hợp ngành hàng.',
    path: '/thay-nen-san-pham',
    keywords: ['thay nền sản phẩm', 'đổi background sản phẩm ai', 'ảnh sản phẩm quảng cáo', 'product background ai'],
    serviceName: 'Thay nền sản phẩm bằng AI',
    serviceDescription: 'Tạo bối cảnh mới cho ảnh sản phẩm nhanh và đồng bộ theo chiến dịch.',
    h2: 'Tạo ảnh sản phẩm bắt mắt bằng cách thay nền đúng ngữ cảnh',
    overview: 'Một sản phẩm có thể cần nhiều bối cảnh khác nhau cho từng kênh bán. Công cụ thay nền sản phẩm giúp bạn tạo nhanh ảnh dùng cho sàn TMĐT, social và quảng cáo mà không cần chụp lại nhiều lần.',
    benefits: ['Tiết kiệm chi phí setup chụp bối cảnh', 'Tạo nhiều phiên bản ảnh cho từng kênh', 'Giữ sản phẩm là trung tâm khung hình'],
    useCases: ['Ảnh nền trắng cho sàn', 'Ảnh lifestyle cho social', 'Ảnh chiến dịch theo mùa cho quảng cáo'],
    tips: ['Chọn ảnh sản phẩm gốc đủ sáng', 'Mô tả bối cảnh đúng ngành hàng', 'Test nhiều phương án nền để tăng CTR'],
    faqs: [
      { question: 'Có dùng cho shop online nhỏ được không?', answer: 'Có, đây là nhóm dùng nhiều nhất vì tối ưu chi phí và thời gian.' },
      { question: 'Có cần chụp lại sản phẩm không?', answer: 'Không cần nếu ảnh gốc đủ chất lượng.' },
      { question: 'Có làm ảnh nhìn giả không?', answer: 'Hệ thống ưu tiên hòa hợp ánh sáng và bố cục để tự nhiên hơn.' },
      { question: 'Dùng được cho chạy quảng cáo không?', answer: 'Có, bạn có thể tạo nhiều biến thể ảnh để A/B test.' },
      { question: 'Nên chọn 2K hay 4K?', answer: '2K cho nhu cầu nhanh, 4K cho nhu cầu hậu kỳ và hiển thị lớn.' },
    ],
  },
  'tao-anh-3d': {
    key: 'tao-anh-3d',
    pageTitle: 'Tạo ảnh sản phẩm mẫu 3D bằng AI',
    pageDescription: 'Tạo ảnh sản phẩm mẫu 3D bằng AI nhanh cho quảng cáo và social. Dễ tạo mockup sản phẩm nổi bật, chuyên nghiệp.',
    path: '/tao-anh-3d',
    keywords: ['ảnh sản phẩm 3d', 'mockup 3d ai', 'tạo mockup sản phẩm', '3d product image'],
    serviceName: 'Tạo ảnh sản phẩm mẫu 3D bằng AI',
    serviceDescription: 'Tạo mockup 3D trực quan để trình bày sản phẩm chuyên nghiệp hơn.',
    h2: 'Tạo mockup sản phẩm 3D nhanh cho chiến dịch bán hàng',
    overview: 'Ảnh mockup 3D giúp sản phẩm nổi bật hơn trong feed social và trang bán hàng. Công cụ này hỗ trợ tạo nhanh hình ảnh 3D để bạn tăng tốc sản xuất nội dung quảng bá.',
    benefits: ['Tăng cảm nhận chuyên nghiệp của sản phẩm', 'Tạo nhanh nhiều concept ảnh quảng cáo', 'Giảm phụ thuộc vào studio 3D truyền thống'],
    useCases: ['Mockup sản phẩm mới trước khi ra mắt', 'Ảnh social cho chiến dịch theo mùa', 'Ảnh minh họa landing page sản phẩm'],
    tips: ['Chuẩn bị logo/ảnh gốc rõ nét', 'Giữ concept đồng bộ màu thương hiệu', 'Tạo nhiều góc nhìn để test hiệu quả'],
    faqs: [
      { question: 'Có cần biết dựng 3D không?', answer: 'Không, công cụ phù hợp cả người không chuyên 3D.' },
      { question: 'Dùng cho quảng cáo được không?', answer: 'Có, ảnh mockup 3D rất phù hợp cho ads và social.' },
      { question: 'Có tạo được nhiều phong cách không?', answer: 'Có, bạn có thể thay đổi mô tả để ra phong cách khác.' },
      { question: 'Ảnh đầu ra dùng cho web được không?', answer: 'Có, phù hợp cho landing page và listing sản phẩm.' },
      { question: 'Thời gian tạo có nhanh không?', answer: 'Thông thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'tao-mo-hinh-3d-tu-anh': {
    key: 'tao-mo-hinh-3d-tu-anh',
    pageTitle: 'Tạo mô hình 3D từ ảnh online',
    pageDescription: 'Tạo mô hình 3D từ ảnh bằng AI để preview sản phẩm nhanh, phục vụ thiết kế, trưng bày và truyền thông số.',
    path: '/tao-mo-hinh-3d-tu-anh',
    keywords: ['mô hình 3d từ ảnh', 'image to 3d ai', 'tạo model 3d online', 'preview 3d sản phẩm'],
    serviceName: 'Tạo mô hình 3D từ ảnh',
    serviceDescription: 'Chuyển ảnh 2D thành preview mô hình 3D để trình bày ý tưởng trực quan hơn.',
    h2: 'Chuyển ảnh 2D thành preview 3D để trình bày ý tưởng nhanh',
    overview: 'Khi cần mô tả sản phẩm theo góc nhìn trực quan hơn, mô hình 3D từ ảnh giúp bạn rút ngắn bước dựng thử. Công cụ phù hợp cho giai đoạn ý tưởng, pitch và mô phỏng nhanh.',
    benefits: ['Tạo preview 3D nhanh từ ảnh có sẵn', 'Dễ dùng cho thuyết trình và duyệt concept', 'Giảm thời gian dựng mẫu ban đầu'],
    useCases: ['Preview sản phẩm cho đội sale', 'Minh họa concept cho khách hàng', 'Tạo visual cho trang giới thiệu sản phẩm'],
    tips: ['Dùng ảnh gốc rõ chủ thể', 'Tránh nền quá rối', 'Xuất bản chất lượng cao khi cần trình chiếu'],
    faqs: [
      { question: 'Có phải mô hình CAD hoàn chỉnh không?', answer: 'Đây là preview 3D phục vụ trực quan và truyền thông, không thay thế file kỹ thuật chuyên sâu.' },
      { question: 'Người mới có dùng được không?', answer: 'Có, thao tác đơn giản và không yêu cầu kỹ năng dựng 3D.' },
      { question: 'Dùng để trình bày ý tưởng được không?', answer: 'Rất phù hợp cho pitch nhanh và duyệt concept.' },
      { question: 'Có cần nhiều ảnh góc khác nhau không?', answer: 'Một ảnh vẫn có thể dùng, ảnh rõ sẽ cho kết quả tốt hơn.' },
      { question: 'Bao lâu có kết quả?', answer: 'Thông thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'thiet-ke-noi-ngoai-that': {
    key: 'thiet-ke-noi-ngoai-that',
    pageTitle: 'Thiết kế nội ngoại thất từ ảnh bằng AI',
    pageDescription: 'Thiết kế nội thất và ngoại thất bằng AI từ ảnh thật. Tạo phương án decor nhanh, trực quan cho nhà ở, cửa hàng và không gian làm việc.',
    path: '/thiet-ke-noi-ngoai-that',
    keywords: ['thiết kế nội thất ai', 'thiết kế ngoại thất ai', 'decor từ ảnh', 'cải tạo không gian ai'],
    serviceName: 'Thiết kế nội ngoại thất bằng AI',
    serviceDescription: 'Tạo nhanh phương án thiết kế không gian từ ảnh hiện trạng.',
    h2: 'Xem trước phương án nội ngoại thất trước khi thi công',
    overview: 'Thay vì tưởng tượng mơ hồ, bạn có thể dùng ảnh hiện trạng để tạo nhanh phương án nội ngoại thất. Công cụ này phù hợp cho chủ nhà, kiến trúc sư và đội thi công cần duyệt hướng thiết kế nhanh.',
    benefits: ['Có hình minh họa trực quan trước khi làm', 'Dễ trao đổi với gia đình hoặc khách hàng', 'Rút ngắn thời gian chốt phong cách'],
    useCases: ['Cải tạo phòng khách, phòng ngủ', 'Định hướng mặt tiền nhà phố', 'Lên concept cho quán cà phê và showroom'],
    tips: ['Ảnh hiện trạng nên chụp đủ sáng', 'Mô tả rõ phong cách mong muốn', 'So sánh nhiều phương án trước khi chốt'],
    faqs: [
      { question: 'Có thay thế bản vẽ kỹ thuật không?', answer: 'Không, đây là công cụ mô phỏng ý tưởng trực quan trước giai đoạn kỹ thuật chi tiết.' },
      { question: 'Dùng cho nhà ở và cửa hàng đều được không?', answer: 'Có, phù hợp nhiều loại không gian khác nhau.' },
      { question: 'Có hỗ trợ phong cách hiện đại/tối giản không?', answer: 'Có, bạn có thể mô tả phong cách cụ thể để tạo phương án phù hợp.' },
      { question: 'Có dùng cho tư vấn khách hàng được không?', answer: 'Có, rất tiện cho bước trình bày ý tưởng ban đầu.' },
      { question: 'Kết quả có nhanh không?', answer: 'Thường từ vài giây đến khoảng 1 phút tùy mức xử lý.' },
    ],
  },
  'xay-nha-tu-dat-nen': {
    key: 'xay-nha-tu-dat-nen',
    pageTitle: 'Thiết kế nhà từ đất nền bằng AI',
    pageDescription: 'Thiết kế nhà từ ảnh đất nền bằng AI để xem phối cảnh nhanh. Hỗ trợ lên ý tưởng bố cục, phong cách và hướng công năng ban đầu.',
    path: '/xay-nha-tu-dat-nen',
    keywords: ['xây nhà từ đất nền', 'thiết kế nhà ai', 'phối cảnh nhà từ đất', 'ý tưởng nhà ở'],
    serviceName: 'Thiết kế nhà từ đất nền bằng AI',
    serviceDescription: 'Tạo phối cảnh nhà nhanh từ ảnh đất nền để định hình ý tưởng ban đầu.',
    h2: 'Xem phối cảnh nhà nhanh từ ảnh đất nền thực tế',
    overview: 'Khi mới bắt đầu xây nhà, đa số người dùng cần hình dung tổng thể trước khi đi vào bản vẽ kỹ thuật. Công cụ này giúp tạo phối cảnh nhanh từ ảnh đất nền để dễ thảo luận phương án.',
    benefits: ['Hình dung công trình trước khi làm hồ sơ kỹ thuật', 'Dễ trao đổi ý tưởng với gia đình', 'Tiết kiệm thời gian thử concept ban đầu'],
    useCases: ['Lên ý tưởng nhà phố', 'Thử phong cách mặt tiền', 'Minh họa sơ bộ cho phương án công năng'],
    tips: ['Chụp rõ mặt bằng đất nền', 'Mô tả nhu cầu sử dụng chính', 'Thử nhiều phong cách để so sánh'],
    faqs: [
      { question: 'Có thay thế thiết kế kiến trúc chuyên môn không?', answer: 'Không, đây là bước định hướng ý tưởng trực quan ban đầu.' },
      { question: 'Phù hợp người chưa có kinh nghiệm xây nhà không?', answer: 'Có, công cụ hỗ trợ hình dung nhanh và dễ hiểu.' },
      { question: 'Có dùng cho tư vấn khách hàng được không?', answer: 'Có, phù hợp cho giai đoạn trình bày concept.' },
      { question: 'Có tạo nhiều phương án được không?', answer: 'Có, bạn nên tạo nhiều phương án để chọn hướng tối ưu.' },
      { question: 'Bao lâu có kết quả?', answer: 'Thông thường chỉ từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'tao-anh-chain-dung': {
    key: 'tao-anh-chain-dung',
    pageTitle: 'Tạo ảnh chân dung chuyên nghiệp bằng AI',
    pageDescription: 'Tạo ảnh chân dung chuyên nghiệp bằng AI cho CV, hồ sơ doanh nghiệp và LinkedIn. Kết quả tự nhiên, chỉn chu, dùng ngay.',
    path: '/tao-anh-chain-dung',
    keywords: ['ảnh chân dung ai', 'ai headshot', 'ảnh profile chuyên nghiệp', 'ảnh linkedin'],
    serviceName: 'Tạo ảnh chân dung chuyên nghiệp bằng AI',
    serviceDescription: 'Tạo ảnh chân dung chỉn chu cho hồ sơ cá nhân và công việc.',
    h2: 'Tạo ảnh chân dung chuyên nghiệp để nâng cấp hồ sơ cá nhân',
    overview: 'Ảnh chân dung profile tốt giúp tạo ấn tượng mạnh hơn trên CV, LinkedIn và website doanh nghiệp. Công cụ này hỗ trợ tạo ảnh chân dung sạch, chuyên nghiệp, phù hợp nhiều mục tiêu nghề nghiệp.',
    benefits: ['Nâng chất lượng ảnh profile nhanh', 'Giữ nét tự nhiên khuôn mặt', 'Phù hợp cá nhân, team và doanh nghiệp'],
    useCases: ['Ảnh CV và hồ sơ ứng tuyển', 'Ảnh đại diện LinkedIn', 'Ảnh profile nhân sự trên website công ty'],
    tips: ['Dùng ảnh gốc rõ mặt và đủ sáng', 'Giữ góc chụp chính diện hoặc lệch nhẹ', 'Chọn phong cách phù hợp ngành nghề'],
    faqs: [
      { question: 'Ảnh có phù hợp LinkedIn không?', answer: 'Có, đây là mục đích sử dụng rất phổ biến của tính năng.' },
      { question: 'Có giữ gương mặt thật không?', answer: 'Có, hệ thống ưu tiên giữ nhận diện tự nhiên.' },
      { question: 'Dùng cho profile doanh nghiệp được không?', answer: 'Có, phù hợp để đồng bộ ảnh nhân sự.' },
      { question: 'Có cần studio không?', answer: 'Không, bạn có thể bắt đầu từ ảnh chụp thông thường.' },
      { question: 'Bao lâu nhận kết quả?', answer: 'Thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'mo-rong-khung-hinh': {
    key: 'mo-rong-khung-hinh',
    pageTitle: 'Mở rộng khung hình ảnh bằng AI',
    pageDescription: 'Mở rộng khung hình ảnh online bằng AI (outpaint) để đổi tỷ lệ 1:1, 4:5, 16:9 nhanh và tự nhiên, phù hợp social và quảng cáo.',
    path: '/mo-rong-khung-hinh',
    keywords: ['mở rộng khung hình', 'outpaint ai', 'extend image', 'đổi tỷ lệ ảnh'],
    serviceName: 'Mở rộng khung hình bằng AI',
    serviceDescription: 'Mở rộng vùng ảnh tự nhiên để phù hợp nhiều tỷ lệ hiển thị.',
    h2: 'Mở rộng ảnh nhanh cho social, banner và màn hình rộng',
    overview: 'Khi một ảnh gốc không đúng tỷ lệ đăng, mở rộng khung hình giúp bạn tránh cắt mất nội dung quan trọng. Công cụ AI hỗ trợ outpaint để ảnh đầy đặn hơn trên nhiều nền tảng.',
    benefits: ['Đổi tỷ lệ ảnh nhanh không cần chụp lại', 'Giữ bố cục chính của ảnh gốc', 'Phù hợp social, banner và cover'],
    useCases: ['Đổi ảnh vuông sang ngang 16:9', 'Mở rộng ảnh cho cover fanpage', 'Tối ưu ảnh cho layout website'],
    tips: ['Giữ chủ thể chính ở vùng trung tâm', 'Mở rộng vừa phải để tự nhiên hơn', 'Kiểm tra lại cạnh ảnh trước khi xuất'],
    faqs: [
      { question: 'Mở rộng ảnh có bị giả không?', answer: 'Hệ thống tối ưu để vùng mở rộng hòa hợp ảnh gốc tự nhiên nhất có thể.' },
      { question: 'Dùng để đổi tỷ lệ social được không?', answer: 'Có, đây là mục đích sử dụng phổ biến.' },
      { question: 'Có cần kỹ năng thiết kế không?', answer: 'Không, thao tác phù hợp người mới.' },
      { question: 'Dùng cho ảnh quảng cáo được không?', answer: 'Có, rất tiện khi cần nhiều tỷ lệ cho đa kênh.' },
      { question: 'Bao lâu có kết quả?', answer: 'Thông thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'hoan-doi-khuon-mat': {
    key: 'hoan-doi-khuon-mat',
    pageTitle: 'Hoán đổi khuôn mặt bằng AI tự nhiên',
    pageDescription: 'Hoán đổi khuôn mặt bằng AI nhanh, giữ ánh sáng và tổng thể tự nhiên. Phù hợp giải trí, nội dung sáng tạo và thử ý tưởng hình ảnh.',
    path: '/hoan-doi-khuon-mat',
    keywords: ['hoán đổi khuôn mặt', 'face swap ai', 'ghép mặt ai', 'đổi mặt online'],
    serviceName: 'Hoán đổi khuôn mặt bằng AI',
    serviceDescription: 'Hoán đổi khuôn mặt nhanh với độ hòa hợp tự nhiên cao.',
    h2: 'Hoán đổi khuôn mặt nhanh cho nội dung sáng tạo',
    overview: 'Face swap là tính năng giải trí và sáng tạo nội dung được dùng nhiều trên social. Công cụ này giúp bạn tạo ảnh hoán đổi khuôn mặt nhanh, trực quan và dễ dùng.',
    benefits: ['Thao tác nhanh, kết quả dễ chia sẻ', 'Hòa hợp ánh sáng và tông ảnh tổng thể', 'Phù hợp nội dung sáng tạo và giải trí'],
    useCases: ['Nội dung giải trí trên social', 'Minh họa concept truyền thông', 'Tạo visual thử nghiệm cho chiến dịch'],
    tips: ['Dùng ảnh mặt rõ và hướng nhìn tương đồng', 'Tránh ảnh bị che khuất nhiều', 'Sử dụng có trách nhiệm và tuân thủ pháp luật'],
    faqs: [
      { question: 'Face swap có tự nhiên không?', answer: 'Kết quả phụ thuộc chất lượng ảnh, công cụ ưu tiên hòa hợp tự nhiên tối đa.' },
      { question: 'Dùng cho mục đích thương mại được không?', answer: 'Có thể, nhưng cần đảm bảo quyền sử dụng hình ảnh hợp pháp.' },
      { question: 'Có phù hợp nội dung giải trí không?', answer: 'Rất phù hợp cho social content.' },
      { question: 'Có cần ảnh chất lượng cao không?', answer: 'Ảnh rõ mặt sẽ cho kết quả tốt hơn rõ rệt.' },
      { question: 'Bao lâu có kết quả?', answer: 'Thông thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'dich-anh-tai-lieu': {
    key: 'dich-anh-tai-lieu',
    pageTitle: 'Dịch ảnh tài liệu bằng AI OCR',
    pageDescription: 'Dịch ảnh tài liệu bằng AI OCR nhanh, giữ bố cục dễ đọc. Phù hợp tài liệu chụp, scan, brochure và ảnh văn bản đa ngôn ngữ.',
    path: '/dich-anh-tai-lieu',
    keywords: ['dịch ảnh tài liệu', 'ocr dịch ảnh', 'translate image ai', 'dịch ảnh văn bản'],
    serviceName: 'Dịch ảnh tài liệu bằng AI',
    serviceDescription: 'Nhận diện chữ từ ảnh và dịch nhanh, giữ trải nghiệm đọc trực quan.',
    h2: 'Dịch ảnh tài liệu nhanh để xử lý công việc đa ngôn ngữ',
    overview: 'Khi làm việc với ảnh tài liệu hoặc ảnh scan ngoại ngữ, việc dịch thủ công tốn nhiều thời gian. Công cụ này kết hợp nhận diện chữ và dịch để bạn đọc nội dung nhanh hơn trong cùng một quy trình.',
    benefits: ['Tăng tốc xử lý tài liệu đa ngôn ngữ', 'Phù hợp ảnh chụp và ảnh scan', 'Hữu ích cho học tập, công việc và vận hành'],
    useCases: ['Dịch ảnh hướng dẫn sản phẩm', 'Dịch tài liệu học tập từ ảnh', 'Dịch brochure hoặc menu từ ảnh chụp'],
    tips: ['Chụp ảnh rõ, không rung', 'Canh khung đủ nội dung cần dịch', 'Nếu tài liệu dài, xử lý theo từng phần'],
    faqs: [
      { question: 'Có dịch được ảnh chụp điện thoại không?', answer: 'Có, miễn ảnh đủ rõ để nhận diện chữ.' },
      { question: 'Có phù hợp tài liệu scan không?', answer: 'Có, đây là loại đầu vào rất phổ biến.' },
      { question: 'Có giữ bố cục dễ đọc không?', answer: 'Kết quả ưu tiên trải nghiệm đọc và theo dõi nội dung.' },
      { question: 'Dịch được nhiều ảnh liên tiếp không?', answer: 'Có, bạn có thể xử lý theo batch tùy flow hỗ trợ.' },
      { question: 'Bao lâu có kết quả?', answer: 'Tùy số lượng ảnh và độ dài nội dung, thường từ vài giây đến vài phút.' },
    ],
  },
  'tao-video-tu-anh': {
    key: 'tao-video-tu-anh',
    pageTitle: 'Tạo video từ ảnh bằng AI online',
    pageDescription: 'Tạo video từ ảnh bằng AI nhanh để làm nội dung social, quảng cáo và truyền thông thương hiệu. Chuyển ảnh tĩnh thành video ngắn trực quan.',
    path: '/tao-video-tu-anh',
    keywords: ['tạo video từ ảnh', 'image to video ai', 'video ai online', 'ảnh thành video'],
    serviceName: 'Tạo video từ ảnh bằng AI',
    serviceDescription: 'Chuyển ảnh tĩnh thành video ngắn để tăng hiệu quả truyền thông và quảng cáo.',
    h2: 'Biến ảnh tĩnh thành video ngắn để tăng tương tác nhanh',
    overview: 'Video ngắn luôn có khả năng thu hút tốt hơn ảnh tĩnh ở nhiều nền tảng. Tính năng này giúp bạn chuyển nhanh ảnh thành video để dùng cho social, quảng cáo và nội dung giới thiệu sản phẩm.',
    benefits: ['Tăng khả năng thu hút khi đăng bài', 'Tận dụng ảnh có sẵn để tạo video nhanh', 'Phù hợp team nội dung cần sản xuất liên tục'],
    useCases: ['Video sản phẩm cho TikTok/Reels', 'Video teaser cho chiến dịch mới', 'Video ngắn cho trang đích và fanpage'],
    tips: ['Chọn ảnh có chủ thể rõ để chuyển động đẹp', 'Giữ thông điệp ngắn, tập trung một ý chính', 'Tạo nhiều phiên bản để test hiệu quả hiển thị'],
    faqs: [
      { question: 'Ảnh nào phù hợp để tạo video?', answer: 'Ảnh rõ chủ thể, đủ sáng và bố cục gọn thường cho kết quả chuyển động tốt hơn.' },
      { question: 'Dùng cho quảng cáo social được không?', answer: 'Có, video ngắn từ ảnh rất phù hợp cho social ads và nội dung thu hút.' },
      { question: 'Có cần biết dựng video không?', answer: 'Không, công cụ tối ưu cho thao tác nhanh của người không chuyên.' },
      { question: 'Có tạo nhiều phiên bản video được không?', answer: 'Có, bạn nên tạo nhiều biến thể để chọn bản hiệu quả nhất.' },
      { question: 'Bao lâu có kết quả?', answer: 'Thời gian xử lý phụ thuộc cấu hình và tải hệ thống, thường từ vài chục giây đến vài phút.' },
    ],
  },
  'nhac-nen-ai': {
    key: 'nhac-nen-ai',
    pageTitle: 'Tạo nhạc nền AI thời gian thực',
    pageDescription: 'Tạo nhạc nền AI độc quyền theo prompt bằng Lyria RealTime. Phát liên tục, đổi mood nhanh, phù hợp TikTok, YouTube và podcast.',
    path: '/nhac-nen-ai',
    keywords: ['tạo nhạc nền ai', 'ai background music', 'lyria realtime', 'nhạc không bản quyền ai'],
    serviceName: 'AI Background Music với Lyria RealTime',
    serviceDescription: 'Tạo nhạc nền instrumental độc quyền theo prompt và phát realtime.',
    h2: 'Tạo nhạc nền độc quyền cho video bằng AI thời gian thực',
    overview: 'Tính năng này giúp creator tạo nhạc nền instrumental ngay tại chỗ bằng Lyria RealTime, tránh phụ thuộc thư viện nhạc lặp lại và giảm rủi ro bản quyền.',
    benefits: ['Nhạc sinh tại chỗ theo prompt riêng', 'Phát liên tục, không cần render chờ lâu', 'Dễ dùng cho video ngắn, livestream và podcast'],
    useCases: ['Nhạc nền TikTok/Reels', 'Nhạc lofi cho video học tập', 'Nhạc ambience cho podcast và stream'],
    tips: ['Viết prompt rõ thể loại + mood', 'Bắt đầu với BPM vừa phải để dễ nghe', 'Tinh chỉnh dần để chuyển mượt'],
    faqs: [
      { question: 'Nhạc tạo ra có lời không?', answer: 'Lyria RealTime hiện tập trung vào nhạc instrumental (không lời).' },
      { question: 'Có thể đổi phong cách khi đang phát không?', answer: 'Có, bạn có thể gửi prompt mới theo thời gian thực để nhạc chuyển dần.' },
      { question: 'Dùng cho video social được không?', answer: 'Có, đây là use case chính của tính năng.' },
      { question: 'Có cần biết sản xuất âm nhạc không?', answer: 'Không, người dùng phổ thông vẫn có thể bắt đầu bằng prompt đơn giản.' },
      { question: 'Làm sao để nhạc ổn định hơn?', answer: 'Nên điều chỉnh prompt và config từng bước thay vì đổi đột ngột.' },
    ],
  },
  'ai-dj': {
    key: 'ai-dj',
    pageTitle: 'Bàn mix AI DJ tương tác realtime',
    pageDescription: 'Bàn mix AI DJ trên web: kéo BPM, Density, Brightness để biến đổi nhạc realtime với Lyria. Trải nghiệm DJ AI trực tiếp.',
    path: '/ai-dj',
    keywords: ['ai dj', 'bàn mix ai', 'lyria dj', 'mix nhạc realtime'],
    serviceName: 'Interactive AI DJ',
    serviceDescription: 'Điều khiển nhạc realtime bằng thanh trượt BPM, Density và Brightness.',
    h2: 'Biến người dùng thành DJ AI ngay trên trình duyệt',
    overview: 'AI DJ giúp bạn điều khiển texture âm nhạc trực tiếp mà không cần phần mềm DJ truyền thống, phù hợp trải nghiệm giải trí và activation campaign.',
    benefits: ['Điều khiển nhạc theo thời gian thực', 'Tạo trải nghiệm tương tác cao trên website', 'Dễ dùng cho sự kiện online và livestream'],
    useCases: ['Mini game âm nhạc cho landing page', 'Nhạc nền linh hoạt cho livestream', 'Trải nghiệm thương hiệu tương tác'],
    tips: ['Thay đổi BPM theo từng nhịp nhỏ', 'Kết hợp density + brightness để đổi màu âm', 'Reset context khi thay đổi lớn'],
    faqs: [
      { question: 'AI DJ có cần thiết bị MIDI không?', answer: 'Không bắt buộc, bạn có thể dùng trực tiếp bằng thanh trượt trên web.' },
      { question: 'Có thể dùng cho sự kiện livestream không?', answer: 'Có, đây là một kịch bản phù hợp.' },
      { question: 'Thông số nào tác động nhiều nhất?', answer: 'BPM thay đổi nhịp rõ nhất; density và brightness đổi texture và màu âm.' },
      { question: 'Có thể dừng/tạm dừng nhạc không?', answer: 'Có, hỗ trợ play, pause, stop theo phiên realtime.' },
      { question: 'Có phù hợp người mới không?', answer: 'Có, thao tác đơn giản và trực quan.' },
    ],
  },
  'nhac-theo-cam-xuc-anh': {
    key: 'nhac-theo-cam-xuc-anh',
    pageTitle: 'Tạo nhạc theo cảm xúc ảnh bằng AI',
    pageDescription: 'Upload ảnh và để AI phân tích mood để tạo nhạc tương ứng với Lyria RealTime. Trải nghiệm đa giác quan ảnh + nhạc cho NanoAI.',
    path: '/nhac-theo-cam-xuc-anh',
    keywords: ['image to music', 'nhạc theo cảm xúc ảnh', 'ai music from image', 'lyria realtime image'],
    serviceName: 'Image-to-Music cho NanoAI',
    serviceDescription: 'Phân tích mood ảnh và chuyển thành prompt nhạc realtime.',
    h2: 'Kết hợp ảnh và nhạc để tạo trải nghiệm đa giác quan',
    overview: 'Image-to-Music giúp ảnh không chỉ đẹp mà còn có lớp âm thanh tương ứng, tạo trải nghiệm khác biệt cho người xem trong các flow sáng tạo nội dung.',
    benefits: ['Tự động suy ra mood nhạc từ ảnh', 'Tăng chiều sâu cảm xúc cho content', 'Khác biệt so với công cụ xử lý ảnh thông thường'],
    useCases: ['Ảnh hoàng hôn + nhạc acoustic nhẹ', 'Ảnh đô thị đêm + nhạc synthwave', 'Ảnh sản phẩm premium + ambient sang trọng'],
    tips: ['Chọn ảnh rõ bối cảnh chính', 'Tinh chỉnh prompt nhạc sau khi AI đề xuất', 'Dùng thêm bàn mix để tối ưu mood'],
    faqs: [
      { question: 'AI phân tích ảnh để tạo nhạc như thế nào?', answer: 'Hệ thống đọc mood thị giác và chuyển thành prompt âm nhạc tương ứng.' },
      { question: 'Có thể chỉnh lại prompt sau khi phân tích không?', answer: 'Có, bạn có thể sửa prompt trước hoặc trong lúc phát.' },
      { question: 'Dùng được với ảnh từ các tính năng NanoAI khác không?', answer: 'Có, đây là luồng tích hợp được khuyến nghị.' },
      { question: 'Có hỗ trợ ảnh sản phẩm không?', answer: 'Có, phù hợp cho content quảng cáo và social.' },
      { question: 'Nhạc tạo ra có realtime không?', answer: 'Có, nhạc được sinh và điều khiển theo thời gian thực.' },
    ],
  },
  'dieu-khien-nhac-realtime': {
    key: 'dieu-khien-nhac-realtime',
    pageTitle: 'Điều khiển nhạc realtime bằng prompt',
    pageDescription: 'Đang phát nhạc và thêm prompt mới ngay lập tức: thêm drum, đổi mood, đổi nhạc cụ mà không dừng stream với Lyria RealTime.',
    path: '/dieu-khien-nhac-realtime',
    keywords: ['realtime prompting music', 'điều khiển nhạc realtime', 'lyria prompt', 'ai music control'],
    serviceName: 'Real-time Prompting cho nhạc AI',
    serviceDescription: 'Điều khiển và biến đổi nhạc đang phát bằng prompt mới theo thời gian thực.',
    h2: 'Chèn prompt mới khi đang phát để đổi nhạc tức thì',
    overview: 'Tính năng này cho phép streamers, podcasters và creator thay đổi không khí âm nhạc theo diễn biến nội dung mà không cần dừng nhạc và phát lại từ đầu.',
    benefits: ['Đổi nhạc theo ngữ cảnh tức thì', 'Giữ mạch nghe liên tục khi stream', 'Linh hoạt cho podcast và talkshow'],
    useCases: ['Talkshow đổi mood theo chủ đề', 'Stream game thêm nhạc dồn dập lúc cao trào', 'Podcast đổi nhạc nền theo phân đoạn'],
    tips: ['Chèn prompt theo lớp (layer) thay vì đổi toàn bộ', 'Dùng trọng số vừa phải để chuyển mượt', 'Lưu prompt hiệu quả để tái sử dụng'],
    faqs: [
      { question: 'Có phải dừng nhạc để đổi prompt không?', answer: 'Không, bạn có thể chèn prompt ngay khi nhạc đang phát.' },
      { question: 'Prompt mới có áp ngay không?', answer: 'Có, hệ thống sẽ chuyển dần theo prompt mới theo thời gian thực.' },
      { question: 'Có phù hợp cho streamer/podcaster không?', answer: 'Rất phù hợp vì cần đổi mood liên tục theo nội dung.' },
      { question: 'Có thể chèn nhiều prompt liên tiếp không?', answer: 'Có, nên chèn theo từng bước để chuyển cảnh mượt hơn.' },
      { question: 'Có cần phần mềm âm nhạc chuyên dụng không?', answer: 'Không, dùng trực tiếp trên giao diện web là đủ.' },
    ],
  },
  'thu-do-online-1-nguoi': {
    key: 'thu-do-online-1-nguoi',
    pageTitle: 'Thử đồ online 1 người bằng AI',
    pageDescription: 'Thử đồ online 1 người bằng AI từ ảnh thật. Giúp shop và khách xem nhanh outfit trước khi mua, tăng trải nghiệm và giảm đổi trả.',
    path: '/thu-do-online/1-nguoi',
    keywords: ['thử đồ online 1 người', 'ai try on', 'thử quần áo ảo', 'phối đồ ai'],
    serviceName: 'Thử đồ online 1 người bằng AI',
    serviceDescription: 'Áp trang phục lên ảnh người dùng để xem nhanh outfit trước khi mua.',
    h2: 'Thử đồ online 1 người để xem outfit trước khi chốt mua',
    overview: 'Try-on 1 người là flow phổ biến nhất cho shop thời trang và người mua cá nhân. Công cụ giúp xem nhanh trang phục lên người thật để giảm cảm giác mua hàng mơ hồ.',
    benefits: ['Xem trước outfit nhanh từ ảnh thật', 'Tăng tự tin trước khi mua', 'Hỗ trợ shop tạo nội dung thử đồ'],
    useCases: ['Khách tự thử đồ trước khi chốt', 'Shop làm ảnh demo sản phẩm', 'Stylist gợi ý phối đồ cho khách'],
    tips: ['Chọn ảnh người đứng rõ toàn thân hoặc bán thân', 'Ảnh trang phục nên rõ form', 'Giữ ánh sáng ổn định để kết quả tự nhiên'],
    faqs: [
      { question: 'Thử đồ online có chính xác không?', answer: 'Kết quả mang tính trực quan cao để hỗ trợ quyết định mua nhanh hơn.' },
      { question: 'Ảnh chụp điện thoại dùng được không?', answer: 'Có, nếu ảnh đủ sáng và rõ dáng người.' },
      { question: 'Phù hợp cho shop thời trang không?', answer: 'Rất phù hợp để tăng tốc sản xuất nội dung bán hàng.' },
      { question: 'Có cần người mẫu thật không?', answer: 'Không cần, bạn có thể dùng ảnh có sẵn.' },
      { question: 'Bao lâu ra ảnh?', answer: 'Thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'thu-do-online-2-nguoi': {
    key: 'thu-do-online-2-nguoi',
    pageTitle: 'Thử đồ online 2 người bằng AI',
    pageDescription: 'Thử đồ online cho 2 người bằng AI để phối đồ đôi nhanh, trực quan. Phù hợp cặp đôi, studio và shop thời trang.',
    path: '/thu-do-online/2-nguoi',
    keywords: ['thử đồ 2 người', 'phối đồ đôi', 'couple try on', 'ai thử đồ'],
    serviceName: 'Thử đồ online 2 người bằng AI',
    serviceDescription: 'Phối đồ đôi nhanh từ ảnh thật cho cặp đôi và nội dung bán hàng.',
    h2: 'Phối đồ đôi trực quan với tính năng thử đồ 2 người',
    overview: 'Try-on 2 người giúp bạn xem tổng thể outfit đôi trong cùng một khung hình. Tính năng này được dùng nhiều cho shop couple, chụp concept và gợi ý phối đồ theo cặp.',
    benefits: ['Xem outfit đôi trong một ảnh', 'Tiết kiệm thời gian thử nhiều set', 'Tăng chất lượng tư vấn cho khách hàng'],
    useCases: ['Shop thời trang đôi', 'Concept chụp lookbook cặp', 'Tư vấn phối đồ cho khách'],
    tips: ['Ảnh hai người nên rõ vị trí', 'Mỗi bộ đồ nên chụp tách bạch', 'Chọn ảnh nền gọn để nhìn outfit rõ hơn'],
    faqs: [
      { question: 'Có áp riêng trang phục cho từng người không?', answer: 'Có, flow 2 người hỗ trợ áp trang phục tương ứng từng vị trí.' },
      { question: 'Phù hợp cho shop couple không?', answer: 'Rất phù hợp cho nhóm sản phẩm đồ đôi.' },
      { question: 'Ảnh đầu vào cần điều kiện gì?', answer: 'Ưu tiên ảnh rõ người và ánh sáng đủ.' },
      { question: 'Có dùng cho nội dung social được không?', answer: 'Có, ảnh thử đồ đôi có tính chia sẻ cao.' },
      { question: 'Có nhanh không?', answer: 'Thông thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'thu-do-online-3-nguoi': {
    key: 'thu-do-online-3-nguoi',
    pageTitle: 'Thử đồ online 3 người bằng AI',
    pageDescription: 'Thử đồ nhóm 3 người bằng AI để phối outfit đồng bộ nhanh cho gia đình, bạn bè và đội nhóm bán hàng.',
    path: '/thu-do-online/3-nguoi',
    keywords: ['thử đồ 3 người', 'thử đồ nhóm', 'group try on ai', 'phối đồ nhóm'],
    serviceName: 'Thử đồ online 3 người bằng AI',
    serviceDescription: 'Thử outfit nhóm 3 người nhanh để đồng bộ concept và phong cách.',
    h2: 'Thử đồ nhóm 3 người để chốt concept outfit nhanh',
    overview: 'Với ảnh nhóm 3 người, việc thử đồ thủ công rất tốn thời gian. Tính năng này giúp bạn xem trước tổng thể outfit nhóm để chốt concept nhanh cho gia đình, bạn bè hoặc team.',
    benefits: ['Đồng bộ trang phục theo nhóm', 'Giảm thời gian chỉnh sửa thủ công', 'Dễ dùng cho campaign nhóm nhỏ'],
    useCases: ['Concept ảnh gia đình 3 người', 'Ảnh nhóm bạn theo chủ đề', 'Visual đội ngũ bán hàng'],
    tips: ['Xác định rõ vị trí từng người trong ảnh', 'Chọn trang phục có form rõ', 'Ưu tiên ảnh gốc đủ sáng'],
    faqs: [
      { question: 'Có cần tách ảnh từng người không?', answer: 'Không, bạn có thể dùng ảnh nhóm và gán trang phục theo vị trí.' },
      { question: 'Có phù hợp gia đình nhỏ không?', answer: 'Có, đây là use case rất phổ biến.' },
      { question: 'Dùng cho team marketing được không?', answer: 'Có, thuận tiện để dựng concept đồng phục nhanh.' },
      { question: 'Kết quả có tự nhiên không?', answer: 'Công cụ tối ưu để outfit hòa hợp tổng thể ảnh.' },
      { question: 'Thời gian xử lý bao lâu?', answer: 'Thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'thu-do-online-4-nguoi': {
    key: 'thu-do-online-4-nguoi',
    pageTitle: 'Thử đồ online 4 người bằng AI',
    pageDescription: 'Thử đồ nhóm 4 người bằng AI để dựng concept trang phục đồng bộ cho gia đình, team và chiến dịch nội dung.',
    path: '/thu-do-online/4-nguoi',
    keywords: ['thử đồ 4 người', 'phối đồ nhóm 4', 'group try on', 'thử đồ ai'],
    serviceName: 'Thử đồ online 4 người bằng AI',
    serviceDescription: 'Áp trang phục đồng bộ cho nhóm 4 người trực quan và nhanh chóng.',
    h2: 'Dựng nhanh concept outfit nhóm 4 người',
    overview: 'Try-on 4 người phù hợp với nhu cầu phối đồ nhóm lớn hơn, nơi sự đồng bộ tổng thể quan trọng hơn từng chi tiết riêng lẻ. Công cụ giúp chốt nhanh phương án hình ảnh trước khi chụp hoặc đăng.',
    benefits: ['Xem nhanh tổng thể outfit nhóm', 'Hỗ trợ concept gia đình và team', 'Tăng tốc chuẩn bị ảnh truyền thông'],
    useCases: ['Ảnh gia đình 4 người', 'Ảnh nhóm đồng phục', 'Visual chiến dịch team-based'],
    tips: ['Giữ ảnh nhóm rõ vị trí từng người', 'Chọn bộ đồ không quá giống nhau', 'Kiểm tra bố cục tổng thể trước khi xuất'],
    faqs: [
      { question: 'Có gán trang phục theo người được không?', answer: 'Có, flow thử đồ nhóm hỗ trợ theo vị trí từng người.' },
      { question: 'Dùng cho gia đình được không?', answer: 'Có, rất phù hợp cho ảnh gia đình nhiều thành viên.' },
      { question: 'Có phù hợp cho đội nhóm bán hàng?', answer: 'Có, thuận tiện dựng visual đồng bộ nhanh.' },
      { question: 'Ảnh chụp điện thoại có dùng được không?', answer: 'Có, miễn ảnh đủ sáng và rõ.' },
      { question: 'Bao lâu có kết quả?', answer: 'Thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
  'thu-do-online-5-nguoi': {
    key: 'thu-do-online-5-nguoi',
    pageTitle: 'Thử đồ online 5 người bằng AI',
    pageDescription: 'Thử đồ nhóm 5 người bằng AI để phối outfit đồng bộ cho đại gia đình, nhóm bạn và đội ngũ sự kiện.',
    path: '/thu-do-online/5-nguoi',
    keywords: ['thử đồ 5 người', 'thử đồ nhóm lớn', 'group try on ai', 'phối đồ tập thể'],
    serviceName: 'Thử đồ online 5 người bằng AI',
    serviceDescription: 'Hỗ trợ thử outfit nhóm 5 người nhanh cho nhu cầu hình ảnh tập thể.',
    h2: 'Thử đồ nhóm 5 người để chốt visual tập thể nhanh',
    overview: 'Với nhóm 5 người, việc thử nhiều set đồ thường rất mất thời gian. Công cụ AI giúp bạn xem trước outfit tập thể để chốt phương án đồng bộ nhanh cho sự kiện, lookbook hoặc ảnh gia đình.',
    benefits: ['Phối đồ tập thể trực quan', 'Giảm thời gian chuẩn bị concept', 'Dễ dùng cho nhóm lớn'],
    useCases: ['Ảnh đại gia đình', 'Ảnh đội nhóm sự kiện', 'Lookbook nhóm cho thương hiệu'],
    tips: ['Ưu tiên ảnh nhóm đủ sáng và rõ', 'Tránh người che khuất nhau quá nhiều', 'Thử nhiều set để chọn phương án cân bằng'],
    faqs: [
      { question: 'Có hỗ trợ đúng 5 người không?', answer: 'Có, đây là flow tối ưu cho nhóm 5 người.' },
      { question: 'Phù hợp chụp sự kiện không?', answer: 'Có, giúp chuẩn bị visual tập thể trước khi chụp.' },
      { question: 'Có dùng cho lookbook nhóm được không?', answer: 'Có, đặc biệt khi cần chốt nhanh concept đồng bộ.' },
      { question: 'Có khó dùng không?', answer: 'Không, giao diện tối ưu cho thao tác nhanh.' },
      { question: 'Bao lâu có kết quả?', answer: 'Thông thường từ vài giây đến khoảng 1 phút.' },
    ],
  },
}

export function getFeatureSeo(key: string): FeatureSeoData {
  const data = FEATURE_SEO_DATA[key]
  if (!data) {
    throw new Error(`Missing feature SEO data for key: ${key}`)
  }
  return data
}

export function getAllFeatureSeo(): FeatureSeoData[] {
  return Object.values(FEATURE_SEO_DATA)
}

export function buildFeatureFaqJsonLd(seo: FeatureSeoData) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: seo.faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  }
}

