import { buildEnglishCoachFeatureLabelsForLogs, ENGLISH_COACH_API_STATS_FEATURE_LABELS } from './english-coach-feature-labels'
import { CURRICULUM_API_STATS_FEATURE_LABELS } from './curriculum-feature-labels'

/** Nhãn hiển thị cho `feature` (không gồm english-coach động từ log). */
export const STATIC_API_FEATURE_LABELS: Record<string, string> = {
  'thu-do-online': 'Thử đồ ảo',
  'thiet-ke-noi-ngoai-that': 'Thiết kế nội/ngoại thất',
  'xay-nha-tu-dat-nen': 'Nhà của bạn',
  'xay-nha-tu-dat-nen-synth': 'Xây nhà – tổng hợp prompt',
  'xay-nha-tu-dat-nen-structural': 'Xây nhà – bản vẽ kết cấu',
  'xay-nha-tu-dat-nen-floorplan': 'Xây nhà – bản vẽ chia phòng',
  'thiet-ke-noi-ngoai-that-analyze': 'Phân tích nội thất',
  'thiet-ke-noi-ngoai-that-process': 'Xử lý nội thất (dọn/staging)',
  'thiet-ke-logo': 'Thiết kế logo',
  'tao-anh-the': 'Tạo ảnh thẻ',
  'ghep-anh': 'Ghép ảnh',
  'lam-net-anh': 'Làm nét ảnh',
  'lam-dep-anh': 'Làm đẹp ảnh',
  'tao-banner': 'Tạo banner',
  'tao-nhan-gioi-thieu-san-pham': 'Tạo nhãn giới thiệu sản phẩm',
  'phuc-dung-anh': 'Phục dựng ảnh',
  'che-anh': 'Chế ảnh',
  'xoa-vat-the': 'Xóa vật thể',
  'thay-nen-san-pham': 'Thay nền sản phẩm',
  'tao-anh-chain-dung': 'Ảnh chân dung',
  'mo-rong-khung-hinh': 'Mở rộng khung hình',
  'hoan-doi-khuon-mat': 'Hoán đổi khuôn mặt',
  'tao-anh-3d': 'Ảnh 3D mockup',
  'tao-mo-hinh-3d-tu-anh': 'Mô hình 3D từ ảnh',
  'tao-video-tu-anh': 'Tạo video từ ảnh',
  'ai-normalize': 'Chuẩn hóa văn bản (AI)',
  'dich-anh-tai-lieu': 'Dịch ảnh tài liệu',
  'tao-anh-tu-chu': 'Tạo ảnh từ chữ',
  'du-anh-tu-phac-thao': 'Dựng ảnh từ phác thảo',
  'tao-infographic-tu-sach': 'Infographic từ sách',
  'xoa-nen-png': 'Xóa nền PNG',
  'ke-chuyen-bang-hinh-anh': 'Kể chuyện bằng hình ảnh',
  'thiet-ke-con-dau': 'Thiết kế con dấu',
  'tao-nhan-gian': 'Tạo nhãn gián',
  'tao-tem-niem-phong-bao-hanh': 'Tem niêm phong bảo hành',
  'tao-nhan-gioi-thieu-san-pham-mockup': 'Nhãn giới thiệu — mockup',
  'thiet-ke-bao-bi': 'Thiết kế bao bì',
  'thiet-ke-bao-bi-surface': 'Bao bì — bề mặt',
  'thiet-ke-bao-bi-bag-surface': 'Bao bì túi — bề mặt',
  'thiet-ke-bao-bi-mockup': 'Bao bì — mockup',
  'thiet-ke-bao-bi-bag-mockup': 'Bao bì túi — mockup',
  'xay-nha-synth': 'Xây nhà — tổng hợp',
  'xay-nha-3d': 'Xây nhà — 3D',
  'xay-nha-fp-synth': 'Xây nhà — mặt bằng (tổng hợp)',
  'xay-nha-floorplan': 'Xây nhà — mặt bằng',
  'xay-nha-structural': 'Xây nhà — kết cấu',
  'meeting-report-audio-transcribe-chunk': 'Biên bản họp — phiên âm từng đoạn audio',
  'meeting-report-audio-from-transcript': 'Biên bản họp — báo cáo từ transcript',
  'meeting-report-audio-unified': 'Biên bản họp — phiên âm + báo cáo (một lượt)',
  'exam-essay-ai-suggest': 'Thi — gợi ý điểm tự luận (giáo viên)',
  'music-lyria3-generate': 'Nhạc Lyria 3 (lượt gọi)',
  'dich-anh-tai-lieu-postcheck-verify': 'Dịch ảnh — hậu kiểm (kiểm tra chữ sót)',
  'dich-anh-tai-lieu-postcheck-translate': 'Dịch ảnh — hậu kiểm (dịch đoạn sót)',
  'quiz-verify-deepseek': 'Trắc nghiệm slide — kiểm tra đáp án (DeepSeek)',
  'quiz-verify-gemini-flash': 'Trắc nghiệm slide — kiểm tra đáp án (Gemini Flash)',
  'quiz-create-gemini-pro': 'Trắc nghiệm slide — tạo câu (Gemini Pro)',
  'quiz-create-gpt': 'Trắc nghiệm slide — tạo câu (GPT)',
  'quiz-check-wrong-gemini-pro': 'Trắc nghiệm slide — kiểm tra báo sai (Gemini Pro)',
  'quiz-check-wrong-gpt': 'Trắc nghiệm slide — kiểm tra báo sai (GPT)',
  'worksheet-quiz-generate-gemini-pro': 'Phiếu bài tập — sinh câu trắc nghiệm (Gemini Pro)',
  'worksheet-quiz-generate-openai-retry': 'Phiếu bài tập — sinh câu trắc nghiệm (OpenAI retry)',
  'worksheet-generate-essay-gemini-pro': 'Phiếu bài tập — sinh bài tự luận (Gemini Pro)',
  'worksheet-edit-check-gemini-flash': 'Phiếu bài tập — kiểm tra/sửa câu (Flash)',
  'slide-generate-quiz-gemini-pro': 'Slide giáo trình — sinh trắc nghiệm (Pro)',
  'slide-generate-quiz-gemini-pro-retry-parse': 'Slide giáo trình — sinh trắc nghiệm (Pro, retry JSON)',
  'slide-generate-quiz-verify-gemini-flash': 'Slide giáo trình — verify trắc nghiệm (Flash)',
  'slide-generate-quiz-fix-gemini-pro': 'Slide giáo trình — sửa trắc nghiệm sau verify (Pro)',
  'slide-verify-quiz-gemini-flash': 'Slide — kiểm tra trắc nghiệm chèn tay (Flash)',
  'worksheet-verify-oneshot-quiz-flash': 'Phiếu BT — verify trắc nghiệm (Flash, nền)',
  'worksheet-verify-oneshot-essay-flash': 'Phiếu BT — verify tự luận (Flash, nền)',
  'worksheet-verify-oneshot-quiz-vision-flash': 'Phiếu BT — verify trắc nghiệm + ảnh SGK (Flash)',
  'worksheet-verify-oneshot-essay-vision-flash': 'Phiếu BT — verify tự luận + ảnh SGK (Flash)',
  'worksheet-verify-essay-api-flash': 'Phiếu BT — API kiểm tra tự luận (Flash)',
  'worksheet-regenerate-quiz-gemini-flash': 'Phiếu BT — tạo lại TN (Flash)',
  'worksheet-regenerate-quiz-gemini-pro': 'Phiếu BT — tạo lại TN (Pro)',
  'worksheet-regenerate-essay-gemini-flash': 'Phiếu BT — tạo lại tự luận (Flash)',
  'worksheet-regenerate-essay-gemini-pro': 'Phiếu BT — tạo lại tự luận (Pro)',
  'worksheet-regenerate-fix-quiz-gemini-pro': 'Phiếu BT — sửa TN sau verify (Pro)',
  'worksheet-regenerate-fix-essay-gemini-pro': 'Phiếu BT — sửa tự luận sau verify (Pro)',
  'worksheet-parse-sgk-gemini-pro': 'Phiếu BT — tách câu từ ảnh SGK (Pro)',
  'worksheet-parse-sgk-essay-solution-pro': 'Phiếu BT — sinh lời giải khi parse SGK (Pro)',
  'worksheet-solve-sgk-essay-solution-pro': 'Phiếu BT — bù lời giải essay SGK (Pro)',
  'worksheet-step-quiz-gemini-pro': 'Phiếu BT — tạo từng bước: trắc nghiệm (Pro)',
  'worksheet-step-essay-gemini-pro': 'Phiếu BT — tạo từng bước: tự luận (Pro)',
  'dich-anh-tai-lieu-vision-ocr': 'Dịch ảnh tài liệu — Cloud Vision OCR (hậu kiểm)',
  'hoan-doi-khuon-mat-vision-face': 'Hoán đổi khuôn mặt — Cloud Vision (FACE_DETECTION)',
  'schools-search-canonicalize-gemini-flash': 'Tìm trường — chuẩn hóa tên bằng AI (Flash)',
  'thu-do-online-vision-remove-face-garment': 'Thử đồ ảo — Vision xóa mặt người mẫu (ảnh SP)',
  ...ENGLISH_COACH_API_STATS_FEATURE_LABELS,
  ...CURRICULUM_API_STATS_FEATURE_LABELS,
}

export function mergeApiFeatureLabelsForLogs(logFeatures: string[]): Record<string, string> {
  return {
    ...STATIC_API_FEATURE_LABELS,
    ...buildEnglishCoachFeatureLabelsForLogs(logFeatures),
  }
}
