export const AI_CATALOG_DATA = {
  specVersion: '1.0',
  host: {
    displayName: 'NanoAI',
    identifier: 'nanoai.vn',
    documentationUrl: 'https://nanoai.vn/llms.txt',
    logoUrl: 'https://nanoai.vn/icons/icon-192x192.png',
  },
  entries: [
    {
      identifier: 'urn:air:nanoai.vn:virtual-try-on',
      displayName: 'NanoAI Virtual Try-On',
      description: 'AI virtual fitting room supporting 1-5 people garment transfer and photo enhancement.',
      type: 'application/mcp-server-card+json',
      url: 'https://nanoai.vn/api/agent/mcp.json',
      representativeQueries: [
        'Thử quần áo lên người qua ảnh chụp online',
        'Phòng thử đồ online AI 1 đến 5 người',
        'Virtual try on clothing on model photo',
        'Ghép quần áo và phụ kiện thời trang',
      ],
      capabilities: [
        'VirtualTryOn',
        'GarmentTransfer',
        'PhotoRestoration',
        'ImageEnhancement',
      ],
      tags: [
        'fashion',
        'try-on',
        'ecommerce',
        'ai-vision',
      ],
    },
    {
      identifier: 'urn:air:nanoai.vn:partner-website',
      displayName: 'NanoAI Partner Website & Storefront Builder',
      description: 'Automated e-commerce storefront, landing page generator, and product catalog manager.',
      type: 'application/mcp-server-card+json',
      url: 'https://nanoai.vn/api/agent/mcp.json',
      representativeQueries: [
        'Tạo website bán hàng và landing page tự động',
        'Thiết kế web thời trang chuẩn SEO có giỏ hàng',
        'Build e-commerce store with product catalog',
        'Tạo landing page chuyển đổi cao bằng AI',
      ],
      capabilities: [
        'StorefrontGenerator',
        'LandingPageBuilder',
        'VisualEditor',
        'CatalogManagement',
      ],
      tags: [
        'website-builder',
        'storefront',
        'landing-page',
        'ecommerce',
      ],
    },
    {
      identifier: 'urn:air:nanoai.vn:packaging-design',
      displayName: 'NanoAI Packaging & Dieline Design',
      description: 'Automated 2D dieline and 3D mockup generator for carton boxes, bottles, and product labels.',
      type: 'application/mcp-server-card+json',
      url: 'https://nanoai.vn/api/agent/mcp.json',
      representativeQueries: [
        'Thiết kế bao bì hộp carton tự động theo kích thước',
        'Tạo dieline và nhãn chai lọ mỹ phẩm 3D',
        'Generate packaging dieline box SVG and 3D preview',
        'Thiết kế nhãn mác sản phẩm theo tiêu chuẩn',
      ],
      capabilities: [
        'PackagingDesign',
        'DielineGenerator',
        'Mockup3D',
        'LabelDesign',
      ],
      tags: [
        'packaging',
        'dieline',
        'box-design',
        'labels',
      ],
    },
    {
      identifier: 'urn:air:nanoai.vn:ai-studio-designer',
      displayName: 'NanoAI Studio Image & Banner Designer',
      description: 'E-commerce product photo studio, promotional banner creator, and brand logo designer.',
      type: 'application/mcp-server-card+json',
      url: 'https://nanoai.vn/api/agent/mcp.json',
      representativeQueries: [
        'Tạo banner quảng cáo thương mại điện tử 21:9',
        'Thiết kế logo thương hiệu và tách nền ảnh tự động',
        'Generate professional product photography studio backgrounds',
        'Thiết kế ấn phẩm marketing bằng AI',
      ],
      capabilities: [
        'ProductPhotography',
        'BannerDesign',
        'LogoDesign',
        'BackgroundRemoval',
      ],
      tags: [
        'studio',
        'banner',
        'logo',
        'graphic-design',
      ],
    },
    {
      identifier: 'urn:air:nanoai.vn:vietnamese-text-to-speech',
      displayName: 'NanoAI Vietnamese Text-to-Speech',
      description: 'Natural expressive Vietnamese voice synthesis across northern, central, and southern regional accents.',
      type: 'application/mcp-server-card+json',
      url: 'https://nanoai.vn/api/agent/mcp.json',
      representativeQueries: [
        'Chuyển văn bản thành giọng nói tiếng Việt tự nhiên',
        'Đọc văn bản giọng Bắc Trung Nam truyền cảm',
        'Vietnamese text to speech realistic voice generator',
        'Lồng tiếng video quảng cáo bằng AI',
      ],
      capabilities: [
        'TextToSpeech',
        'VoiceSynthesis',
        'AudioGeneration',
        'MultiAccentVietnamese',
      ],
      tags: [
        'tts',
        'voice',
        'audio',
        'vietnamese',
      ],
    },
    {
      identifier: 'urn:air:nanoai.vn:ai-language-coach',
      displayName: 'NanoAI Interactive Language Coach',
      description: 'Real-time multilingual English conversation coach with dynamic pronunciation feedback and personalized learning.',
      type: 'application/mcp-server-card+json',
      url: 'https://nanoai.vn/api/agent/mcp.json',
      representativeQueries: [
        'Luyện giao tiếp tiếng Anh thời gian thực với AI',
        'Học phát âm và chỉnh sửa câu tiếng Anh trực tiếp',
        'Interactive AI English conversation partner',
        'Luyện nói ngoại ngữ theo chủ đề hàng ngày',
      ],
      capabilities: [
        'LanguageCoaching',
        'ConversationalPractice',
        'PronunciationFeedback',
        'AdaptiveLearning',
      ],
      tags: [
        'education',
        'language-learning',
        'english-coach',
        'conversational-ai',
      ],
    },
  ],
}
