import assert from 'node:assert/strict'
import test from 'node:test'
import { buildPartnerSitePdpBootstrapScript } from '@/lib/partner-website/shop/build-partner-site-pdp-bootstrap-script'

test('PDP bootstrap hydrates reviews, Q&A, and options instead of clearing cards', () => {
  const s = buildPartnerSitePdpBootstrapScript({ siteSlug: '188-shop', locale: 'vi' })
  assert.match(s, /data-pw-pdp-bootstrap/)
  assert.match(s, /\/api\/site\/188-shop\/products\//)
  assert.match(s, /\/reviews/)
  assert.match(s, /\/questions/)
  assert.match(s, /\/options/)
  assert.match(s, /data-pw-pdp-option-value/)
  assert.match(s, /data-pw-review-submit/)
  assert.match(s, /data-pw-review-vote/)
  assert.match(s, /data-pw-qa-submit/)
  assert.match(s, /data-pw-qa-answer-submit/)
  assert.match(s, /LOGIN_PATH/)
  assert.match(s, /"reviewsFormSubmit":"Gửi"/)
  assert.match(s, /Gửi câu hỏi/)
  assert.match(s, /applyOptions/)
  assert.match(s, /pdpPurchasesLabel/)
  assert.match(s, /data-pw-pdp-video-thumb/)
  assert.match(s, /ACCOUNT_HDR='x-guest-account-id'/)
  assert.match(s, /pw-recently-viewed-updated/)
  assert.match(s, /function pwEnsureGuestSessionId/)
  assert.match(s, /pwShopTrack\('view_item'/)
  assert.match(s, /data-pw-region="pdp-info"/)
  assert.match(s, /data-nanoai-inventory/)
  assert.doesNotMatch(
    s,
    /querySelector\('\[data-pw-region="pdp-info"\],\[data-pw-region="gallery"\],\.pw-pdp,\[data-pw-page="product"\]'\)/
  )
  assert.match(s, /closest\('\[data-pw-el="variant"\],\[data-pw-pdp-option\]'\)/)
  assert.match(s, /if\(info\.querySelector\('\[data-pw-pdp-option="'\+kind\+'"\]'\)\)return/)
  assert.match(s, /function rehomePdpBuyBox/)
  assert.match(s, /function pdpBuyBox/)
  assert.doesNotMatch(s, /\[data-pw-region="reviews"\] \[data-pw-el="card"\]'\)\.forEach\(function\(card\)\{card\.innerHTML=''/)
  assert.match(s, /function stampTryOnButtons/)
  assert.match(s, /function coverImageOf/)
  assert.match(s, /data-nanoai-cover-image/)
  assert.match(s, /data-nanoai-image/)
  assert.match(s, /function paintPdpBirthday/)
  assert.match(s, /birthdaySave/)
  assert.match(s, /birthdayEndsAfter/)
  assert.doesNotMatch(s, /\?view=buy/)
  assert.match(s, /data-pw-like-count/)
  assert.match(s, /data-pw-stat="likes"/)
  assert.match(s, /hideBrokenPdpImgs/)
  assert.match(s, /data-pw-pdp-img-broken/)
  assert.match(s, /_\\d\+x\\d\+\(\?:q\\d\+\)\?/)
  assert.match(s, /function shopPdpPageSrc/)
  assert.match(s, /function galleryFaceVisible/)
  assert.match(s, /pw-shop-product-detail-body/)
  assert.match(s, /SUMMARY_PAGE_SIZE=1/)
  assert.match(s, /REVIEW_PAGE_SIZE=20/)
  assert.match(s, /data-pw-pdp-slot=['"]sale-timer['"]/)
  assert.match(s, /data-pw-pdp-slot=['"]price-kicker['"]/)
  assert.match(s, /countdownStarts/)
  assert.doesNotMatch(s, /pageSize=100/)
  assert.match(s, /data-pw-size-guide-open/)
  assert.match(s, /data-pw-pdp-slot['"],['"]size-guide/)
  assert.match(s, /sizeGuideButton/)
  assert.match(s, /function bindSizeGuideModal/)
  assert.match(s, /function hoistSizeGuideModal/)
  assert.match(s, /document\.body\.appendChild\(modal\)/)
  assert.match(s, /replySlot===slot/)
  assert.match(s, /user_one/)
  assert.match(s, /user_two/)
  assert.match(s, /qaReplyBuyerOnly/)
  assert.match(s, /pw-pdp-helpful-icon/)
  assert.match(s, /pw-pdp-helpful-btn/)
  assert.match(s, /pw-pdp-verified-label/)
  assert.match(s, /function toggleHelpfulVote/)
  assert.match(s, /function paintHelpfulBtn/)
  assert.match(s, /pw-pdp-rq-sample-box/)
  assert.match(s, /function rqToast/)
  assert.match(s, /function paintNeedBuy/)
  assert.match(s, /canReviewLive/)
  assert.match(s, /highlight=/)
  assert.match(s, /reviewsPurchaseRequired/)
  assert.match(s, /qaSeeList/)
  assert.match(s, /sample\?\[\]/)
  assert.doesNotMatch(s, /goLogin\('#pw-pdp-reviews'\)/)
  assert.doesNotMatch(s, /goLogin\('#pw-pdp-qa'\)/)
})

test('PDP bootstrap uses shop copy for the requested locale', () => {
  const en = buildPartnerSitePdpBootstrapScript({ siteSlug: '188-shop', locale: 'en' })
  assert.match(en, /"reviewsFormSubmit":"Send"/)
  assert.match(en, /Ask a question|Your question/)
})

test('PDP bootstrap paints helpful count outside the button and opens a write modal', () => {
  const s = buildPartnerSitePdpBootstrapScript({ siteSlug: '188-shop', locale: 'vi' })
  assert.match(s, /class="pw-pdp-helpful-n"/)
  assert.match(s, /pw-pdp-helpful-label/)
  assert.match(s, /function paintHelpfulUi/)
  assert.match(s, /helpfulVotes/)
  assert.match(s, /function readHelpfulCountFromDom/)
  assert.match(s, /data-pw-qa-open-reply/)
  assert.match(s, /data-pw-rq-modal="write"/)
  assert.match(s, /function paintWriteForm/)
  assert.match(s, /pw-pdp-rq-ctas-empty/)
  assert.match(s, /function paintProductStrips/)
  assert.match(s, /reviewsMineHeading/)
  assert.match(s, /reviewsCustomersHeading/)
  assert.match(s, /isCurrentUser/)
  assert.doesNotMatch(s, /\[data-pw-rq-modal="reviews"\] \[data-pw-pdp-slot="review-form"\]/)
  assert.doesNotMatch(
    s,
    /function toggleHelpfulVote\(btn,kind\)\{\s*if\(!btn\)return;\s*if\(!loggedIn\(\)\)/
  )
  assert.match(s, /window\.__pwPdpClickHandler=onPdpClick/)
  assert.match(s, /removeEventListener\('click',oldPdpClick,true\)/)
  assert.match(s, /addEventListener\('click',onPdpClick,true\)/)
  assert.match(s, /function showPdpImage\(img,page,full,alt\)/)
  assert.match(s, /removeAttribute\('data-pw-pdp-img-broken'\)/)
  assert.match(s, /removeAttribute\('data-pw-img-retry'\)/)
  assert.match(s, /showPdpImage\(main,colorPage\|\|colorSrc,colorFull/)
  assert.match(s, /showPdpImage\(main,page\|\|src,full/)
  assert.match(s, /function revealPdpGalleryMainImage/)
  assert.match(s, /function pdpGalleryIsMobileFace/)
  assert.match(s, /photoThumb\.classList\.add\('is-active'\);\s*revealPdpGalleryMainImage\(\)/)
  assert.match(s, /videoThumb\.classList\.add\('is-active'\);\s*revealPdpGalleryMainImage\(\)/)
  assert.match(s, /el\.setAttribute\('data-nanoai-image',colorFull\|\|colorSrc\);\s*\}\);\s*revealPdpGalleryMainImage\(\)/)
  assert.match(
    s,
    /querySelectorAll\('\[data-nanoai-try-on\],\[data-pw-chrome-btn="try-on"\]'\)\.forEach\(function\(el\)\{\s*el\.setAttribute\('data-nanoai-image',colorFull\|\|colorSrc\)/
  )
  assert.doesNotMatch(
    s,
    /\[data-nanoai-try-on\],\[data-pw-chrome-btn="try-on"\],\[data-nanoai-open-chat\],\[data-pw-chrome-btn="chat"\]/
  )
  assert.match(s, /if\(el\.parentElement!==document\.body\)document\.body\.appendChild\(el\)/)
  assert.doesNotMatch(s, /getAttribute\('data-pw-pdp-live'\)==='1'\)return/)
})
