import assert from 'node:assert/strict'
import test from 'node:test'
import { buildPartnerMarketingBannerBootstrapScript } from '@/lib/partner-website/shop/build-partner-marketing-banner-bootstrap-script'

test('bootstrap paints N slides on the first host and turns leftover widgets off', () => {
  const html = buildPartnerMarketingBannerBootstrapScript({ siteSlug: 'demo-shop', locale: 'vi' })
  assert.match(html, /\/api\/site\/demo-shop\/marketing-banners/)
  assert.match(html, /var WAIT=6500/)
  assert.match(html, /aspect-ratio:21\/9/)
  assert.match(html, /flex-shrink:0/)
  assert.match(html, /display:block!important/)
  assert.match(html, /\[data-pw-promo-carousel\]\{position:absolute;inset:0/)
  assert.doesNotMatch(html, /\[data-pw-personalize-banner\]\[data-pw-banner-live="1"\]\{min-height:0!important/)
  assert.doesNotMatch(
    html,
    /\[data-pw-personalize-banner\]\[data-pw-banner-live="1"\]:not\(\[data-pw-block-h\]\) \[data-pw-promo-carousel\]\{position:relative/
  )
  assert.match(html, /\[data-pw-promo-carousel\] img\{position:absolute!important/)
  assert.match(html, /object-fit:contain/)
  assert.match(html, /nextShopImageRetrySrc/)
  assert.match(html, /data-pw-banner-img-broken/)
  assert.match(html, /function firstHost/)
  assert.match(html, /data-pw-hidden/)
  assert.match(html, /var host=firstHost\(nodes\)/)
  assert.match(html, /data-pw-banner-live','off'/)
  assert.match(html, /data-pw-personalize-banner','promo'/)
  assert.match(html, /data-pw-marketing-banner-css/)
  assert.match(html, /data-pw-promo-carousel/)
  assert.match(html, /opacity:1/)
  assert.doesNotMatch(html, /transition:opacity/)
  assert.match(html, /items\.forEach\(function\(item,i\)/)
  assert.match(html, /data-pw-promo-slide/)
  assert.match(html, /data-pw-promo-prev/)
  assert.match(html, /data-pw-promo-next/)
  assert.match(html, /data-pw-promo-dots/)
  assert.match(html, /function wireCarousel/)
  assert.match(html, /function boot\(\)/)
  assert.match(html, /shopBannerImg/)
  assert.match(html, /__pwPromoTimer/)
  assert.match(html, /data-pw-src/)
  assert.match(html, /activateSlideImg/)
  assert.match(html, /box\.isConnected/)
  assert.match(html, /live==='1'\|\|live==='off'/)
  assert.match(html, /pwShopLiveUiOff/)
  assert.doesNotMatch(html, /#f97316|#ea580c|#fff7ed/)
  assert.doesNotMatch(html, /kind==='sale-calendar'\?'sale':kind/)
})
