import assert from 'node:assert/strict'
import test from 'node:test'
import { buildPartnerSitePdpBootstrapScript } from '@/lib/partner-website/shop/build-partner-site-pdp-bootstrap-script'

test('PDP bootstrap hydrates reviews, Q&A, and options instead of clearing cards', () => {
  const s = buildPartnerSitePdpBootstrapScript({ siteSlug: '188-shop', locale: 'vi' })
  assert.match(s, /data-pw-pdp-bootstrap/)
  assert.match(s, /\/api\/site\/188-shop\/products\//)
  assert.match(s, /\/reviews/)
  assert.match(s, /\/questions/)
  assert.match(s, /\/options/)
  assert.match(s, /data-pw-pdp-option-value/)
  assert.match(s, /data-pw-review-submit/)
  assert.match(s, /data-pw-review-vote/)
  assert.match(s, /data-pw-qa-submit/)
  assert.match(s, /data-pw-qa-answer-submit/)
  assert.match(s, /LOGIN_PATH/)
  assert.match(s, /Gửi đánh giá/)
  assert.match(s, /Gửi câu hỏi/)
  assert.match(s, /applyOptions/)
  assert.match(s, /pdpPurchasesLabel/)
  assert.match(s, /data-pw-pdp-video-thumb/)
  assert.match(s, /ACCOUNT_HDR='x-guest-account-id'/)
  assert.match(s, /pw-recently-viewed-updated/)
  assert.match(s, /function pwEnsureGuestSessionId/)
  assert.match(s, /data-pw-region="pdp-info"/)
  assert.match(s, /data-nanoai-inventory/)
  assert.doesNotMatch(
    s,
    /querySelector\('\[data-pw-region="pdp-info"\],\[data-pw-region="gallery"\],\.pw-pdp,\[data-pw-page="product"\]'\)/
  )
  assert.match(s, /closest\('\[data-pw-el="variant"\],\[data-pw-pdp-option\]'\)/)
  assert.match(s, /if\(info\.querySelector\('\[data-pw-pdp-option="'\+kind\+'"\]'\)\)return/)
  assert.match(s, /function rehomePdpBuyBox/)
  assert.match(s, /function pdpBuyBox/)
  assert.doesNotMatch(s, /\[data-pw-region="reviews"\] \[data-pw-el="card"\]'\)\.forEach\(function\(card\)\{card\.innerHTML=''/)
  assert.match(s, /function stampTryOnButtons/)
  assert.match(s, /data-nanoai-image/)
  assert.match(s, /function paintPdpBirthday/)
  assert.match(s, /birthdaySave/)
  assert.match(s, /birthdayEndsAfter/)
  assert.match(s, /\?view=buy/)
  assert.match(s, /data-pw-like-count/)
  assert.match(s, /data-pw-stat="likes"/)
  assert.match(s, /hideBrokenPdpImgs/)
  assert.match(s, /data-pw-pdp-img-broken/)
  assert.match(s, /_\\d\+x\\d\+\(\?:q\\d\+\)\?/)
  assert.match(s, /function shopPdpPageSrc/)
  assert.match(s, /function galleryFaceVisible/)
  assert.match(s, /pw-shop-product-detail-body/)
  assert.match(s, /SUMMARY_PAGE_SIZE=1/)
  assert.match(s, /REVIEW_PAGE_SIZE=20/)
  assert.match(s, /data-pw-pdp-slot=['"]sale-timer['"]/)
  assert.match(s, /data-pw-pdp-slot=['"]price-kicker['"]/)
  assert.match(s, /countdownStarts/)
  assert.doesNotMatch(s, /pageSize=100/)
  assert.match(s, /data-pw-size-guide-open/)
  assert.match(s, /data-pw-pdp-slot['"],['"]size-guide/)
  assert.match(s, /sizeGuideButton/)
  assert.match(s, /function bindSizeGuideModal/)
  assert.match(s, /function hoistSizeGuideModal/)
  assert.match(s, /document\.body\.appendChild\(modal\)/)
  assert.match(s, /replySlot===slot/)
  assert.match(s, /user_one/)
  assert.match(s, /user_two/)
  assert.match(s, /qaReplyBuyerOnly/)
  assert.match(s, /pw-pdp-helpful-icon/)
  assert.match(s, /pw-pdp-helpful-btn/)
  assert.match(s, /pw-pdp-verified-label/)
  assert.match(s, /function toggleHelpfulVote/)
  assert.match(s, /function paintHelpfulBtn/)
  assert.match(s, /pw-pdp-rq-sample-box/)
  assert.match(s, /function rqToast/)
  assert.match(s, /function paintNeedBuy/)
  assert.match(s, /canReviewLive/)
  assert.match(s, /highlight=/)
  assert.match(s, /reviewsPurchaseRequired/)
  assert.match(s, /qaSeeList/)
  assert.match(s, /sample\?\[\]/)
  assert.doesNotMatch(s, /goLogin\('#pw-pdp-reviews'\)/)
  assert.doesNotMatch(s, /goLogin\('#pw-pdp-qa'\)/)
})

test('PDP bootstrap uses shop copy for the requested locale', () => {
  const en = buildPartnerSitePdpBootstrapScript({ siteSlug: '188-shop', locale: 'en' })
  assert.match(en, /Submit review/)
  assert.match(en, /Ask a question|Your question/)
})
