import type { WebLocale } from '@/lib/i18n/config'

export type PartnerSiteShopCopy = {
  navHome: string
  navProducts: string
  navRecentlyViewed: string
  navFavorites: string
  navRecommended: string
  navCart: string
  navChat: string
  navChatZalo: string
  navChatFacebook: string
  navChatWhatsapp: string
  navTopUp: string
  navCategories: string
  catalogTitle: string
  categorySeoBodyAriaLabel: string
  categorySubcategoriesLabel: string
  categoryFilterMinPrice: string
  categoryFilterMaxPrice: string
  categoryFilterApply: string
  categoryFilterClear: string
  categorySortLabel: string
  categorySortNewest: string
  categorySortRandom: string
  categorySortOldest: string
  categorySortViews: string
  categorySortPriceAsc: string
  categorySortPriceDesc: string
  categoryFilterSize: string
  categoryFilterColor: string
  categoryFilterAllSizes: string
  categoryFilterAllColors: string
  categoryMegaHint: string
  khoSaleNavLabel: string
  khoSaleNavBlurb: string
  khoSaleViewAll: string
  khoSalePageTitle: string
  categorySeoRowAria: string
  categoryExpand: string
  categoryCollapse: string
  categoryHubTitle: string
  categoryHubEmpty: string
  categoryPagePrev: string
  categoryPageNext: string
  categoryFiltersAria: string
  catalogEmpty: string
  loadMore: string
  productDetail: string
  addToCart: string
  buyNow: string
  addedToCart: string
  cartAddedTitle: string
  cartGoToCart: string
  cartContinueShopping: string
  cartAddedClose: string
  /** W1.6 — cảnh báo sắp hết hàng, chỉ hiện khi 1 <= tồn kho <= ngưỡng (không chặn mua). Chứa token `{n}` — thay bằng số lượng. */
  lowStockUrgency: string
  galleryZoomHint: string
  lightboxClose: string
  lightboxPrev: string
  lightboxNext: string
  consultChat: string
  cartTitle: string
  cartEmpty: string
  cartSubtotal: string
  cartCheckout: string
  cartCheckingOut: string
  cartRemove: string
  cartPromoLabel: string
  cartPromoPlaceholder: string
  cartPromoApply: string
  cartPromoApplying: string
  cartPromoRemove: string
  cartPromoDiscountLabel: string
  cartTotalLabel: string
  /** W1.7 */
  cartShippingFeeLabel: string
  cartShippingFeeFree: string
  cartShippingFeeIncluded: string
  /** Chứa token `{amount}`. */
  cartShippingFreeThresholdHint: string
  checkoutPaymentMethodLabel: string
  checkoutPaymentMethodBank: string
  checkoutPaymentMethodEwallet: string
  checkoutPaymentMethodHint: string
  orderConfirmEwalletTitle: string
  orderConfirmEwalletHint: string
  promoErrorNotFound: string
  promoErrorInactive: string
  promoErrorNotStarted: string
  promoErrorExpired: string
  promoErrorBelowMinSubtotal: string
  promoErrorUsageLimitReached: string
  promoErrorPerUserLimitReached: string
  promoErrorFirstOrderOnly: string
  promoErrorNoEligibleItems: string
  promoErrorGrantRequired: string
  promoErrorGeneric: string
  checkoutName: string
  checkoutPhone: string
  checkoutAddress: string
  checkoutNote: string
  checkoutSuccess: string
  checkoutAuthRequired: string
  checkoutGuestHint: string
  checkoutAuthLink: string
  quantity: string
  backToShop: string
  navOrders: string
  sizeLabel: string
  colorLabel: string
  /** W1.5 — size guide on PDP */
  sizeGuideButton: string
  sizeGuideModalTitle: string
  sizeGuideFallbackLink: string
  sizeGuideClose: string
  /** S0.7 — public contact channel FABs */
  contactChannelsAria: string
  contactChannelPhone: string
  contactChannelZalo: string
  contactChannelMessenger: string
  contactChannelInstagram: string
  /** W1.4 flash sale */
  flashSaleBadge: string
  flashSaleEndsIn: string
  /** M1.4 */
  shippingCarrierLabel: string
  searchPlaceholder: string
  searchButton: string
  searchByImage: string
  searchSearching: string
  searchResults: string
  searchEmpty: string
  searchError: string
  relatedProducts: string
  relatedSeeAll: string
  relatedEmpty: string
  outfitTitleFallback: string
  outfitSubtitle: string
  outfitSlotsAria: string
  outfitEmpty: string
  outfitError: string
  outfitSeeAll: string
  tryOnLink: string
  favoriteProduct: string
  /** PDP — bố cục kiểu 188 (gallery bleed / giá / sticky), copy đa ngôn ngữ */
  skuLabel: string
  pdpRatingLabel: string
  pdpLineTotal: string
  pdpSavings: string
  pdpQtyBuy: string
  pdpShippingNote: string
  pdpShippingFreeFrom: string
  pdpShippingPolicyLink: string
  pdpReturnsPolicyLink: string
  pdpServiceLabel: string
  pdpServiceNote: string
  pdpNotesTitle: string
  pdpNoteFit: string
  pdpNoteColor: string
  pdpStickyHome: string
  /** Thanh đáy PDP mobile — 2 dòng như 188 (Trang / chủ) */
  pdpStickyHomeL1: string
  pdpStickyHomeL2: string
  pdpStickyTryOnL1: string
  pdpStickyTryOnL2: string
  pdpStickyLikeLabel: string
  pdpAddToCartShort: string
  pdpBuyNowShort: string
  pdpShareCopy: string
  pdpShareCopied: string
  pdpJumpReviews: string
  pdpJumpQa: string
  pdpBrandLabel: string
  pdpOriginLabel: string
  pdpMaterialLabel: string
  pdpStyleLabel: string
  pdpOccasionLabel: string
  pdpWeightLabel: string
  pdpFeaturesLabel: string
  pdpCategoryLabel: string
  pdpPurchasesLabel: string
  pdpLikesLabel: string
  pdpRatingCountSuffix: string
  pdpDescTab: string
  pdpSpecsTab: string
  pdpDetailImagesHeading: string
  pdpSpecsEmpty: string
  pdpYes: string
  pdpNo: string
  ordersTitle: string
  ordersEmpty: string
  /** W3.2 — trang cảm ơn sau checkout */
  thankYouOrderLabel: string
  thankYouTrackCta: string
  /** W5.3 — shortcut trạng thái đơn */
  ordersFilterAriaLabel: string
  ordersFilterAll: string
  ordersFilterWaitingPayment: string
  ordersFilterProcessing: string
  ordersFilterDelivered: string
  ordersFilterReviewed: string
  ordersFilterCancelled: string
  ordersFilterReturned: string
  ordersFilterEmpty: string
  orderTrack: string
  orderHideTrack: string
  orderConfirmReceived: string
  orderConfirmReceivedHint: string
  orderConfirmReceivedOk: string
  orderCancel: string
  orderCancelHint: string
  orderCancelOk: string
  orderCancelReason: string
  orderReview: string
  orderDetail: string
  orderHideDetail: string
  orderTimelineTitle: string
  orderTimelineCreated: string
  orderTimelineConfirmed: string
  orderTimelinePacking: string
  orderTimelineShipping: string
  orderTimelineDelivered: string
  orderActionFailed: string
  orderAddressLabel: string
  authSendOtp: string
  authVerifyOtp: string
  authSuccess: string
  authFailed: string
  authOtpSent: string
  authEmailLogin: string
  authChangeEmail: string
  authEmailRequired: string
  authGoogleLogin: string
  authShopOtpOr: string
  authLoginSubtitle: string
  authLoginTitle: string
  authLoginWelcome: string
  authQuickLoginFailed: string
  authNanoAiLoginHint: string
  authRememberDevice: string
  orderIdLabel: string
  depositAmount: string
  paymentReference: string
  depositPolicyNote: string
  productDescriptionTitle: string
  productDetailImagesTitle: string
  productVideoTitle: string
  pdpConsultNoteTitle: string
  pdpMaterialImagesTitle: string
  pdpRealUseImagesTitle: string
  favoriteAdd: string
  favoriteRemove: string
  wishlistTitle: string
  wishlistEmpty: string
  recentlyViewedTitle: string
  recentlyViewedEmpty: string
  chatOpenLabel: string
  chatCloseLabel: string
  chatFullPageLabel: string
  chatLanguageLabel: string
  consentMessage: string
  consentAccept: string
  consentReject: string
  navAccount: string
  navLogout: string
  navRegister: string
  leadFormTitle: string
  navWallet: string
  walletTitle: string
  walletHint: string
  walletEmpty: string
  walletCopyCode: string
  walletCodeCopied: string
  walletExpiresLabel: string
  walletMinSubtotalNote: string
  accountEditProfile: string
  accountViewedProducts: string
  accountAddressBook: string
  accountEmailLabel: string
  accountSave: string
  accountSaved: string
  accountSaveFailed: string
  addressesHint: string
  accountWelcome: string
  accountQuickLinks: string
  accountOpenShopAdmin: string
  accountOpenShopAdminHint: string
  accountSectionEditProfile: string
  /** W5.1 */
  accountSecurity: string
  accountSecurityTitle: string
  accountSecurityLoginNote: string
  accountSignOutDevice: string
  accountSignOutDone: string
  accountSecurityReAuth: string
  /** W5.2 */
  accountNotifications: string
  accountNotificationsTitle: string
  accountNotificationsEmpty: string
  accountNotificationsMarkAllRead: string
  accountNotificationsLogin: string
  accountNotificationsLoading: string
  accountNotificationsSignIn: string
  pushEnableTitle: string
  pushEnableHint: string
  pushEnableButton: string
  pushEnabled: string
  pushDenied: string
  pushUnsupported: string
  pushIosHint: string
  pushSyncing: string
  /** W5.5 */
  accountInstallApp: string
  accountInstallAppTitle: string
  accountInstallAppHint: string
  accountInstallAppButton: string
  accountInstallAppIosTip: string
  accountInstallAppInstalled: string
  accountInstallAppManualTip: string
  orderStatusLabel: string
  orderStatusAwaitingPayment: string
  orderStatusPaymentChecking: string
  orderStatusPaidVerified: string
  orderStatusPendingManualReview: string
  orderStatusCancelled: string
  orderShippingStatusLabel: string
  orderShippingPending: string
  orderShippingConfirmed: string
  orderShippingPacking: string
  orderShippingShipping: string
  orderShippingDelivered: string
  orderShippingReturned: string
  orderShippingCancelled: string
  orderDateLabel: string
  orderViewPayment: string
  orderHidePayment: string
  orderQuantityLabel: string
  recentlyViewedClear: string
  recentlyViewedCleared: string
  addressesEmptyHint: string
  addressAdd: string
  addressEdit: string
  addressDelete: string
  addressDeleteConfirm: string
  addressDeleteConfirmBody: string
  addressCancel: string
  addressSave: string
  addressSetDefault: string
  addressDefaultBadge: string
  addressFullName: string
  addressPhone: string
  addressProvince: string
  addressProvincePlaceholder: string
  addressDistrict: string
  addressWard: string
  addressStreet: string
  addressStreetPlaceholder: string
  addressMakeDefault: string
  addressManageBook: string
  addressCartTitle: string
  addressCartEmpty: string
  addressCartAddHint: string
  addressFormTitleAdd: string
  addressFormTitleEdit: string
  addressDeleted: string
  addressSaveBook: string
  addressCartModalTitle: string
  reviewsTitle: string
  reviewsTotalSuffix: string
  reviewsWriteButton: string
  reviewsFormRatingLabel: string
  reviewsFormContentPlaceholder: string
  reviewsFormImagesLabel: string
  reviewsFormSubmit: string
  reviewsFormCancel: string
  reviewsSubmitSuccess: string
  reviewsSubmitLoginRequired: string
  reviewsSubmitAlreadyReviewed: string
  reviewsSubmitNotEligible: string
  reviewsEmpty: string
  reviewsLoadMore: string
  reviewsUsefulLabel: string
  reviewsMerchantReplyPrefix: string
  qaTitle: string
  qaAskButton: string
  qaFormPlaceholder: string
  qaFormSubmit: string
  qaSubmitSuccess: string
  qaSubmitLoginRequired: string
  qaEmpty: string
  qaLoadMore: string
  qaAnswerButton: string
  qaAnswerFormPlaceholder: string
  qaAnswerSubmit: string
  qaAnswerNotEligible: string
  qaAnswerSlotFull: string
  qaVerifiedBadge: string
  qaAdminBadge: string
  qaNoAnswersYet: string
  footerColShop: string
  footerColShopping: string
  footerColSupport: string
  footerColLegal: string
  footerBrandHint: string
  /** Tokens `{year}` `{shop}` */
  footerCopyright: string
  footerPaymentHint: string
  lpExploreProducts: string
  lpViewProducts: string
  lpSuggestedForYou: string
  /** 188 homepage block title — recommended product grid */
  homeYouMayLike: string
  forYouBadge: string
  lpHighlightsHeading: string
  lpFaqHeading: string
  lpRealReviews: string
  lpViewFullCategory: string
  lpMaterialChip: string
  lpTrust1: string
  lpTrust2: string
  lpTrust3: string
}

const COPY: Record<WebLocale, PartnerSiteShopCopy> = {
  vi: {
    navHome: 'Trang chủ',
    navProducts: 'Sản phẩm',
    navRecentlyViewed: 'Vừa xem',
    navFavorites: 'Yêu thích',
    navRecommended: 'Gợi ý',
    navCart: 'Giỏ hàng',
    navChat: 'Chat mua',
    navChatZalo: 'Chat Zalo',
    navChatFacebook: 'Chat Facebook',
    navChatWhatsapp: 'Chat WhatsApp',
    navTopUp: 'Lên đầu trang',
    navCategories: 'Danh mục',
    catalogTitle: 'Tất cả sản phẩm',
    categorySeoBodyAriaLabel: 'Giới thiệu danh mục',
    categorySubcategoriesLabel: 'Danh mục con',
    categoryFilterMinPrice: 'Giá từ',
    categoryFilterMaxPrice: 'Giá đến',
    categoryFilterApply: 'Áp dụng',
    categoryFilterClear: 'Xóa bộ lọc',
    categorySortLabel: 'Sắp xếp',
    categorySortNewest: 'Mới nhất',
    categorySortRandom: 'Ngẫu nhiên',
    categorySortOldest: 'Cũ nhất',
    categorySortViews: 'Xem nhiều',
    categorySortPriceAsc: 'Giá tăng dần',
    categorySortPriceDesc: 'Giá giảm dần',
    categoryFilterSize: 'Size',
    categoryFilterColor: 'Màu',
    categoryFilterAllSizes: 'Tất cả size',
    categoryFilterAllColors: 'Tất cả màu',
    categoryMegaHint: 'Di chuột vào danh mục để xem cấp 2, cấp 3.',
    khoSaleNavLabel: 'Sale kho',
    khoSaleNavBlurb: 'Hàng hoàn và tồn thanh lý — giá ưu đãi, số lượng có hạn.',
    khoSaleViewAll: 'Xem tất cả →',
    khoSalePageTitle: 'Sale kho',
    categorySeoRowAria: 'Từ khóa size SEO',
    categoryExpand: 'Mở danh mục con',
    categoryCollapse: 'Thu gọn danh mục con',
    categoryHubTitle: 'Danh mục sản phẩm',
    categoryHubEmpty: 'Chưa có danh mục để hiển thị.',
    categoryPagePrev: 'Trước',
    categoryPageNext: 'Sau',
    categoryFiltersAria: 'Bộ lọc sản phẩm',
    catalogEmpty: 'Chưa có sản phẩm.',
    loadMore: 'Xem thêm',
    productDetail: 'Chi tiết sản phẩm',
    addToCart: 'Thêm vào giỏ',
    buyNow: 'Mua ngay',
    addedToCart: 'Đã thêm vào giỏ.',
    cartAddedTitle: 'Đã thêm vào giỏ hàng',
    cartGoToCart: 'Vào giỏ hàng',
    cartContinueShopping: 'Mua sắm tiếp',
    cartAddedClose: 'Đóng',
    lowStockUrgency: 'Chỉ còn {n} sản phẩm — nhanh tay đặt hàng!',
    galleryZoomHint: 'Chạm để phóng to, vuốt để xem ảnh khác',
    lightboxClose: 'Đóng',
    lightboxPrev: 'Ảnh trước',
    lightboxNext: 'Ảnh tiếp theo',
    consultChat: 'Chat tư vấn',
    cartTitle: 'Giỏ hàng',
    cartEmpty: 'Giỏ hàng trống.',
    cartSubtotal: 'Tạm tính',
    cartCheckout: 'Thanh toán',
    cartCheckingOut: 'Đang tạo đơn…',
    cartRemove: 'Xóa',
    cartPromoLabel: 'Mã giảm giá',
    cartPromoPlaceholder: 'Nhập mã giảm giá',
    cartPromoApply: 'Áp dụng',
    cartPromoApplying: 'Đang kiểm tra...',
    cartPromoRemove: 'Bỏ mã',
    cartPromoDiscountLabel: 'Giảm giá',
    cartTotalLabel: 'Tổng cộng',
    cartShippingFeeLabel: 'Phí vận chuyển',
    cartShippingFeeFree: 'Miễn phí vận chuyển',
    cartShippingFeeIncluded: 'Đã bao gồm phí vận chuyển',
    cartShippingFreeThresholdHint: 'mua thêm để đạt {amount} sẽ được miễn phí ship',
    checkoutPaymentMethodLabel: 'Phương thức thanh toán',
    checkoutPaymentMethodBank: 'Chuyển khoản ngân hàng',
    checkoutPaymentMethodEwallet: 'Ví điện tử',
    checkoutPaymentMethodHint: 'Áp dụng cho phần cần thanh toán trước (nếu có); phần còn lại thanh toán khi nhận hàng.',
    orderConfirmEwalletTitle: 'Thanh toán qua ví điện tử',
    orderConfirmEwalletHint: 'Quét mã QR bằng ứng dụng ví điện tử, nhập đúng số tiền cần thanh toán rồi gửi ảnh biên lai bên dưới.',
    promoErrorNotFound: 'Mã giảm giá không tồn tại.',
    promoErrorInactive: 'Mã giảm giá không còn hiệu lực.',
    promoErrorNotStarted: 'Mã giảm giá chưa tới ngày áp dụng.',
    promoErrorExpired: 'Mã giảm giá đã hết hạn.',
    promoErrorBelowMinSubtotal: 'Đơn hàng chưa đạt giá trị tối thiểu để áp mã.',
    promoErrorUsageLimitReached: 'Mã giảm giá đã hết lượt sử dụng.',
    promoErrorPerUserLimitReached: 'Bạn đã dùng mã này đủ số lần cho phép.',
    promoErrorFirstOrderOnly: 'Mã chỉ áp dụng cho đơn hàng đầu tiên.',
    promoErrorNoEligibleItems: 'Giỏ hàng chưa có sản phẩm phù hợp với mã này.',
    promoErrorGrantRequired: 'Mã này chỉ dùng được khi đã được tặng vào ví.',
    promoErrorGeneric: 'Không áp dụng được mã giảm giá.',
    checkoutName: 'Họ tên',
    checkoutPhone: 'Số điện thoại',
    checkoutAddress: 'Địa chỉ giao hàng',
    checkoutNote: 'Ghi chú',
    checkoutSuccess: 'Đã tạo đơn — shop sẽ liên hệ sớm.',
    checkoutAuthRequired: 'Vui lòng đăng nhập để tiếp tục.',
    checkoutGuestHint: 'Bạn có thể đặt hàng mà không cần đăng nhập — chỉ cần điền thông tin giao hàng.',
    checkoutAuthLink: 'Đăng nhập / xác minh tại chat shop',
    quantity: 'Số lượng',
    backToShop: 'Tiếp tục mua',
    navOrders: 'Đơn hàng',
    sizeLabel: 'Size',
    colorLabel: 'Màu',
    sizeGuideButton: 'Hướng dẫn chọn size',
    sizeGuideModalTitle: 'Bảng size',
    sizeGuideFallbackLink: 'Xem hướng dẫn size',
    sizeGuideClose: 'Đóng',
    contactChannelsAria: 'Liên hệ nhanh',
    contactChannelPhone: 'Gọi điện',
    contactChannelZalo: 'Zalo',
    contactChannelMessenger: 'Messenger',
    contactChannelInstagram: 'Instagram',
    flashSaleBadge: 'Flash sale',
    flashSaleEndsIn: 'Kết thúc sau',
    shippingCarrierLabel: 'Đơn vị vận chuyển',
    searchPlaceholder: 'Tìm sản phẩm…',
    searchButton: 'Tìm',
    searchByImage: 'Tìm bằng ảnh',
    searchSearching: 'Đang tìm…',
    searchResults: 'Kết quả tìm kiếm',
    searchEmpty: 'Không tìm thấy sản phẩm phù hợp.',
    searchError: 'Không tìm được. Thử lại.',
    relatedProducts: 'Sản phẩm tương tự',
    relatedSeeAll: 'Xem tất cả',
    relatedEmpty: 'Không có sản phẩm khác cùng danh mục.',
    outfitTitleFallback: 'Phối với món này',
    outfitSubtitle: 'Món khác loại để mặc cùng',
    outfitSlotsAria: 'Nhóm phối',
    outfitEmpty: 'Chưa có gợi ý phối cho sản phẩm này.',
    outfitError: 'Không tải được gợi ý phối.',
    outfitSeeAll: 'Xem tất cả',
    tryOnLink: 'Thử đồ AI',
    favoriteProduct: 'Thích sản phẩm',
    skuLabel: 'Mã SP',
    pdpRatingLabel: 'Đánh giá',
    pdpLineTotal: 'Tổng số',
    pdpSavings: 'Tiết kiệm {amount}',
    pdpQtyBuy: 'Số lượng mua',
    pdpShippingNote: 'Giao hàng toàn quốc. {free}Đổi trả trong 7 ngày nếu sản phẩm lỗi hoặc không đúng mô tả.',
    pdpShippingFreeFrom: 'Miễn phí đơn từ {amount}. ',
    pdpShippingPolicyLink: 'Chính sách giao hàng',
    pdpReturnsPolicyLink: 'Chính sách đổi trả',
    pdpServiceLabel: 'Dịch vụ',
    pdpServiceNote: 'Thanh toán khi nhận hàng, đổi size nếu không vừa, xem hàng trước khi nhận.',
    pdpNotesTitle: 'Lưu ý',
    pdpNoteFit: 'Kích thước thực tế có thể chênh lệch nhẹ so với mô tả.',
    pdpNoteColor: 'Màu sắc trên ảnh có thể hơi khác thực tế do ánh sáng và thiết bị.',
    pdpStickyHome: 'Trang chủ',
    pdpStickyHomeL1: 'Trang',
    pdpStickyHomeL2: 'chủ',
    pdpStickyTryOnL1: 'Thử',
    pdpStickyTryOnL2: 'đồ',
    pdpStickyLikeLabel: 'Thích',
    pdpAddToCartShort: 'Thêm giỏ',
    pdpBuyNowShort: 'Mua hàng',
    pdpShareCopy: 'Sao chép link',
    pdpShareCopied: 'Đã sao chép',
    pdpJumpReviews: 'Xem đánh giá',
    pdpJumpQa: 'Hỏi đáp',
    pdpBrandLabel: 'Thương hiệu',
    pdpOriginLabel: 'Xuất xứ',
    pdpMaterialLabel: 'Chất liệu',
    pdpStyleLabel: 'Phong cách',
    pdpOccasionLabel: 'Dịp',
    pdpWeightLabel: 'Trọng lượng',
    pdpFeaturesLabel: 'Tính năng',
    pdpCategoryLabel: 'Danh mục',
    pdpPurchasesLabel: 'Đã bán',
    pdpLikesLabel: 'Lượt thích',
    pdpRatingCountSuffix: 'lượt',
    pdpDescTab: 'Mô Tả Sản Phẩm',
    pdpSpecsTab: 'Thông tin sản phẩm',
    pdpDetailImagesHeading: 'Hình ảnh chi tiết sản phẩm',
    pdpSpecsEmpty: 'Chưa có dữ liệu thông tin sản phẩm.',
    pdpYes: 'Có',
    pdpNo: 'Không',
    ordersTitle: 'Đơn hàng của bạn',
    ordersEmpty: 'Chưa có đơn hàng.',
    thankYouOrderLabel: 'Mã đơn',
    thankYouTrackCta: 'Theo dõi đơn',
    ordersFilterAriaLabel: 'Lọc theo trạng thái đơn',
    ordersFilterAll: 'Tất cả',
    ordersFilterWaitingPayment: 'Chờ thanh toán',
    ordersFilterProcessing: 'Chờ nhận',
    ordersFilterDelivered: 'Đã nhận',
    ordersFilterReviewed: 'Đã đánh giá',
    ordersFilterCancelled: 'Đã huỷ',
    ordersFilterReturned: 'Đơn hoàn',
    ordersFilterEmpty: 'Không có đơn nào ở trạng thái này.',
    orderTrack: 'Theo dõi đơn',
    orderHideTrack: 'Ẩn lịch trình',
    orderConfirmReceived: 'Đã nhận hàng',
    orderConfirmReceivedHint: 'Xác nhận bạn đã nhận đủ hàng. Sau đó bạn có thể đánh giá sản phẩm.',
    orderConfirmReceivedOk: 'Đã xác nhận nhận hàng.',
    orderCancel: 'Huỷ đơn',
    orderCancelHint: 'Chỉ huỷ được khi đơn chưa thanh toán / chưa giao.',
    orderCancelOk: 'Đã huỷ đơn hàng.',
    orderCancelReason: 'Lý do huỷ (không bắt buộc)',
    orderReview: 'Đánh giá',
    orderDetail: 'Chi tiết đơn',
    orderHideDetail: 'Ẩn chi tiết',
    orderTimelineTitle: 'Lịch trình đơn hàng',
    orderTimelineCreated: 'Đã đặt hàng',
    orderTimelineConfirmed: 'Shop đã xác nhận',
    orderTimelinePacking: 'Đang đóng gói',
    orderTimelineShipping: 'Đang giao hàng',
    orderTimelineDelivered: 'Đã nhận hàng',
    orderActionFailed: 'Không thực hiện được. Thử lại.',
    orderAddressLabel: 'Địa chỉ giao',
    authSendOtp: 'Gửi mã OTP',
    authVerifyOtp: 'Xác minh',
    authSuccess: 'Đã xác minh email — có thể thanh toán.',
    authFailed: 'Không xác minh được. Thử lại.',
    authOtpSent: 'Đã gửi mã OTP tới email.',
    authEmailLogin: 'Đăng nhập bằng email',
    authChangeEmail: 'Đổi email khác',
    authEmailRequired: 'Vui lòng nhập email.',
    authGoogleLogin: 'Đăng nhập bằng Google',
    authShopOtpOr: 'Hoặc nhập email để nhận mã',
    authLoginSubtitle: 'Google hoặc mã OTP qua email',
    authLoginTitle: 'Đăng nhập',
    authLoginWelcome: 'Chào mừng trở lại',
    authQuickLoginFailed: 'Chưa đăng nhập được — dùng email OTP bên dưới.',
    authNanoAiLoginHint: 'Nhập email — bạn sẽ nhận mã OTP qua email.',
    authRememberDevice: 'Giữ đăng nhập trên thiết bị này (lần sau có thể không cần OTP).',
    orderIdLabel: 'Mã đơn',
    depositAmount: 'Số tiền cọc',
    paymentReference: 'Nội dung chuyển khoản',
    depositPolicyNote: 'Cọc theo cài đặt shop — quét QR hoặc chuyển khoản đúng nội dung.',
    productDescriptionTitle: 'Mô tả sản phẩm',
    productDetailImagesTitle: 'Ảnh chi tiết',
    productVideoTitle: 'Video sản phẩm',
    pdpConsultNoteTitle: 'Gợi ý tư vấn',
    pdpMaterialImagesTitle: 'Ảnh chất liệu',
    pdpRealUseImagesTitle: 'Ảnh thực tế',
    favoriteAdd: 'Thêm yêu thích',
    favoriteRemove: 'Bỏ yêu thích',
    wishlistTitle: 'Yêu thích',
    wishlistEmpty: 'Chưa có sản phẩm yêu thích.',
    recentlyViewedTitle: 'Vừa xem',
    recentlyViewedEmpty: 'Chưa xem sản phẩm nào.',
    chatOpenLabel: 'Mở chat',
    chatCloseLabel: 'Đóng',
    chatFullPageLabel: 'Mở toàn trang',
    chatLanguageLabel: 'Ngôn ngữ',
    consentMessage: 'Trang web này dùng cookie để cải thiện trải nghiệm mua sắm và đo lường hiệu quả quảng cáo.',
    consentAccept: 'Đồng ý',
    consentReject: 'Từ chối',
    navAccount: 'Tài khoản',
    navLogout: 'Đăng xuất',
    navRegister: 'Đăng ký',
    leadFormTitle: 'Đăng ký nhận tin',
    navWallet: 'Ví quà',
    walletTitle: 'Ví quà của bạn',
    walletHint: 'Sao chép mã và dán vào ô mã giảm giá ở giỏ hàng để áp dụng.',
    walletEmpty: 'Bạn chưa có voucher nào trong ví.',
    walletCopyCode: 'Sao chép mã',
    walletCodeCopied: 'Đã sao chép mã!',
    walletExpiresLabel: 'Hết hạn',
    walletMinSubtotalNote: 'Áp dụng cho đơn từ',
    accountEditProfile: 'Chỉnh sửa hồ sơ',
    accountViewedProducts: 'Sản phẩm đã xem',
    accountAddressBook: 'Sổ địa chỉ',
    accountEmailLabel: 'Email',
    accountSave: 'Lưu thay đổi',
    accountSaved: 'Đã lưu hồ sơ.',
    accountSaveFailed: 'Không lưu được. Thử lại.',
    addressesHint: 'Quản lý nhiều địa chỉ giao hàng. Địa chỉ mặc định dùng khi thanh toán.',
    accountWelcome: 'Xin chào',
    accountQuickLinks: 'Truy cập nhanh',
    accountOpenShopAdmin: 'Vào trang quản trị shop',
    accountOpenShopAdminHint: 'Gmail này được mời làm quản trị — mở nhanh trang quản trị shop.',
    accountSectionEditProfile: 'Chỉnh sửa hồ sơ',
    accountSecurity: 'Bảo mật',
    accountSecurityTitle: 'Bảo mật tài khoản',
    accountSecurityLoginNote: 'Đăng nhập bằng OTP qua email hoặc Google — không dùng mật khẩu.',
    accountSignOutDevice: 'Đăng xuất thiết bị này',
    accountSignOutDone: 'Đã đăng xuất trên thiết bị này.',
    accountSecurityReAuth: 'Đăng nhập lại',
    accountNotifications: 'Thông báo',
    accountNotificationsTitle: 'Trung tâm thông báo',
    accountNotificationsEmpty: 'Bạn chưa có thông báo nào.',
    accountNotificationsMarkAllRead: 'Đánh dấu tất cả đã đọc',
    accountNotificationsLogin: 'Vui lòng đăng nhập để xem thông báo.',
    accountNotificationsLoading: 'Đang tải thông báo...',
    accountNotificationsSignIn: 'Đăng nhập ngay',
    pushEnableTitle: 'Thông báo trên trình duyệt',
    pushEnableHint: 'Nhận thông báo đơn hàng và tin từ shop ngay cả khi bạn không mở trang.',
    pushEnableButton: 'Bật thông báo đẩy',
    pushEnabled: 'Đã bật thông báo đẩy trên thiết bị này.',
    pushDenied: 'Trình duyệt đang chặn thông báo. Hãy cho phép trong cài đặt trang.',
    pushUnsupported: 'Trình duyệt này chưa hỗ trợ thông báo đẩy.',
    pushIosHint: 'Trên iPhone/iPad: thêm shop vào màn hình chính rồi bật thông báo trong app.',
    pushSyncing: 'Đang bật…',
    accountInstallApp: 'Cài đặt app',
    accountInstallAppTitle: 'Cài đặt ứng dụng',
    accountInstallAppHint: 'Thêm cửa hàng vào màn hình chính để mở nhanh như một app.',
    accountInstallAppButton: 'Cài đặt',
    accountInstallAppIosTip: 'Trên iPhone/iPad: chạm Share → «Thêm vào MH chính».',
    accountInstallAppInstalled: 'Ứng dụng đã được cài trên thiết bị này.',
    accountInstallAppManualTip: 'Mở menu trình duyệt và chọn «Cài đặt ứng dụng» hoặc «Thêm vào màn hình chính».',
    orderStatusLabel: 'Trạng thái',
    orderStatusAwaitingPayment: 'Chờ thanh toán',
    orderStatusPaymentChecking: 'Đang kiểm tra thanh toán',
    orderStatusPaidVerified: 'Đã thanh toán',
    orderStatusPendingManualReview: 'Chờ xác nhận',
    orderStatusCancelled: 'Đã hủy',
    orderShippingStatusLabel: 'Giao hàng',
    orderShippingPending: 'Chờ xử lý',
    orderShippingConfirmed: 'Đã xác nhận',
    orderShippingPacking: 'Đang đóng gói',
    orderShippingShipping: 'Đang giao',
    orderShippingDelivered: 'Đã giao',
    orderShippingReturned: 'Đã trả hàng',
    orderShippingCancelled: 'Đã hủy giao',
    orderDateLabel: 'Ngày đặt',
    orderViewPayment: 'Xem QR / thanh toán',
    orderHidePayment: 'Ẩn thanh toán',
    orderQuantityLabel: 'Số lượng',
    recentlyViewedClear: 'Xóa lịch sử',
    recentlyViewedCleared: 'Đã xóa lịch sử xem.',
    addressesEmptyHint: 'Chưa có địa chỉ nào. Nhấn "Thêm địa chỉ" để thêm.',
    addressAdd: '+ Thêm địa chỉ',
    addressEdit: 'Sửa',
    addressDelete: 'Xóa',
    addressDeleteConfirm: 'Xóa địa chỉ',
    addressDeleteConfirmBody: 'Bạn chắc chắn muốn xóa địa chỉ này?',
    addressCancel: 'Hủy',
    addressSave: 'Lưu địa chỉ',
    addressSetDefault: 'Đặt mặc định',
    addressDefaultBadge: 'Mặc định',
    addressFullName: 'Họ và tên',
    addressPhone: 'Số điện thoại',
    addressProvince: 'Tỉnh / Thành phố',
    addressProvincePlaceholder: '— Chọn tỉnh/thành phố —',
    addressDistrict: 'Quận / Huyện',
    addressWard: 'Phường / Xã',
    addressStreet: 'Địa chỉ cụ thể',
    addressStreetPlaceholder: 'Số nhà, tên đường, thôn/xóm...',
    addressMakeDefault: 'Đặt làm địa chỉ mặc định',
    addressManageBook: 'Quản lý sổ địa chỉ',
    addressCartTitle: 'Địa chỉ giao hàng',
    addressCartEmpty: 'Chưa có địa chỉ. Thêm địa chỉ để thanh toán.',
    addressCartAddHint: '+ Thêm địa chỉ mới',
    addressFormTitleAdd: 'Thêm địa chỉ mới',
    addressFormTitleEdit: 'Chỉnh sửa địa chỉ',
    addressDeleted: 'Đã xóa địa chỉ',
    addressSaveBook: 'Lưu vào sổ địa chỉ',
    addressCartModalTitle: 'Thêm địa chỉ giao hàng',
    reviewsTitle: 'Đánh giá sản phẩm',
    reviewsTotalSuffix: 'đánh giá',
    reviewsWriteButton: 'Viết đánh giá',
    reviewsFormRatingLabel: 'Chọn số sao',
    reviewsFormContentPlaceholder: 'Chia sẻ cảm nhận của bạn về sản phẩm...',
    reviewsFormImagesLabel: 'Thêm ảnh (không bắt buộc)',
    reviewsFormSubmit: 'Gửi đánh giá',
    reviewsFormCancel: 'Huỷ',
    reviewsSubmitSuccess: 'Cảm ơn bạn đã đánh giá!',
    reviewsSubmitLoginRequired: 'Vui lòng đăng nhập để đánh giá sản phẩm.',
    reviewsSubmitAlreadyReviewed: 'Bạn đã đánh giá sản phẩm này rồi.',
    reviewsSubmitNotEligible: 'Chỉ khách đã nhận hàng mới có thể đánh giá sản phẩm này.',
    reviewsEmpty: 'Chưa có đánh giá nào — hãy là người đầu tiên!',
    reviewsLoadMore: 'Xem thêm đánh giá',
    reviewsUsefulLabel: 'Hữu ích',
    reviewsMerchantReplyPrefix: 'Phản hồi từ',
    qaTitle: 'Hỏi đáp về sản phẩm',
    qaAskButton: 'Đặt câu hỏi',
    qaFormPlaceholder: 'Bạn muốn hỏi gì về sản phẩm này?',
    qaFormSubmit: 'Gửi câu hỏi',
    qaSubmitSuccess: 'Đã gửi câu hỏi của bạn!',
    qaSubmitLoginRequired: 'Vui lòng đăng nhập để đặt câu hỏi.',
    qaEmpty: 'Chưa có câu hỏi nào — hãy là người đầu tiên hỏi!',
    qaLoadMore: 'Xem thêm câu hỏi',
    qaAnswerButton: 'Trả lời',
    qaAnswerFormPlaceholder: 'Chia sẻ câu trả lời của bạn...',
    qaAnswerSubmit: 'Gửi trả lời',
    qaAnswerNotEligible: 'Chỉ khách đã mua sản phẩm này mới có thể trả lời.',
    qaAnswerSlotFull: 'Câu hỏi này đã đủ số lượt trả lời công khai.',
    qaVerifiedBadge: 'Đã mua hàng',
    qaAdminBadge: 'Chủ shop',
    qaNoAnswersYet: 'Chưa có câu trả lời.',
    footerColShop: 'Cửa hàng',
    footerColShopping: 'Mua sắm',
    footerColSupport: 'Hỗ trợ khách hàng',
    footerColLegal: 'Chính sách',
    footerBrandHint: 'Mua sắm trực tuyến — sản phẩm đúng mô tả, giao hàng toàn quốc.',
    footerCopyright: '© {year} {shop}. Bảo lưu mọi quyền.',
    footerPaymentHint: 'Thanh toán: COD · Chuyển khoản',
    lpExploreProducts: 'Khám phá sản phẩm',
    lpViewProducts: 'Xem sản phẩm',
    lpSuggestedForYou: 'Gợi ý dành cho bạn',
    homeYouMayLike: 'CÓ THỂ BẠN THÍCH',
    forYouBadge: 'Dành cho bạn',
    lpHighlightsHeading: 'Điểm nổi bật & đáng mua',
    lpFaqHeading: 'Câu hỏi thường gặp',
    lpRealReviews: '{rating}/5 · {count} đánh giá thật',
    lpViewFullCategory: 'Xem toàn bộ danh mục →',
    lpMaterialChip: 'Chất liệu: {name}',
    lpTrust1: 'Chọn lựa kỹ lưỡng',
    lpTrust2: 'Đặt hàng thuận tiện',
    lpTrust3: 'Hỗ trợ khi cần',
  },
  en: {
    navHome: 'Home',
    navProducts: 'Products',
    navRecentlyViewed: 'Recent',
    navFavorites: 'Favorites',
    navRecommended: 'For you',
    navCart: 'Cart',
    navChat: 'Chat',
    navChatZalo: 'Zalo chat',
    navChatFacebook: 'Facebook chat',
    navChatWhatsapp: 'WhatsApp chat',
    navTopUp: 'Back to top',
    navCategories: 'Categories',
    catalogTitle: 'All products',
    categorySeoBodyAriaLabel: 'About this category',
    categorySubcategoriesLabel: 'Subcategories',
    categoryFilterMinPrice: 'Min price',
    categoryFilterMaxPrice: 'Max price',
    categoryFilterApply: 'Apply',
    categoryFilterClear: 'Clear filters',
    categorySortLabel: 'Sort',
    categorySortNewest: 'Newest',
    categorySortRandom: 'Random',
    categorySortOldest: 'Oldest',
    categorySortViews: 'Most viewed',
    categorySortPriceAsc: 'Price: low to high',
    categorySortPriceDesc: 'Price: high to low',
    categoryFilterSize: 'Size',
    categoryFilterColor: 'Color',
    categoryFilterAllSizes: 'All sizes',
    categoryFilterAllColors: 'All colors',
    categoryMegaHint: 'Hover a category to see level 2 and 3.',
    khoSaleNavLabel: 'Warehouse sale',
    khoSaleNavBlurb: 'Returned and clearance stock — promotional prices, limited quantity.',
    khoSaleViewAll: 'View all →',
    khoSalePageTitle: 'Warehouse sale',
    categorySeoRowAria: 'Size SEO links',
    categoryExpand: 'Open subcategories',
    categoryCollapse: 'Collapse subcategories',
    categoryHubTitle: 'Shop categories',
    categoryHubEmpty: 'No categories to show yet.',
    categoryPagePrev: 'Prev',
    categoryPageNext: 'Next',
    categoryFiltersAria: 'Product filters',
    catalogEmpty: 'No products yet.',
    loadMore: 'Load more',
    productDetail: 'Product details',
    addToCart: 'Add to cart',
    buyNow: 'Buy now',
    addedToCart: 'Added to cart.',
    cartAddedTitle: 'Added to cart',
    cartGoToCart: 'View cart',
    cartContinueShopping: 'Continue shopping',
    cartAddedClose: 'Close',
    lowStockUrgency: 'Only {n} left in stock — order soon!',
    galleryZoomHint: 'Tap to zoom, swipe for more photos',
    lightboxClose: 'Close',
    lightboxPrev: 'Previous photo',
    lightboxNext: 'Next photo',
    consultChat: 'Chat for advice',
    cartTitle: 'Shopping cart',
    cartEmpty: 'Your cart is empty.',
    cartSubtotal: 'Subtotal',
    cartCheckout: 'Checkout',
    cartCheckingOut: 'Placing order…',
    cartRemove: 'Remove',
    cartPromoLabel: 'Promo code',
    cartPromoPlaceholder: 'Enter promo code',
    cartPromoApply: 'Apply',
    cartPromoApplying: 'Checking...',
    cartPromoRemove: 'Remove code',
    cartPromoDiscountLabel: 'Discount',
    cartTotalLabel: 'Total',
    cartShippingFeeLabel: 'Shipping fee',
    cartShippingFeeFree: 'Free shipping',
    cartShippingFeeIncluded: 'Shipping fee included',
    cartShippingFreeThresholdHint: 'add more to reach {amount} for free shipping',
    checkoutPaymentMethodLabel: 'Payment method',
    checkoutPaymentMethodBank: 'Bank transfer',
    checkoutPaymentMethodEwallet: 'E-wallet',
    checkoutPaymentMethodHint: 'Applies to the upfront amount (if any); the rest is paid on delivery.',
    orderConfirmEwalletTitle: 'Pay via e-wallet',
    orderConfirmEwalletHint: 'Scan the QR code with your e-wallet app, enter the exact amount, then send a payment screenshot below.',
    promoErrorNotFound: 'Promo code not found.',
    promoErrorInactive: 'This promo code is no longer active.',
    promoErrorNotStarted: "This promo code isn't valid yet.",
    promoErrorExpired: 'This promo code has expired.',
    promoErrorBelowMinSubtotal: "Your order doesn't meet the minimum amount for this code.",
    promoErrorUsageLimitReached: 'This promo code has reached its usage limit.',
    promoErrorPerUserLimitReached: "You've already used this code the maximum number of times.",
    promoErrorFirstOrderOnly: 'This code is only valid for first orders.',
    promoErrorNoEligibleItems: "Your cart doesn't have items eligible for this code.",
    promoErrorGrantRequired: 'This code is only available if it was granted to your wallet.',
    promoErrorGeneric: 'Could not apply this promo code.',
    checkoutName: 'Full name',
    checkoutPhone: 'Phone',
    checkoutAddress: 'Shipping address',
    checkoutNote: 'Note',
    checkoutSuccess: 'Order placed — the shop will contact you soon.',
    checkoutAuthRequired: 'Please sign in to continue.',
    checkoutGuestHint: 'You can checkout without signing in — just fill in delivery details.',
    checkoutAuthLink: 'Sign in / verify via shop chat',
    quantity: 'Quantity',
    backToShop: 'Continue shopping',
    navOrders: 'Orders',
    sizeLabel: 'Size',
    colorLabel: 'Color',
    sizeGuideButton: 'Size guide',
    sizeGuideModalTitle: 'Size chart',
    sizeGuideFallbackLink: 'View size guide',
    sizeGuideClose: 'Close',
    contactChannelsAria: 'Quick contact',
    contactChannelPhone: 'Call',
    contactChannelZalo: 'Zalo',
    contactChannelMessenger: 'Messenger',
    contactChannelInstagram: 'Instagram',
    flashSaleBadge: 'Flash sale',
    flashSaleEndsIn: 'Ends in',
    shippingCarrierLabel: 'Shipping carrier',
    searchPlaceholder: 'Search products…',
    searchButton: 'Search',
    searchByImage: 'Search by image',
    searchSearching: 'Searching…',
    searchResults: 'Search results',
    searchEmpty: 'No matching products.',
    searchError: 'Search failed. Try again.',
    relatedProducts: 'Similar products',
    relatedSeeAll: 'See all',
    relatedEmpty: 'No other products in this category.',
    outfitTitleFallback: 'Pair with this piece',
    outfitSubtitle: 'Other categories to wear together',
    outfitSlotsAria: 'Outfit groups',
    outfitEmpty: 'No outfit suggestions for this product yet.',
    outfitError: 'Could not load outfit suggestions.',
    outfitSeeAll: 'See all',
    tryOnLink: 'AI try-on',
    favoriteProduct: 'Like product',
    skuLabel: 'SKU',
    pdpRatingLabel: 'Reviews',
    pdpLineTotal: 'Total',
    pdpSavings: 'Save {amount}',
    pdpQtyBuy: 'Quantity',
    pdpShippingNote: 'Nationwide delivery. {free}Returns within 7 days if the item is faulty or not as described.',
    pdpShippingFreeFrom: 'Free shipping from {amount}. ',
    pdpShippingPolicyLink: 'Shipping policy',
    pdpReturnsPolicyLink: 'Returns policy',
    pdpServiceLabel: 'Service',
    pdpServiceNote: 'Pay on delivery, exchange size if it does not fit, inspect before accepting.',
    pdpNotesTitle: 'Notes',
    pdpNoteFit: 'Actual size may differ slightly from the description.',
    pdpNoteColor: 'Colors on screen may differ slightly from the real product.',
    pdpStickyHome: 'Home',
    pdpStickyHomeL1: 'Home',
    pdpStickyHomeL2: '',
    pdpStickyTryOnL1: 'Try',
    pdpStickyTryOnL2: 'on',
    pdpStickyLikeLabel: 'Like',
    pdpAddToCartShort: 'Add to cart',
    pdpBuyNowShort: 'Buy now',
    pdpShareCopy: 'Copy link',
    pdpShareCopied: 'Copied',
    pdpJumpReviews: 'See reviews',
    pdpJumpQa: 'Q&A',
    pdpBrandLabel: 'Brand',
    pdpOriginLabel: 'Origin',
    pdpMaterialLabel: 'Material',
    pdpStyleLabel: 'Style',
    pdpOccasionLabel: 'Occasion',
    pdpWeightLabel: 'Weight',
    pdpFeaturesLabel: 'Features',
    pdpCategoryLabel: 'Category',
    pdpPurchasesLabel: 'Sold',
    pdpLikesLabel: 'Likes',
    pdpRatingCountSuffix: 'ratings',
    pdpDescTab: 'Product description',
    pdpSpecsTab: 'Product information',
    pdpDetailImagesHeading: 'Product detail photos',
    pdpSpecsEmpty: 'No product information yet.',
    pdpYes: 'Yes',
    pdpNo: 'No',
    ordersTitle: 'Your orders',
    ordersEmpty: 'No orders yet.',
    thankYouOrderLabel: 'Order ID',
    thankYouTrackCta: 'Track order',
    ordersFilterAriaLabel: 'Filter orders by status',
    ordersFilterAll: 'All',
    ordersFilterWaitingPayment: 'Awaiting payment',
    ordersFilterProcessing: 'In progress',
    ordersFilterDelivered: 'Delivered',
    ordersFilterReviewed: 'Reviewed',
    ordersFilterCancelled: 'Cancelled',
    ordersFilterReturned: 'Returned',
    ordersFilterEmpty: 'No orders in this status.',
    orderTrack: 'Track order',
    orderHideTrack: 'Hide timeline',
    orderConfirmReceived: 'I received the order',
    orderConfirmReceivedHint: 'Confirm you received everything. You can review the product after that.',
    orderConfirmReceivedOk: 'Delivery confirmed.',
    orderCancel: 'Cancel order',
    orderCancelHint: 'You can cancel only before payment is confirmed or the order is shipped.',
    orderCancelOk: 'Order cancelled.',
    orderCancelReason: 'Cancel reason (optional)',
    orderReview: 'Review',
    orderDetail: 'Order details',
    orderHideDetail: 'Hide details',
    orderTimelineTitle: 'Order timeline',
    orderTimelineCreated: 'Order placed',
    orderTimelineConfirmed: 'Shop confirmed',
    orderTimelinePacking: 'Packing',
    orderTimelineShipping: 'Out for delivery',
    orderTimelineDelivered: 'Delivered',
    orderActionFailed: 'Could not complete this action. Try again.',
    orderAddressLabel: 'Shipping address',
    authSendOtp: 'Send OTP',
    authVerifyOtp: 'Verify',
    authSuccess: 'Email verified — you can checkout.',
    authFailed: 'Verification failed. Try again.',
    authOtpSent: 'OTP sent to your email.',
    authEmailLogin: 'Sign in with email',
    authChangeEmail: 'Use a different email',
    authEmailRequired: 'Please enter your email.',
    authGoogleLogin: 'Sign in with Google',
    authShopOtpOr: 'Or enter email to receive a code',
    authLoginSubtitle: 'Google or OTP via email',
    authLoginTitle: 'Sign in',
    authLoginWelcome: 'Welcome back',
    authQuickLoginFailed: 'Could not sign in — use email OTP below.',
    authNanoAiLoginHint: 'Enter your email — you will receive an OTP code by email.',
    authRememberDevice: 'Keep me signed in on this device (you may skip OTP next time).',
    orderIdLabel: 'Order ID',
    depositAmount: 'Deposit amount',
    paymentReference: 'Transfer reference',
    depositPolicyNote: 'Deposit per shop settings — scan QR or transfer with the reference.',
    productDescriptionTitle: 'Product description',
    productDetailImagesTitle: 'Detail images',
    productVideoTitle: 'Product video',
    pdpConsultNoteTitle: 'Stylist note',
    pdpMaterialImagesTitle: 'Material photos',
    pdpRealUseImagesTitle: 'On-body photos',
    favoriteAdd: 'Add to favorites',
    favoriteRemove: 'Remove from favorites',
    wishlistTitle: 'Favorites',
    wishlistEmpty: 'No favorite products yet.',
    recentlyViewedTitle: 'Recently viewed',
    recentlyViewedEmpty: 'No recently viewed products.',
    chatOpenLabel: 'Open chat',
    chatCloseLabel: 'Close',
    chatFullPageLabel: 'Open full page',
    chatLanguageLabel: 'Language',
    consentMessage: 'This site uses cookies to improve your shopping experience and measure ad performance.',
    consentAccept: 'Accept',
    consentReject: 'Decline',
    navAccount: 'Account',
    navLogout: 'Log out',
    navRegister: 'Sign up',
    leadFormTitle: 'Get updates',
    navWallet: 'My vouchers',
    walletTitle: 'Your vouchers',
    walletHint: 'Copy a code and paste it into the promo code field at checkout to apply it.',
    walletEmpty: "You don't have any vouchers yet.",
    walletCopyCode: 'Copy code',
    walletCodeCopied: 'Code copied!',
    walletExpiresLabel: 'Expires',
    walletMinSubtotalNote: 'Valid for orders from',
    accountEditProfile: 'Edit profile',
    accountViewedProducts: 'Viewed products',
    accountAddressBook: 'Address book',
    accountEmailLabel: 'Email',
    accountSave: 'Save changes',
    accountSaved: 'Profile saved.',
    accountSaveFailed: 'Could not save. Try again.',
    addressesHint: 'Manage multiple shipping addresses. The default is used at checkout.',
    accountWelcome: 'Hello',
    accountQuickLinks: 'Quick links',
    accountOpenShopAdmin: 'Open shop admin',
    accountOpenShopAdminHint: 'This Gmail was invited as shop admin — open the shop admin page.',
    accountSectionEditProfile: 'Edit profile',
    accountSecurity: 'Security',
    accountSecurityTitle: 'Account security',
    accountSecurityLoginNote: 'Sign in with email OTP or Google — no password is used.',
    accountSignOutDevice: 'Sign out this device',
    accountSignOutDone: 'Signed out on this device.',
    accountSecurityReAuth: 'Sign in again',
    accountNotifications: 'Notifications',
    accountNotificationsTitle: 'Notification center',
    accountNotificationsEmpty: 'You have no notifications yet.',
    accountNotificationsMarkAllRead: 'Mark all as read',
    accountNotificationsLogin: 'Please sign in to view notifications.',
    accountNotificationsLoading: 'Loading notifications...',
    accountNotificationsSignIn: 'Sign in now',
    pushEnableTitle: 'Browser notifications',
    pushEnableHint: 'Get order and shop alerts even when this page is closed.',
    pushEnableButton: 'Turn on push notifications',
    pushEnabled: 'Push notifications are on for this device.',
    pushDenied: 'Notifications are blocked. Allow them in your browser site settings.',
    pushUnsupported: 'This browser does not support push notifications.',
    pushIosHint: 'On iPhone/iPad: add the shop to your Home Screen, then enable notifications in the app.',
    pushSyncing: 'Turning on…',
    accountInstallApp: 'Install app',
    accountInstallAppTitle: 'Install the app',
    accountInstallAppHint: 'Add this shop to your home screen for quick access like an app.',
    accountInstallAppButton: 'Install',
    accountInstallAppIosTip: 'On iPhone/iPad: tap Share → “Add to Home Screen”.',
    accountInstallAppInstalled: 'The app is already installed on this device.',
    accountInstallAppManualTip: 'Open your browser menu and choose “Install app” or “Add to Home Screen”.',
    orderStatusLabel: 'Status',
    orderStatusAwaitingPayment: 'Awaiting payment',
    orderStatusPaymentChecking: 'Checking payment',
    orderStatusPaidVerified: 'Paid',
    orderStatusPendingManualReview: 'Pending review',
    orderStatusCancelled: 'Cancelled',
    orderShippingStatusLabel: 'Shipping',
    orderShippingPending: 'Pending',
    orderShippingConfirmed: 'Confirmed',
    orderShippingPacking: 'Packing',
    orderShippingShipping: 'In transit',
    orderShippingDelivered: 'Delivered',
    orderShippingReturned: 'Returned',
    orderShippingCancelled: 'Shipping cancelled',
    orderDateLabel: 'Order date',
    orderViewPayment: 'View payment QR',
    orderHidePayment: 'Hide payment',
    orderQuantityLabel: 'Quantity',
    recentlyViewedClear: 'Clear history',
    recentlyViewedCleared: 'View history cleared.',
    addressesEmptyHint: 'No addresses yet. Tap "Add address" to add one.',
    addressAdd: '+ Add address',
    addressEdit: 'Edit',
    addressDelete: 'Delete',
    addressDeleteConfirm: 'Delete address',
    addressDeleteConfirmBody: 'Delete this address?',
    addressCancel: 'Cancel',
    addressSave: 'Save address',
    addressSetDefault: 'Set as default',
    addressDefaultBadge: 'Default',
    addressFullName: 'Full name',
    addressPhone: 'Phone number',
    addressProvince: 'Province / City',
    addressProvincePlaceholder: '— Select province/city —',
    addressDistrict: 'District',
    addressWard: 'Ward',
    addressStreet: 'Street address',
    addressStreetPlaceholder: 'House number, street, village…',
    addressMakeDefault: 'Set as default address',
    addressManageBook: 'Manage address book',
    addressCartTitle: 'Shipping address',
    addressCartEmpty: 'No address yet. Add one to check out.',
    addressCartAddHint: '+ Add a new address',
    addressFormTitleAdd: 'Add a new address',
    addressFormTitleEdit: 'Edit address',
    addressDeleted: 'Address deleted',
    addressSaveBook: 'Save to address book',
    addressCartModalTitle: 'Add shipping address',
    reviewsTitle: 'Product reviews',
    reviewsTotalSuffix: 'reviews',
    reviewsWriteButton: 'Write a review',
    reviewsFormRatingLabel: 'Select rating',
    reviewsFormContentPlaceholder: 'Share your thoughts about this product...',
    reviewsFormImagesLabel: 'Add photos (optional)',
    reviewsFormSubmit: 'Submit review',
    reviewsFormCancel: 'Cancel',
    reviewsSubmitSuccess: 'Thanks for your review!',
    reviewsSubmitLoginRequired: 'Please sign in to review this product.',
    reviewsSubmitAlreadyReviewed: 'You already reviewed this product.',
    reviewsSubmitNotEligible: 'Only customers who received this product can review it.',
    reviewsEmpty: 'No reviews yet — be the first!',
    reviewsLoadMore: 'Load more reviews',
    reviewsUsefulLabel: 'Helpful',
    reviewsMerchantReplyPrefix: 'Reply from',
    qaTitle: 'Questions & answers',
    qaAskButton: 'Ask a question',
    qaFormPlaceholder: 'What would you like to know about this product?',
    qaFormSubmit: 'Submit question',
    qaSubmitSuccess: 'Your question has been submitted!',
    qaSubmitLoginRequired: 'Please sign in to ask a question.',
    qaEmpty: 'No questions yet — be the first to ask!',
    qaLoadMore: 'Load more questions',
    qaAnswerButton: 'Answer',
    qaAnswerFormPlaceholder: 'Share your answer...',
    qaAnswerSubmit: 'Submit answer',
    qaAnswerNotEligible: 'Only customers who bought this product can answer.',
    qaAnswerSlotFull: 'This question already has enough public answers.',
    qaVerifiedBadge: 'Verified buyer',
    qaAdminBadge: 'Shop owner',
    qaNoAnswersYet: 'No answers yet.',
    footerColShop: 'Shop',
    footerColShopping: 'Shopping',
    footerColSupport: 'Customer support',
    footerColLegal: 'Policies',
    footerBrandHint: 'Shop online — products as described, nationwide delivery.',
    footerCopyright: '© {year} {shop}. All rights reserved.',
    footerPaymentHint: 'Payment: COD · Bank transfer',
    lpExploreProducts: 'Explore products',
    lpViewProducts: 'View products',
    lpSuggestedForYou: 'Suggested for you',
    homeYouMayLike: 'YOU MAY ALSO LIKE',
    forYouBadge: 'For you',
    lpHighlightsHeading: 'Highlights worth buying',
    lpFaqHeading: 'Frequently asked questions',
    lpRealReviews: '{rating}/5 · {count} real reviews',
    lpViewFullCategory: 'View full category →',
    lpMaterialChip: 'Material: {name}',
    lpTrust1: 'Carefully selected',
    lpTrust2: 'Easy ordering',
    lpTrust3: 'Support when you need it',
  },
  zh: {
    navHome: '首页',
    navProducts: '产品',
    navRecentlyViewed: '最近浏览',
    navFavorites: '收藏',
    navRecommended: '推荐',
    navCart: '购物车',
    navChat: '聊天购买',
    navChatZalo: 'Zalo 聊天',
    navChatFacebook: 'Facebook 聊天',
    navChatWhatsapp: 'WhatsApp 聊天',
    navTopUp: '回到顶部',
    navCategories: '分类',
    catalogTitle: '全部产品',
    categorySeoBodyAriaLabel: '分类介绍',
    categorySubcategoriesLabel: '子分类',
    categoryFilterMinPrice: '最低价',
    categoryFilterMaxPrice: '最高价',
    categoryFilterApply: '应用',
    categoryFilterClear: '清除筛选',
    categorySortLabel: '排序',
    categorySortNewest: '最新',
    categorySortRandom: '随机',
    categorySortOldest: '最早',
    categorySortViews: '最多浏览',
    categorySortPriceAsc: '价格从低到高',
    categorySortPriceDesc: '价格从高到低',
    categoryFilterSize: '尺码',
    categoryFilterColor: '颜色',
    categoryFilterAllSizes: '全部尺码',
    categoryFilterAllColors: '全部颜色',
    categoryMegaHint: '将鼠标移到分类上可查看二级、三级。',
    khoSaleNavLabel: '仓库特卖',
    khoSaleNavBlurb: '退货与清仓库存 — 优惠价，数量有限。',
    khoSaleViewAll: '查看全部 →',
    khoSalePageTitle: '仓库特卖',
    categorySeoRowAria: '尺码搜索链接',
    categoryExpand: '打开子分类',
    categoryCollapse: '收起子分类',
    categoryHubTitle: '商品分类',
    categoryHubEmpty: '暂无可显示的分类。',
    categoryPagePrev: '上一页',
    categoryPageNext: '下一页',
    categoryFiltersAria: '商品筛选',
    catalogEmpty: '暂无产品。',
    loadMore: '加载更多',
    productDetail: '产品详情',
    addToCart: '加入购物车',
    buyNow: '立即购买',
    addedToCart: '已加入购物车。',
    cartAddedTitle: '已加入购物车',
    cartGoToCart: '进入购物车',
    cartContinueShopping: '继续购物',
    cartAddedClose: '关闭',
    lowStockUrgency: '仅剩 {n} 件 — 尽快下单！',
    galleryZoomHint: '点击放大，滑动查看更多图片',
    lightboxClose: '关闭',
    lightboxPrev: '上一张',
    lightboxNext: '下一张',
    consultChat: '咨询聊天',
    cartTitle: '购物车',
    cartEmpty: '购物车为空。',
    cartSubtotal: '小计',
    cartCheckout: '结账',
    cartCheckingOut: '正在下单…',
    cartRemove: '删除',
    cartPromoLabel: '优惠码',
    cartPromoPlaceholder: '输入优惠码',
    cartPromoApply: '应用',
    cartPromoApplying: '正在检查...',
    cartPromoRemove: '移除优惠码',
    cartPromoDiscountLabel: '优惠',
    cartTotalLabel: '总计',
    cartShippingFeeLabel: '运费',
    cartShippingFeeFree: '免运费',
    cartShippingFeeIncluded: '已含运费',
    cartShippingFreeThresholdHint: '再购买以满 {amount} 即可免运费',
    checkoutPaymentMethodLabel: '支付方式',
    checkoutPaymentMethodBank: '银行转账',
    checkoutPaymentMethodEwallet: '电子钱包',
    checkoutPaymentMethodHint: '适用于需要预付的金额（如有）；其余款项到货后支付。',
    orderConfirmEwalletTitle: '通过电子钱包支付',
    orderConfirmEwalletHint: '使用电子钱包 App 扫描二维码，输入准确金额，然后在下方上传付款截图。',
    promoErrorNotFound: '优惠码不存在。',
    promoErrorInactive: '此优惠码已停用。',
    promoErrorNotStarted: '此优惠码尚未生效。',
    promoErrorExpired: '此优惠码已过期。',
    promoErrorBelowMinSubtotal: '订单金额未达到使用此优惠码的最低要求。',
    promoErrorUsageLimitReached: '此优惠码使用次数已达上限。',
    promoErrorPerUserLimitReached: '您已达到此优惠码的最大使用次数。',
    promoErrorFirstOrderOnly: '此优惠码仅适用于首次订单。',
    promoErrorNoEligibleItems: '购物车中没有符合此优惠码的商品。',
    promoErrorGrantRequired: '此优惠码仅在已获赠时可用。',
    promoErrorGeneric: '无法应用此优惠码。',
    checkoutName: '姓名',
    checkoutPhone: '电话',
    checkoutAddress: '收货地址',
    checkoutNote: '备注',
    checkoutSuccess: '订单已创建 — 店铺将尽快联系。',
    checkoutAuthRequired: '请登录后继续。',
    checkoutGuestHint: '无需登录即可下单 — 填写收货信息即可。',
    checkoutAuthLink: '在店铺聊天中登录/验证',
    quantity: '数量',
    backToShop: '继续购物',
    navOrders: '订单',
    sizeLabel: '尺码',
    colorLabel: '颜色',
    sizeGuideButton: '尺码指南',
    sizeGuideModalTitle: '尺码表',
    sizeGuideFallbackLink: '查看尺码指南',
    sizeGuideClose: '关闭',
    contactChannelsAria: '快速联系',
    contactChannelPhone: '电话',
    contactChannelZalo: 'Zalo',
    contactChannelMessenger: 'Messenger',
    contactChannelInstagram: 'Instagram',
    flashSaleBadge: '限时特惠',
    flashSaleEndsIn: '距结束',
    shippingCarrierLabel: '物流公司',
    searchPlaceholder: '搜索产品…',
    searchButton: '搜索',
    searchByImage: '以图搜图',
    searchSearching: '搜索中…',
    searchResults: '搜索结果',
    searchEmpty: '未找到匹配商品。',
    searchError: '搜索失败，请重试。',
    relatedProducts: '相似商品',
    relatedSeeAll: '查看全部',
    relatedEmpty: '该分类暂无其他商品。',
    outfitTitleFallback: '搭配单品',
    outfitSubtitle: '不同品类一起穿',
    outfitSlotsAria: '搭配分组',
    outfitEmpty: '暂无搭配建议。',
    outfitError: '无法加载搭配建议。',
    outfitSeeAll: '查看全部',
    tryOnLink: 'AI 试穿',
    favoriteProduct: '收藏商品',
    skuLabel: '货号',
    pdpRatingLabel: '评价',
    pdpLineTotal: '合计',
    pdpSavings: '节省 {amount}',
    pdpQtyBuy: '购买数量',
    pdpShippingNote: '全国配送。{free}如商品有瑕疵或与描述不符，7 天内可退换。',
    pdpShippingFreeFrom: '满 {amount} 包邮。 ',
    pdpShippingPolicyLink: '配送政策',
    pdpReturnsPolicyLink: '退换政策',
    pdpServiceLabel: '服务',
    pdpServiceNote: '货到付款，尺码不合适可换，收货前可验货。',
    pdpNotesTitle: '提示',
    pdpNoteFit: '实际尺寸可能与描述略有差异。',
    pdpNoteColor: '受光线和设备影响，实物颜色可能与图片略有不同。',
    pdpStickyHome: '首页',
    pdpStickyHomeL1: '首页',
    pdpStickyHomeL2: '',
    pdpStickyTryOnL1: '试穿',
    pdpStickyTryOnL2: '',
    pdpStickyLikeLabel: '喜欢',
    pdpAddToCartShort: '加入购物车',
    pdpBuyNowShort: '立即购买',
    pdpShareCopy: '复制链接',
    pdpShareCopied: '已复制',
    pdpJumpReviews: '查看评价',
    pdpJumpQa: '问答',
    pdpBrandLabel: '品牌',
    pdpOriginLabel: '产地',
    pdpMaterialLabel: '材质',
    pdpStyleLabel: '风格',
    pdpOccasionLabel: '场合',
    pdpWeightLabel: '重量',
    pdpFeaturesLabel: '卖点',
    pdpCategoryLabel: '类目',
    pdpPurchasesLabel: '已售',
    pdpLikesLabel: '喜欢',
    pdpRatingCountSuffix: '次',
    pdpDescTab: '商品描述',
    pdpSpecsTab: '商品信息',
    pdpDetailImagesHeading: '商品细节图',
    pdpSpecsEmpty: '暂无商品信息。',
    pdpYes: '是',
    pdpNo: '否',
    ordersTitle: '我的订单',
    ordersEmpty: '暂无订单。',
    thankYouOrderLabel: '订单编号',
    thankYouTrackCta: '跟踪订单',
    ordersFilterAriaLabel: '按订单状态筛选',
    ordersFilterAll: '全部',
    ordersFilterWaitingPayment: '待付款',
    ordersFilterProcessing: '待收货',
    ordersFilterDelivered: '已收货',
    ordersFilterReviewed: '已评价',
    ordersFilterCancelled: '已取消',
    ordersFilterReturned: '已退货',
    ordersFilterEmpty: '该状态下没有订单。',
    orderTrack: '跟踪订单',
    orderHideTrack: '隐藏进度',
    orderConfirmReceived: '已收货',
    orderConfirmReceivedHint: '确认您已收到全部商品。之后可以评价商品。',
    orderConfirmReceivedOk: '已确认收货。',
    orderCancel: '取消订单',
    orderCancelHint: '仅在未确认付款或未发货时可以取消。',
    orderCancelOk: '订单已取消。',
    orderCancelReason: '取消原因（可选）',
    orderReview: '评价',
    orderDetail: '订单详情',
    orderHideDetail: '隐藏详情',
    orderTimelineTitle: '订单进度',
    orderTimelineCreated: '已下单',
    orderTimelineConfirmed: '店铺已确认',
    orderTimelinePacking: '打包中',
    orderTimelineShipping: '配送中',
    orderTimelineDelivered: '已收货',
    orderActionFailed: '操作失败，请重试。',
    orderAddressLabel: '收货地址',
    authSendOtp: '发送验证码',
    authVerifyOtp: '验证',
    authSuccess: '邮箱已验证 — 可以结账。',
    authFailed: '验证失败，请重试。',
    authOtpSent: '验证码已发送到邮箱。',
    authEmailLogin: '邮箱登录',
    authChangeEmail: '更换邮箱',
    authEmailRequired: '请输入邮箱。',
    authGoogleLogin: '使用 Google 登录',
    authShopOtpOr: '或输入邮箱获取验证码',
    authLoginSubtitle: 'Google 或邮箱 OTP',
    authLoginTitle: '登录',
    authLoginWelcome: '欢迎回来',
    authQuickLoginFailed: '无法登录 — 请使用下方邮箱 OTP。',
    authNanoAiLoginHint: '输入邮箱 — 您将通过邮件收到验证码。',
    authRememberDevice: '在此设备保持登录（下次可能免 OTP）。',
    orderIdLabel: '订单号',
    depositAmount: '定金金额',
    paymentReference: '转账备注',
    depositPolicyNote: '按店铺设置支付定金 — 扫码或转账并填写备注。',
    productDescriptionTitle: '产品描述',
    productDetailImagesTitle: '细节图片',
    productVideoTitle: '产品视频',
    pdpConsultNoteTitle: '搭配建议',
    pdpMaterialImagesTitle: '材质细节',
    pdpRealUseImagesTitle: '实拍图',
    favoriteAdd: '加入收藏',
    favoriteRemove: '取消收藏',
    wishlistTitle: '收藏',
    wishlistEmpty: '暂无收藏商品。',
    recentlyViewedTitle: '最近浏览',
    recentlyViewedEmpty: '暂无浏览记录。',
    chatOpenLabel: '打开聊天',
    chatCloseLabel: '关闭',
    chatFullPageLabel: '全页打开',
    chatLanguageLabel: '语言',
    consentMessage: '本网站使用 Cookie 以改善您的购物体验并评估广告效果。',
    consentAccept: '同意',
    consentReject: '拒绝',
    navAccount: '账户',
    navLogout: '退出登录',
    navRegister: '注册',
    leadFormTitle: '订阅资讯',
    navWallet: '我的优惠券',
    walletTitle: '您的优惠券',
    walletHint: '复制代码并粘贴到结账时的优惠码栏即可使用。',
    walletEmpty: '您的钱包中还没有优惠券。',
    walletCopyCode: '复制代码',
    walletCodeCopied: '代码已复制！',
    walletExpiresLabel: '过期时间',
    walletMinSubtotalNote: '适用于满',
    accountEditProfile: '编辑资料',
    accountViewedProducts: '浏览记录',
    accountAddressBook: '地址簿',
    accountEmailLabel: '邮箱',
    accountSave: '保存更改',
    accountSaved: '资料已保存。',
    accountSaveFailed: '保存失败，请重试。',
    addressesHint: '管理多个收货地址。结账时使用默认地址。',
    accountWelcome: '您好',
    accountQuickLinks: '快捷入口',
    accountOpenShopAdmin: '进入店铺管理页',
    accountOpenShopAdminHint: '此 Gmail 已被邀请为店铺管理员 — 可快速打开管理页。',
    accountSectionEditProfile: '编辑资料',
    accountSecurity: '安全',
    accountSecurityTitle: '账户安全',
    accountSecurityLoginNote: '通过邮箱 OTP 或 Google 登录 — 无需密码。',
    accountSignOutDevice: '退出此设备',
    accountSignOutDone: '已在此设备退出登录。',
    accountSecurityReAuth: '重新登录',
    accountNotifications: '通知',
    accountNotificationsTitle: '通知中心',
    accountNotificationsEmpty: '您还没有通知。',
    accountNotificationsMarkAllRead: '全部标为已读',
    accountNotificationsLogin: '请登录后查看通知。',
    accountNotificationsLoading: '正在加载通知...',
    accountNotificationsSignIn: '立即登录',
    pushEnableTitle: '浏览器通知',
    pushEnableHint: '即使未打开页面，也能收到订单和店铺通知。',
    pushEnableButton: '开启推送通知',
    pushEnabled: '此设备已开启推送通知。',
    pushDenied: '浏览器已拦截通知。请在网站设置中允许。',
    pushUnsupported: '此浏览器不支持推送通知。',
    pushIosHint: '在 iPhone/iPad：先将店铺添加到主屏幕，再在应用中开启通知。',
    pushSyncing: '正在开启…',
    accountInstallApp: '安装应用',
    accountInstallAppTitle: '安装应用',
    accountInstallAppHint: '将店铺添加到主屏幕，像应用一样快速打开。',
    accountInstallAppButton: '安装',
    accountInstallAppIosTip: '在 iPhone/iPad：点分享 →「添加到主屏幕」。',
    accountInstallAppInstalled: '此设备已安装该应用。',
    accountInstallAppManualTip: '打开浏览器菜单，选择「安装应用」或「添加到主屏幕」。',
    orderStatusLabel: '状态',
    orderStatusAwaitingPayment: '待付款',
    orderStatusPaymentChecking: '核对付款中',
    orderStatusPaidVerified: '已付款',
    orderStatusPendingManualReview: '待确认',
    orderStatusCancelled: '已取消',
    orderShippingStatusLabel: '配送',
    orderShippingPending: '待处理',
    orderShippingConfirmed: '已确认',
    orderShippingPacking: '打包中',
    orderShippingShipping: '配送中',
    orderShippingDelivered: '已送达',
    orderShippingReturned: '已退货',
    orderShippingCancelled: '配送取消',
    orderDateLabel: '下单日期',
    orderViewPayment: '查看付款 QR',
    orderHidePayment: '隐藏付款',
    orderQuantityLabel: '数量',
    recentlyViewedClear: '清除记录',
    recentlyViewedCleared: '浏览记录已清除。',
    addressesEmptyHint: '暂无地址。点击“添加地址”添加。',
    addressAdd: '+ 添加地址',
    addressEdit: '编辑',
    addressDelete: '删除',
    addressDeleteConfirm: '删除地址',
    addressDeleteConfirmBody: '确定要删除此地址吗？',
    addressCancel: '取消',
    addressSave: '保存地址',
    addressSetDefault: '设为默认',
    addressDefaultBadge: '默认',
    addressFullName: '姓名',
    addressPhone: '手机号码',
    addressProvince: '省 / 市',
    addressProvincePlaceholder: '— 选择省/市 —',
    addressDistrict: '区 / 县',
    addressWard: '街道 / 乡',
    addressStreet: '详细地址',
    addressStreetPlaceholder: '门牌、街道、村组…',
    addressMakeDefault: '设为默认地址',
    addressManageBook: '管理地址簿',
    addressCartTitle: '收货地址',
    addressCartEmpty: '暂无地址。请先添加收货地址再结算。',
    addressCartAddHint: '+ 添加新地址',
    addressFormTitleAdd: '添加新地址',
    addressFormTitleEdit: '编辑地址',
    addressDeleted: '已删除地址',
    addressSaveBook: '保存到地址簿',
    addressCartModalTitle: '添加收货地址',
    reviewsTitle: '商品评价',
    reviewsTotalSuffix: '条评价',
    reviewsWriteButton: '写评价',
    reviewsFormRatingLabel: '选择星级',
    reviewsFormContentPlaceholder: '分享您对该商品的感受...',
    reviewsFormImagesLabel: '添加图片（可选）',
    reviewsFormSubmit: '提交评价',
    reviewsFormCancel: '取消',
    reviewsSubmitSuccess: '感谢您的评价！',
    reviewsSubmitLoginRequired: '请登录后再评价商品。',
    reviewsSubmitAlreadyReviewed: '您已经评价过该商品。',
    reviewsSubmitNotEligible: '只有收到商品的客户才能评价。',
    reviewsEmpty: '暂无评价 — 快来抢沙发！',
    reviewsLoadMore: '查看更多评价',
    reviewsUsefulLabel: '有用',
    reviewsMerchantReplyPrefix: '来自',
    qaTitle: '商品问答',
    qaAskButton: '提问',
    qaFormPlaceholder: '您想了解这款商品的什么信息？',
    qaFormSubmit: '提交问题',
    qaSubmitSuccess: '您的问题已提交！',
    qaSubmitLoginRequired: '请登录后再提问。',
    qaEmpty: '暂无问题 — 快来提第一个问题！',
    qaLoadMore: '查看更多问题',
    qaAnswerButton: '回答',
    qaAnswerFormPlaceholder: '分享您的回答...',
    qaAnswerSubmit: '提交回答',
    qaAnswerNotEligible: '只有购买过该商品的客户才能回答。',
    qaAnswerSlotFull: '该问题的公开回答名额已满。',
    qaVerifiedBadge: '已购买',
    qaAdminBadge: '店主',
    qaNoAnswersYet: '暂无回答。',
    footerColShop: '店铺',
    footerColShopping: '购物',
    footerColSupport: '客户支持',
    footerColLegal: '政策',
    footerBrandHint: '在线购物 — 描述相符，全国配送。',
    footerCopyright: '© {year} {shop}。保留所有权利。',
    footerPaymentHint: '支付：货到付款 · 银行转账',
    lpExploreProducts: '探索商品',
    lpViewProducts: '查看商品',
    lpSuggestedForYou: '为你推荐',
    homeYouMayLike: '猜你喜欢',
    forYouBadge: '为你',
    lpHighlightsHeading: '亮点与购买理由',
    lpFaqHeading: '常见问题',
    lpRealReviews: '{rating}/5 · {count} 条真实评价',
    lpViewFullCategory: '查看全部分类 →',
    lpMaterialChip: '材质：{name}',
    lpTrust1: '精选好物',
    lpTrust2: '下单便捷',
    lpTrust3: '随时支持',
  },
  ja: {
    navHome: 'ホーム',
    navProducts: '商品',
    navRecentlyViewed: '最近見た',
    navFavorites: 'お気に入り',
    navRecommended: 'おすすめ',
    navCart: 'カート',
    navChat: 'チャット',
    navChatZalo: 'Zaloチャット',
    navChatFacebook: 'Facebookチャット',
    navChatWhatsapp: 'WhatsAppチャット',
    navTopUp: 'ページ先頭',
    navCategories: 'カテゴリ',
    catalogTitle: 'すべての商品',
    categorySeoBodyAriaLabel: 'カテゴリー紹介',
    categorySubcategoriesLabel: 'サブカテゴリー',
    categoryFilterMinPrice: '最低価格',
    categoryFilterMaxPrice: '最高価格',
    categoryFilterApply: '適用',
    categoryFilterClear: 'フィルターを解除',
    categorySortLabel: '並び替え',
    categorySortNewest: '新着順',
    categorySortRandom: 'ランダム',
    categorySortOldest: '古い順',
    categorySortViews: '閲覧が多い順',
    categorySortPriceAsc: '価格が安い順',
    categorySortPriceDesc: '価格が高い順',
    categoryFilterSize: 'サイズ',
    categoryFilterColor: 'カラー',
    categoryFilterAllSizes: 'すべてのサイズ',
    categoryFilterAllColors: 'すべてのカラー',
    categoryMegaHint: 'カテゴリにマウスを置くと2階層・3階層が表示されます。',
    khoSaleNavLabel: '倉庫セール',
    khoSaleNavBlurb: '返品・倉庫清算品 — 特価、数量限定。',
    khoSaleViewAll: 'すべて見る →',
    khoSalePageTitle: '倉庫セール',
    categorySeoRowAria: 'サイズSEO',
    categoryExpand: '下のカテゴリを開く',
    categoryCollapse: '下のカテゴリを閉じる',
    categoryHubTitle: '商品カテゴリ',
    categoryHubEmpty: '表示できるカテゴリがありません。',
    categoryPagePrev: '前へ',
    categoryPageNext: '次へ',
    categoryFiltersAria: '商品フィルター',
    catalogEmpty: '商品がありません。',
    loadMore: 'もっと見る',
    productDetail: '商品詳細',
    addToCart: 'カートに追加',
    buyNow: '今すぐ購入',
    addedToCart: 'カートに追加しました。',
    cartAddedTitle: 'カートに追加しました',
    cartGoToCart: 'カートを見る',
    cartContinueShopping: '買い物を続ける',
    cartAddedClose: '閉じる',
    lowStockUrgency: '残り{n}点 — お早めにご注文ください！',
    galleryZoomHint: 'タップで拡大、スワイプで他の写真を表示',
    lightboxClose: '閉じる',
    lightboxPrev: '前の写真',
    lightboxNext: '次の写真',
    consultChat: 'チャット相談',
    cartTitle: 'ショッピングカート',
    cartEmpty: 'カートは空です。',
    cartSubtotal: '小計',
    cartCheckout: 'レジに進む',
    cartCheckingOut: '注文処理中…',
    cartRemove: '削除',
    cartPromoLabel: 'プロモコード',
    cartPromoPlaceholder: 'プロモコードを入力',
    cartPromoApply: '適用',
    cartPromoApplying: '確認中...',
    cartPromoRemove: 'コードを削除',
    cartPromoDiscountLabel: '割引',
    cartTotalLabel: '合計',
    cartShippingFeeLabel: '送料',
    cartShippingFeeFree: '送料無料',
    cartShippingFeeIncluded: '送料込み',
    cartShippingFreeThresholdHint: '{amount}以上のご購入で送料無料',
    checkoutPaymentMethodLabel: 'お支払い方法',
    checkoutPaymentMethodBank: '銀行振込',
    checkoutPaymentMethodEwallet: '電子マネー',
    checkoutPaymentMethodHint: '前払い金額がある場合に適用されます。残額は商品受け取り時にお支払いください。',
    orderConfirmEwalletTitle: '電子マネーでのお支払い',
    orderConfirmEwalletHint: '電子マネーアプリでQRコードを読み取り、正確な金額を入力してから、下記に支払い画面のスクリーンショットを送信してください。',
    promoErrorNotFound: 'プロモコードが見つかりません。',
    promoErrorInactive: 'このプロモコードは無効です。',
    promoErrorNotStarted: 'このプロモコードはまだ有効ではありません。',
    promoErrorExpired: 'このプロモコードは期限切れです。',
    promoErrorBelowMinSubtotal: 'ご注文の金額がこのコードの最低金額に達していません。',
    promoErrorUsageLimitReached: 'このプロモコードは使用回数の上限に達しました。',
    promoErrorPerUserLimitReached: 'このコードの使用回数上限に達しました。',
    promoErrorFirstOrderOnly: 'このコードは初回注文のみ有効です。',
    promoErrorNoEligibleItems: 'カート内にこのコードの対象商品がありません。',
    promoErrorGrantRequired: 'このコードはウォレットに付与された場合のみ使用できます。',
    promoErrorGeneric: 'このプロモコードは適用できません。',
    checkoutName: '氏名',
    checkoutPhone: '電話番号',
    checkoutAddress: '配送先',
    checkoutNote: 'メモ',
    checkoutSuccess: '注文を受け付けました — ショップから連絡があります。',
    checkoutAuthRequired: '続行するにはログインしてください。',
    checkoutGuestHint: 'ログイン不要で注文できます — 配送情報を入力してください。',
    checkoutAuthLink: 'ショップチャットでログイン/認証',
    quantity: '数量',
    backToShop: '買い物を続ける',
    navOrders: '注文',
    sizeLabel: 'サイズ',
    colorLabel: '色',
    sizeGuideButton: 'サイズガイド',
    sizeGuideModalTitle: 'サイズ表',
    sizeGuideFallbackLink: 'サイズガイドを見る',
    sizeGuideClose: '閉じる',
    contactChannelsAria: 'クイック連絡',
    contactChannelPhone: '電話',
    contactChannelZalo: 'Zalo',
    contactChannelMessenger: 'Messenger',
    contactChannelInstagram: 'Instagram',
    flashSaleBadge: 'フラッシュセール',
    flashSaleEndsIn: '終了まで',
    shippingCarrierLabel: '配送業者',
    searchPlaceholder: '商品を検索…',
    searchButton: '検索',
    searchByImage: '画像で検索',
    searchSearching: '検索中…',
    searchResults: '検索結果',
    searchEmpty: '該当する商品がありません。',
    searchError: '検索に失敗しました。',
    relatedProducts: '類似商品',
    relatedSeeAll: 'すべて見る',
    relatedEmpty: 'このカテゴリに他の商品はありません。',
    outfitTitleFallback: 'このアイテムに合うコーディネート',
    outfitSubtitle: '別カテゴリで合わせる',
    outfitSlotsAria: 'コーディネートグループ',
    outfitEmpty: 'この商品のコーディネート提案はまだありません。',
    outfitError: 'コーディネートを読み込めませんでした。',
    outfitSeeAll: 'すべて見る',
    tryOnLink: 'AI試着',
    favoriteProduct: '商品をお気に入り',
    skuLabel: '商品コード',
    pdpRatingLabel: 'レビュー',
    pdpLineTotal: '合計',
    pdpSavings: '{amount} お得',
    pdpQtyBuy: '数量',
    pdpShippingNote: '全国配送。{free}不良品・説明と異なる場合は7日以内に返品できます。',
    pdpShippingFreeFrom: '{amount}以上で送料無料。 ',
    pdpShippingPolicyLink: '配送ポリシー',
    pdpReturnsPolicyLink: '返品ポリシー',
    pdpServiceLabel: 'サービス',
    pdpServiceNote: '代金引換、サイズ交換、受取前の確認が可能です。',
    pdpNotesTitle: 'ご注意',
    pdpNoteFit: '実寸は記載と多少異なる場合があります。',
    pdpNoteColor: '光や端末により、実物の色が画像と異なる場合があります。',
    pdpStickyHome: 'ホーム',
    pdpStickyHomeL1: 'ホーム',
    pdpStickyHomeL2: '',
    pdpStickyTryOnL1: '試着',
    pdpStickyTryOnL2: '',
    pdpStickyLikeLabel: 'いいね',
    pdpAddToCartShort: 'カートへ',
    pdpBuyNowShort: '購入する',
    pdpShareCopy: 'リンクをコピー',
    pdpShareCopied: 'コピーしました',
    pdpJumpReviews: 'レビューを見る',
    pdpJumpQa: 'Q&A',
    pdpBrandLabel: 'ブランド',
    pdpOriginLabel: '原産地',
    pdpMaterialLabel: '素材',
    pdpStyleLabel: 'スタイル',
    pdpOccasionLabel: 'シーン',
    pdpWeightLabel: '重量',
    pdpFeaturesLabel: '特徴',
    pdpCategoryLabel: 'カテゴリ',
    pdpPurchasesLabel: '販売',
    pdpLikesLabel: 'いいね',
    pdpRatingCountSuffix: '件',
    pdpDescTab: '商品説明',
    pdpSpecsTab: '商品情報',
    pdpDetailImagesHeading: '詳細画像',
    pdpSpecsEmpty: '商品情報はまだありません。',
    pdpYes: 'はい',
    pdpNo: 'いいえ',
    ordersTitle: '注文履歴',
    ordersEmpty: '注文はまだありません。',
    thankYouOrderLabel: '注文ID',
    thankYouTrackCta: '注文を追跡',
    ordersFilterAriaLabel: '注文ステータスで絞り込み',
    ordersFilterAll: 'すべて',
    ordersFilterWaitingPayment: '支払い待ち',
    ordersFilterProcessing: '受け取り待ち',
    ordersFilterDelivered: '受け取り済み',
    ordersFilterReviewed: 'レビュー済み',
    ordersFilterCancelled: 'キャンセル',
    ordersFilterReturned: '返品',
    ordersFilterEmpty: 'このステータスの注文はありません。',
    orderTrack: '注文を追跡',
    orderHideTrack: '進捗を隠す',
    orderConfirmReceived: '受け取りました',
    orderConfirmReceivedHint: '商品をすべて受け取ったことを確認します。その後レビューできます。',
    orderConfirmReceivedOk: '受け取りを確認しました。',
    orderCancel: '注文をキャンセル',
    orderCancelHint: '支払い確認前、または発送前のみキャンセルできます。',
    orderCancelOk: '注文をキャンセルしました。',
    orderCancelReason: 'キャンセル理由（任意）',
    orderReview: 'レビュー',
    orderDetail: '注文詳細',
    orderHideDetail: '詳細を隠す',
    orderTimelineTitle: '注文の進捗',
    orderTimelineCreated: '注文済み',
    orderTimelineConfirmed: 'ショップ確認済み',
    orderTimelinePacking: '梱包中',
    orderTimelineShipping: '配送中',
    orderTimelineDelivered: '受け取り済み',
    orderActionFailed: '操作できませんでした。再試行してください。',
    orderAddressLabel: 'お届け先',
    authSendOtp: 'OTP送信',
    authVerifyOtp: '確認',
    authSuccess: 'メール確認済み — 決済できます。',
    authFailed: '確認に失敗しました。',
    authOtpSent: 'OTPをメールに送信しました。',
    authEmailLogin: 'メールでログイン',
    authChangeEmail: '別のメールを使う',
    authEmailRequired: 'メールアドレスを入力してください。',
    authGoogleLogin: 'Googleでログイン',
    authShopOtpOr: 'またはメールでコードを受け取る',
    authLoginSubtitle: 'Google またはメール OTP',
    authLoginTitle: 'ログイン',
    authLoginWelcome: 'おかえりなさい',
    authQuickLoginFailed: 'ログインできません — 下のメール OTP をお試しください。',
    authNanoAiLoginHint: 'メールアドレスを入力 — OTPコードをメールで受け取ります。',
    authRememberDevice: 'この端末でログイン状態を保持（次回 OTP 省略の場合あり）。',
    orderIdLabel: '注文ID',
    depositAmount: 'デポジット',
    paymentReference: '振込参照',
    depositPolicyNote: 'ショップ設定に従いデポジットをお支払いください。',
    productDescriptionTitle: '商品説明',
    productDetailImagesTitle: '詳細画像',
    productVideoTitle: '商品動画',
    pdpConsultNoteTitle: 'スタイリストメモ',
    pdpMaterialImagesTitle: '素材写真',
    pdpRealUseImagesTitle: '着用写真',
    favoriteAdd: 'お気に入りに追加',
    favoriteRemove: 'お気に入りから削除',
    wishlistTitle: 'お気に入り',
    wishlistEmpty: 'お気に入りはまだありません。',
    recentlyViewedTitle: '最近見た商品',
    recentlyViewedEmpty: '閲覧履歴はありません。',
    chatOpenLabel: 'チャットを開く',
    chatCloseLabel: '閉じる',
    chatFullPageLabel: '全画面で開く',
    chatLanguageLabel: '言語',
    consentMessage: '当サイトは、ショッピング体験の向上と広告効果測定のためにCookieを使用しています。',
    consentAccept: '同意する',
    consentReject: '拒否する',
    navAccount: 'アカウント',
    navLogout: 'ログアウト',
    navRegister: '登録',
    leadFormTitle: '最新情報を受け取る',
    navWallet: 'マイクーポン',
    walletTitle: 'あなたのクーポン',
    walletHint: 'コードをコピーしてカートのプロモコード欄に貼り付けてください。',
    walletEmpty: 'まだクーポンはありません。',
    walletCopyCode: 'コードをコピー',
    walletCodeCopied: 'コードをコピーしました！',
    walletExpiresLabel: '有効期限',
    walletMinSubtotalNote: '対象注文金額',
    accountEditProfile: 'プロフィール編集',
    accountViewedProducts: '閲覧履歴',
    accountAddressBook: '住所録',
    accountEmailLabel: 'メール',
    accountSave: '変更を保存',
    accountSaved: 'プロフィールを保存しました。',
    accountSaveFailed: '保存できませんでした。もう一度お試しください。',
    addressesHint: '複数の配送先を管理します。決済時は既定の住所を使います。',
    accountWelcome: 'こんにちは',
    accountQuickLinks: 'クイックリンク',
    accountOpenShopAdmin: '店舗管理ページを開く',
    accountOpenShopAdminHint: 'この Gmail は店舗管理者に招待されています。管理ページをすぐ開けます。',
    accountSectionEditProfile: 'プロフィール編集',
    accountSecurity: 'セキュリティ',
    accountSecurityTitle: 'アカウントのセキュリティ',
    accountSecurityLoginNote: 'メール OTP または Google でログイン — パスワードは使いません。',
    accountSignOutDevice: 'この端末からサインアウト',
    accountSignOutDone: 'この端末からサインアウトしました。',
    accountSecurityReAuth: '再ログイン',
    accountNotifications: '通知',
    accountNotificationsTitle: '通知センター',
    accountNotificationsEmpty: '通知はまだありません。',
    accountNotificationsMarkAllRead: 'すべて既読にする',
    accountNotificationsLogin: '通知を見るにはログインしてください。',
    accountNotificationsLoading: '通知を読み込み中...',
    accountNotificationsSignIn: '今すぐログイン',
    pushEnableTitle: 'ブラウザ通知',
    pushEnableHint: 'このページを閉じていても、注文やショップのお知らせを受け取れます。',
    pushEnableButton: 'プッシュ通知をオンにする',
    pushEnabled: 'この端末でプッシュ通知がオンです。',
    pushDenied: '通知がブロックされています。サイト設定で許可してください。',
    pushUnsupported: 'このブラウザはプッシュ通知に対応していません。',
    pushIosHint: 'iPhone/iPad：ホーム画面に追加してから、アプリ内で通知をオンにしてください。',
    pushSyncing: 'オンにしています…',
    accountInstallApp: 'アプリをインストール',
    accountInstallAppTitle: 'アプリをインストール',
    accountInstallAppHint: 'ホーム画面に追加すると、アプリのようにすぐ開けます。',
    accountInstallAppButton: 'インストール',
    accountInstallAppIosTip: 'iPhone/iPad：共有 →「ホーム画面に追加」。',
    accountInstallAppInstalled: 'この端末にはすでにインストール済みです。',
    accountInstallAppManualTip: 'ブラウザのメニューから「アプリをインストール」または「ホーム画面に追加」を選んでください。',
    orderStatusLabel: 'ステータス',
    orderStatusAwaitingPayment: '支払い待ち',
    orderStatusPaymentChecking: '支払い確認中',
    orderStatusPaidVerified: '支払い済み',
    orderStatusPendingManualReview: '確認待ち',
    orderStatusCancelled: 'キャンセル',
    orderShippingStatusLabel: '配送',
    orderShippingPending: '処理待ち',
    orderShippingConfirmed: '確認済み',
    orderShippingPacking: '梱包中',
    orderShippingShipping: '配送中',
    orderShippingDelivered: '配達完了',
    orderShippingReturned: '返品',
    orderShippingCancelled: '配送キャンセル',
    orderDateLabel: '注文日',
    orderViewPayment: 'QR / 支払いを見る',
    orderHidePayment: '支払いを隠す',
    orderQuantityLabel: '数量',
    recentlyViewedClear: '履歴を削除',
    recentlyViewedCleared: '閲覧履歴を削除しました。',
    addressesEmptyHint: '住所がありません。「住所を追加」を押してください。',
    addressAdd: '+ 住所を追加',
    addressEdit: '編集',
    addressDelete: '削除',
    addressDeleteConfirm: '住所を削除',
    addressDeleteConfirmBody: 'この住所を削除しますか？',
    addressCancel: 'キャンセル',
    addressSave: '住所を保存',
    addressSetDefault: '既定にする',
    addressDefaultBadge: '既定',
    addressFullName: '氏名',
    addressPhone: '電話番号',
    addressProvince: '都道府県 / 市',
    addressProvincePlaceholder: '— 都道府県/市を選択 —',
    addressDistrict: '区 / 郡',
    addressWard: '町 / 村',
    addressStreet: '番地',
    addressStreetPlaceholder: '番地、通り、集落…',
    addressMakeDefault: '既定の住所にする',
    addressManageBook: '住所録を管理',
    addressCartTitle: '配送先',
    addressCartEmpty: '住所がありません。決済前に追加してください。',
    addressCartAddHint: '+ 新しい住所を追加',
    addressFormTitleAdd: '新しい住所を追加',
    addressFormTitleEdit: '住所を編集',
    addressDeleted: '住所を削除しました',
    addressSaveBook: '住所録に保存',
    addressCartModalTitle: '配送先を追加',
    reviewsTitle: '商品レビュー',
    reviewsTotalSuffix: '件のレビュー',
    reviewsWriteButton: 'レビューを書く',
    reviewsFormRatingLabel: '評価を選択',
    reviewsFormContentPlaceholder: 'この商品についての感想をシェアしてください...',
    reviewsFormImagesLabel: '写真を追加（任意）',
    reviewsFormSubmit: 'レビューを送信',
    reviewsFormCancel: 'キャンセル',
    reviewsSubmitSuccess: 'レビューありがとうございます！',
    reviewsSubmitLoginRequired: 'レビューを投稿するにはログインしてください。',
    reviewsSubmitAlreadyReviewed: 'この商品はすでにレビュー済みです。',
    reviewsSubmitNotEligible: '商品を受け取ったお客様のみレビューできます。',
    reviewsEmpty: 'まだレビューがありません — 最初のレビューを書いてみましょう！',
    reviewsLoadMore: 'レビューをもっと見る',
    reviewsUsefulLabel: '参考になった',
    reviewsMerchantReplyPrefix: '返信元:',
    qaTitle: '商品Q&A',
    qaAskButton: '質問する',
    qaFormPlaceholder: 'この商品について知りたいことは？',
    qaFormSubmit: '質問を送信',
    qaSubmitSuccess: '質問を送信しました！',
    qaSubmitLoginRequired: '質問するにはログインしてください。',
    qaEmpty: 'まだ質問がありません — 最初の質問をしてみましょう！',
    qaLoadMore: '質問をもっと見る',
    qaAnswerButton: '回答する',
    qaAnswerFormPlaceholder: 'あなたの回答をシェアしてください...',
    qaAnswerSubmit: '回答を送信',
    qaAnswerNotEligible: 'この商品を購入したお客様のみ回答できます。',
    qaAnswerSlotFull: 'この質問はすでに公開回答の上限に達しています。',
    qaVerifiedBadge: '購入者',
    qaAdminBadge: 'ショップオーナー',
    qaNoAnswersYet: 'まだ回答がありません。',
    footerColShop: 'ショップ',
    footerColShopping: 'ショッピング',
    footerColSupport: 'カスタマーサポート',
    footerColLegal: 'ポリシー',
    footerBrandHint: 'オンラインショップ — 記載どおりの商品、全国配送。',
    footerCopyright: '© {year} {shop}. 無断転載を禁じます。',
    footerPaymentHint: '支払い：代金引換 · 銀行振込',
    lpExploreProducts: '商品を見る',
    lpViewProducts: '商品を見る',
    lpSuggestedForYou: 'あなたへのおすすめ',
    homeYouMayLike: 'あなたへのおすすめ',
    forYouBadge: 'おすすめ',
    lpHighlightsHeading: '注目ポイント',
    lpFaqHeading: 'よくある質問',
    lpRealReviews: '{rating}/5 · 本物のレビュー {count}件',
    lpViewFullCategory: 'カテゴリをすべて見る →',
    lpMaterialChip: '素材：{name}',
    lpTrust1: '厳選した商品',
    lpTrust2: 'かんたん注文',
    lpTrust3: '必要なときにサポート',
  },
  ko: {
    navHome: '홈',
    navProducts: '상품',
    navRecentlyViewed: '최근 본',
    navFavorites: '찜',
    navRecommended: '추천',
    navCart: '장바구니',
    navChat: '채팅',
    navChatZalo: 'Zalo 채팅',
    navChatFacebook: 'Facebook 채팅',
    navChatWhatsapp: 'WhatsApp 채팅',
    navTopUp: '맨 위로',
    navCategories: '카테고리',
    catalogTitle: '전체 상품',
    categorySeoBodyAriaLabel: '카테고리 소개',
    categorySubcategoriesLabel: '하위 카테고리',
    categoryFilterMinPrice: '최소 가격',
    categoryFilterMaxPrice: '최대 가격',
    categoryFilterApply: '적용',
    categoryFilterClear: '필터 지우기',
    categorySortLabel: '정렬',
    categorySortNewest: '최신순',
    categorySortRandom: '무작위',
    categorySortOldest: '오래된순',
    categorySortViews: '많이 본순',
    categorySortPriceAsc: '가격 낮은순',
    categorySortPriceDesc: '가격 높은순',
    categoryFilterSize: '사이즈',
    categoryFilterColor: '색상',
    categoryFilterAllSizes: '모든 사이즈',
    categoryFilterAllColors: '모든 색상',
    categoryMegaHint: '카테고리에 마우스를 올리면 2·3단계를 봅니다.',
    khoSaleNavLabel: '창고 세일',
    khoSaleNavBlurb: '반품·창고 정리 재고 — 특가, 수량 한정.',
    khoSaleViewAll: '모두 보기 →',
    khoSalePageTitle: '창고 세일',
    categorySeoRowAria: '사이즈 SEO',
    categoryExpand: '하위 카테고리 열기',
    categoryCollapse: '하위 카테고리 접기',
    categoryHubTitle: '상품 카테고리',
    categoryHubEmpty: '표시할 카테고리가 없습니다.',
    categoryPagePrev: '이전',
    categoryPageNext: '다음',
    categoryFiltersAria: '상품 필터',
    catalogEmpty: '상품이 없습니다.',
    loadMore: '더 보기',
    productDetail: '상품 상세',
    addToCart: '장바구니 담기',
    buyNow: '바로 구매',
    addedToCart: '장바구니에 담았습니다.',
    cartAddedTitle: '장바구니에 담았습니다',
    cartGoToCart: '장바구니 보기',
    cartContinueShopping: '계속 쇼핑',
    cartAddedClose: '닫기',
    lowStockUrgency: '재고 {n}개 남음 — 서둘러 주문하세요!',
    galleryZoomHint: '탭하여 확대, 스와이프하여 다른 사진 보기',
    lightboxClose: '닫기',
    lightboxPrev: '이전 사진',
    lightboxNext: '다음 사진',
    consultChat: '채팅 상담',
    cartTitle: '장바구니',
    cartEmpty: '장바구니가 비었습니다.',
    cartSubtotal: '소계',
    cartCheckout: '결제',
    cartCheckingOut: '주문 처리 중…',
    cartRemove: '삭제',
    cartPromoLabel: '할인 코드',
    cartPromoPlaceholder: '할인 코드 입력',
    cartPromoApply: '적용',
    cartPromoApplying: '확인 중...',
    cartPromoRemove: '코드 제거',
    cartPromoDiscountLabel: '할인',
    cartTotalLabel: '총액',
    cartShippingFeeLabel: '배송비',
    cartShippingFeeFree: '무료 배송',
    cartShippingFeeIncluded: '배송비 포함',
    cartShippingFreeThresholdHint: '{amount} 이상 구매 시 무료 배송',
    checkoutPaymentMethodLabel: '결제 방법',
    checkoutPaymentMethodBank: '계좌 이체',
    checkoutPaymentMethodEwallet: '전자지갑',
    checkoutPaymentMethodHint: '선결제 금액(있는 경우)에 적용되며, 나머지는 수령 시 결제합니다.',
    orderConfirmEwalletTitle: '전자지갑으로 결제',
    orderConfirmEwalletHint: '전자지갑 앱으로 QR 코드를 스캔하고 정확한 금액을 입력한 후, 아래에 결제 화면 캡처를 보내주세요.',
    promoErrorNotFound: '할인 코드를 찾을 수 없습니다.',
    promoErrorInactive: '이 할인 코드는 더 이상 유효하지 않습니다.',
    promoErrorNotStarted: '이 할인 코드는 아직 사용할 수 없습니다.',
    promoErrorExpired: '이 할인 코드는 만료되었습니다.',
    promoErrorBelowMinSubtotal: '주문 금액이 이 코드의 최소 금액에 도달하지 않았습니다.',
    promoErrorUsageLimitReached: '이 할인 코드의 사용 한도에 도달했습니다.',
    promoErrorPerUserLimitReached: '이 코드의 최대 사용 횟수에 도달했습니다.',
    promoErrorFirstOrderOnly: '이 코드는 첫 주문에만 적용됩니다.',
    promoErrorNoEligibleItems: '장바구니에 이 코드에 해당하는 상품이 없습니다.',
    promoErrorGrantRequired: '이 코드는 지갑으로 지급된 경우에만 사용할 수 있습니다.',
    promoErrorGeneric: '이 할인 코드를 적용할 수 없습니다.',
    checkoutName: '이름',
    checkoutPhone: '전화번호',
    checkoutAddress: '배송 주소',
    checkoutNote: '메모',
    checkoutSuccess: '주문이 접수되었습니다 — 곧 연락드립니다.',
    checkoutAuthRequired: '계속하려면 로그인해 주세요.',
    checkoutGuestHint: '로그인 없이 주문할 수 있습니다 — 배송 정보만 입력하세요.',
    checkoutAuthLink: '샵 채팅에서 로그인/인증',
    quantity: '수량',
    backToShop: '쇼핑 계속',
    navOrders: '주문',
    sizeLabel: '사이즈',
    colorLabel: '색상',
    sizeGuideButton: '사이즈 가이드',
    sizeGuideModalTitle: '사이즈표',
    sizeGuideFallbackLink: '사이즈 가이드 보기',
    sizeGuideClose: '닫기',
    contactChannelsAria: '빠른 연락',
    contactChannelPhone: '전화',
    contactChannelZalo: 'Zalo',
    contactChannelMessenger: 'Messenger',
    contactChannelInstagram: 'Instagram',
    flashSaleBadge: '플래시 세일',
    flashSaleEndsIn: '종료까지',
    shippingCarrierLabel: '배송사',
    searchPlaceholder: '상품 검색…',
    searchButton: '검색',
    searchByImage: '이미지로 검색',
    searchSearching: '검색 중…',
    searchResults: '검색 결과',
    searchEmpty: '일치하는 상품이 없습니다.',
    searchError: '검색에 실패했습니다.',
    relatedProducts: '유사 상품',
    relatedSeeAll: '전체 보기',
    relatedEmpty: '이 카테고리에 다른 상품이 없습니다.',
    outfitTitleFallback: '이 상품과 코디하기',
    outfitSubtitle: '다른 종류와 함께 입기',
    outfitSlotsAria: '코디 그룹',
    outfitEmpty: '이 상품의 코디 제안이 아직 없습니다.',
    outfitError: '코디 제안을 불러오지 못했습니다.',
    outfitSeeAll: '전체 보기',
    tryOnLink: 'AI 피팅',
    favoriteProduct: '상품 찜',
    skuLabel: '상품코드',
    pdpRatingLabel: '리뷰',
    pdpLineTotal: '합계',
    pdpSavings: '{amount} 절약',
    pdpQtyBuy: '구매 수량',
    pdpShippingNote: '전국 배송. {free}불량 또는 설명과 다를 경우 7일 이내 반품 가능.',
    pdpShippingFreeFrom: '{amount} 이상 무료 배송. ',
    pdpShippingPolicyLink: '배송 정책',
    pdpReturnsPolicyLink: '반품 정책',
    pdpServiceLabel: '서비스',
    pdpServiceNote: '착불 결제, 사이즈 교환, 수령 전 확인 가능.',
    pdpNotesTitle: '안내',
    pdpNoteFit: '실제 치수는 설명과 약간 다를 수 있습니다.',
    pdpNoteColor: '조명과 기기에 따라 실제 색상이 사진과 다를 수 있습니다.',
    pdpStickyHome: '홈',
    pdpStickyHomeL1: '홈',
    pdpStickyHomeL2: '',
    pdpStickyTryOnL1: '피팅',
    pdpStickyTryOnL2: '',
    pdpStickyLikeLabel: '좋아요',
    pdpAddToCartShort: '장바구니',
    pdpBuyNowShort: '구매하기',
    pdpShareCopy: '링크 복사',
    pdpShareCopied: '복사됨',
    pdpJumpReviews: '리뷰 보기',
    pdpJumpQa: 'QnA',
    pdpBrandLabel: '브랜드',
    pdpOriginLabel: '원산지',
    pdpMaterialLabel: '소재',
    pdpStyleLabel: '스타일',
    pdpOccasionLabel: '상황',
    pdpWeightLabel: '무게',
    pdpFeaturesLabel: '특징',
    pdpCategoryLabel: '카테고리',
    pdpPurchasesLabel: '판매',
    pdpLikesLabel: '좋아요',
    pdpRatingCountSuffix: '건',
    pdpDescTab: '상품 설명',
    pdpSpecsTab: '상품 정보',
    pdpDetailImagesHeading: '상세 이미지',
    pdpSpecsEmpty: '상품 정보가 아직 없습니다.',
    pdpYes: '예',
    pdpNo: '아니요',
    ordersTitle: '내 주문',
    ordersEmpty: '주문이 없습니다.',
    thankYouOrderLabel: '주문 번호',
    thankYouTrackCta: '주문 조회',
    ordersFilterAriaLabel: '주문 상태별 필터',
    ordersFilterAll: '전체',
    ordersFilterWaitingPayment: '결제 대기',
    ordersFilterProcessing: '수령 대기',
    ordersFilterDelivered: '수령 완료',
    ordersFilterReviewed: '리뷰 완료',
    ordersFilterCancelled: '취소됨',
    ordersFilterReturned: '반품',
    ordersFilterEmpty: '이 상태의 주문이 없습니다.',
    orderTrack: '주문 추적',
    orderHideTrack: '진행 숨기기',
    orderConfirmReceived: '수령했습니다',
    orderConfirmReceivedHint: '상품을 모두 받았는지 확인합니다. 이후 리뷰를 남길 수 있습니다.',
    orderConfirmReceivedOk: '수령을 확인했습니다.',
    orderCancel: '주문 취소',
    orderCancelHint: '결제 확인 전 또는 발송 전에만 취소할 수 있습니다.',
    orderCancelOk: '주문을 취소했습니다.',
    orderCancelReason: '취소 사유 (선택)',
    orderReview: '리뷰',
    orderDetail: '주문 상세',
    orderHideDetail: '상세 숨기기',
    orderTimelineTitle: '주문 진행',
    orderTimelineCreated: '주문 완료',
    orderTimelineConfirmed: '샵 확인',
    orderTimelinePacking: '포장 중',
    orderTimelineShipping: '배송 중',
    orderTimelineDelivered: '수령 완료',
    orderActionFailed: '처리할 수 없습니다. 다시 시도하세요.',
    orderAddressLabel: '배송 주소',
    authSendOtp: 'OTP 전송',
    authVerifyOtp: '인증',
    authSuccess: '이메일 인증 완료 — 결제 가능합니다.',
    authFailed: '인증 실패. 다시 시도하세요.',
    authOtpSent: 'OTP가 이메일로 전송되었습니다.',
    authEmailLogin: '이메일로 로그인',
    authChangeEmail: '다른 이메일 사용',
    authEmailRequired: '이메일을 입력해 주세요.',
    authGoogleLogin: 'Google로 로그인',
    authShopOtpOr: '또는 이메일로 코드 받기',
    authLoginSubtitle: 'Google 또는 이메일 OTP',
    authLoginTitle: '로그인',
    authLoginWelcome: '다시 오신 것을 환영합니다',
    authQuickLoginFailed: '로그인할 수 없습니다 — 아래 이메일 OTP를 사용하세요.',
    authNanoAiLoginHint: '이메일 입력 — OTP 코드를 이메일로 받습니다.',
    authRememberDevice: '이 기기에 로그인 유지(다음에 OTP 생략될 수 있음).',
    orderIdLabel: '주문 ID',
    depositAmount: '보증금',
    paymentReference: '입금 참조',
    depositPolicyNote: '샵 설정에 따른 보증금 — QR 또는 참조번호로 입금.',
    productDescriptionTitle: '상품 설명',
    productDetailImagesTitle: '상세 이미지',
    productVideoTitle: '상품 영상',
    pdpConsultNoteTitle: '스타일 노트',
    pdpMaterialImagesTitle: '소재 사진',
    pdpRealUseImagesTitle: '실착 사진',
    favoriteAdd: '찜하기',
    favoriteRemove: '찜 해제',
    wishlistTitle: '찜',
    wishlistEmpty: '찜한 상품이 없습니다.',
    recentlyViewedTitle: '최근 본 상품',
    recentlyViewedEmpty: '최근 본 상품이 없습니다.',
    chatOpenLabel: '채팅 열기',
    chatCloseLabel: '닫기',
    chatFullPageLabel: '전체 페이지 열기',
    chatLanguageLabel: '언어',
    consentMessage: '이 사이트는 쇼핑 경험 개선과 광고 효과 측정을 위해 쿠키를 사용합니다.',
    consentAccept: '동의',
    consentReject: '거부',
    navAccount: '계정',
    navLogout: '로그아웃',
    navRegister: '가입',
    leadFormTitle: '소식 받기',
    navWallet: '내 쿠폰함',
    walletTitle: '내 쿠폰함',
    walletHint: '코드를 복사해 장바구니의 할인 코드란에 붙여넣으면 적용됩니다.',
    walletEmpty: '아직 쿠폰이 없습니다.',
    walletCopyCode: '코드 복사',
    walletCodeCopied: '코드가 복사되었습니다!',
    walletExpiresLabel: '만료일',
    walletMinSubtotalNote: '적용 최소 주문 금액',
    accountEditProfile: '프로필 수정',
    accountViewedProducts: '최근 본 상품',
    accountAddressBook: '주소록',
    accountEmailLabel: '이메일',
    accountSave: '변경 저장',
    accountSaved: '프로필이 저장되었습니다.',
    accountSaveFailed: '저장하지 못했습니다. 다시 시도하세요.',
    addressesHint: '여러 배송 주소를 관리합니다. 결제 시 기본 주소를 사용합니다.',
    accountWelcome: '안녕하세요',
    accountQuickLinks: '빠른 메뉴',
    accountOpenShopAdmin: '샵 관리 페이지 열기',
    accountOpenShopAdminHint: '이 Gmail은 샵 관리자로 초대되었습니다. 관리 페이지를 바로 여세요.',
    accountSectionEditProfile: '프로필 수정',
    accountSecurity: '보안',
    accountSecurityTitle: '계정 보안',
    accountSecurityLoginNote: '이메일 OTP 또는 Google로 로그인합니다 — 비밀번호는 사용하지 않습니다.',
    accountSignOutDevice: '이 기기에서 로그아웃',
    accountSignOutDone: '이 기기에서 로그아웃했습니다.',
    accountSecurityReAuth: '다시 로그인',
    accountNotifications: '알림',
    accountNotificationsTitle: '알림 센터',
    accountNotificationsEmpty: '알림이 없습니다.',
    accountNotificationsMarkAllRead: '모두 읽음으로 표시',
    accountNotificationsLogin: '알림을 보려면 로그인해 주세요.',
    accountNotificationsLoading: '알림을 불러오는 중...',
    accountNotificationsSignIn: '지금 로그인',
    pushEnableTitle: '브라우저 알림',
    pushEnableHint: '이 페이지를 닫아도 주문과 샵 알림을 받을 수 있습니다.',
    pushEnableButton: '푸시 알림 켜기',
    pushEnabled: '이 기기에서 푸시 알림이 켜져 있습니다.',
    pushDenied: '알림이 차단되었습니다. 브라우저 사이트 설정에서 허용하세요.',
    pushUnsupported: '이 브라우저는 푸시 알림을 지원하지 않습니다.',
    pushIosHint: 'iPhone/iPad: 홈 화면에 샵을 추가한 뒤 앱에서 알림을 켜세요.',
    pushSyncing: '켜는 중…',
    accountInstallApp: '앱 설치',
    accountInstallAppTitle: '앱 설치',
    accountInstallAppHint: '홈 화면에 추가하면 앱처럼 빠르게 열 수 있습니다.',
    accountInstallAppButton: '설치',
    accountInstallAppIosTip: 'iPhone/iPad: 공유 → «홈 화면에 추가».',
    accountInstallAppInstalled: '이 기기에 이미 설치되어 있습니다.',
    accountInstallAppManualTip: '브라우저 메뉴에서 «앱 설치» 또는 «홈 화면에 추가»를 선택하세요.',
    orderStatusLabel: '상태',
    orderStatusAwaitingPayment: '결제 대기',
    orderStatusPaymentChecking: '결제 확인 중',
    orderStatusPaidVerified: '결제 완료',
    orderStatusPendingManualReview: '확인 대기',
    orderStatusCancelled: '취소됨',
    orderShippingStatusLabel: '배송',
    orderShippingPending: '처리 대기',
    orderShippingConfirmed: '확인됨',
    orderShippingPacking: '포장 중',
    orderShippingShipping: '배송 중',
    orderShippingDelivered: '배송 완료',
    orderShippingReturned: '반품',
    orderShippingCancelled: '배송 취소',
    orderDateLabel: '주문일',
    orderViewPayment: 'QR / 결제 보기',
    orderHidePayment: '결제 숨기기',
    orderQuantityLabel: '수량',
    recentlyViewedClear: '기록 삭제',
    recentlyViewedCleared: '최근 본 기록을 삭제했습니다.',
    addressesEmptyHint: '주소가 없습니다. "주소 추가"를 누르세요.',
    addressAdd: '+ 주소 추가',
    addressEdit: '수정',
    addressDelete: '삭제',
    addressDeleteConfirm: '주소 삭제',
    addressDeleteConfirmBody: '이 주소를 삭제할까요?',
    addressCancel: '취소',
    addressSave: '주소 저장',
    addressSetDefault: '기본으로 설정',
    addressDefaultBadge: '기본',
    addressFullName: '이름',
    addressPhone: '전화번호',
    addressProvince: '시 / 도',
    addressProvincePlaceholder: '— 시/도 선택 —',
    addressDistrict: '구 / 군',
    addressWard: '동 / 읍',
    addressStreet: '상세 주소',
    addressStreetPlaceholder: '번지, 도로, 마을…',
    addressMakeDefault: '기본 주소로 설정',
    addressManageBook: '주소록 관리',
    addressCartTitle: '배송 주소',
    addressCartEmpty: '주소가 없습니다. 결제 전에 추가하세요.',
    addressCartAddHint: '+ 새 주소 추가',
    addressFormTitleAdd: '새 주소 추가',
    addressFormTitleEdit: '주소 수정',
    addressDeleted: '주소를 삭제했습니다',
    addressSaveBook: '주소록에 저장',
    addressCartModalTitle: '배송 주소 추가',
    reviewsTitle: '상품 리뷰',
    reviewsTotalSuffix: '개 리뷰',
    reviewsWriteButton: '리뷰 작성',
    reviewsFormRatingLabel: '별점 선택',
    reviewsFormContentPlaceholder: '이 상품에 대한 후기를 남겨주세요...',
    reviewsFormImagesLabel: '사진 추가 (선택)',
    reviewsFormSubmit: '리뷰 제출',
    reviewsFormCancel: '취소',
    reviewsSubmitSuccess: '리뷰를 남겨주셔서 감사합니다!',
    reviewsSubmitLoginRequired: '리뷰를 작성하려면 로그인해주세요.',
    reviewsSubmitAlreadyReviewed: '이미 이 상품에 리뷰를 작성했습니다.',
    reviewsSubmitNotEligible: '상품을 수령한 고객만 리뷰를 작성할 수 있습니다.',
    reviewsEmpty: '아직 리뷰가 없습니다 — 첫 리뷰를 남겨보세요!',
    reviewsLoadMore: '리뷰 더 보기',
    reviewsUsefulLabel: '도움이 됨',
    reviewsMerchantReplyPrefix: '답변:',
    qaTitle: '상품 문의',
    qaAskButton: '질문하기',
    qaFormPlaceholder: '이 상품에 대해 궁금한 점이 있나요?',
    qaFormSubmit: '질문 등록',
    qaSubmitSuccess: '질문이 등록되었습니다!',
    qaSubmitLoginRequired: '질문하려면 로그인해주세요.',
    qaEmpty: '아직 질문이 없습니다 — 첫 질문을 남겨보세요!',
    qaLoadMore: '질문 더 보기',
    qaAnswerButton: '답변하기',
    qaAnswerFormPlaceholder: '답변을 작성해주세요...',
    qaAnswerSubmit: '답변 등록',
    qaAnswerNotEligible: '이 상품을 구매한 고객만 답변할 수 있습니다.',
    qaAnswerSlotFull: '이 질문은 공개 답변 수가 이미 가득 찼습니다.',
    qaVerifiedBadge: '구매 확인',
    qaAdminBadge: '판매자',
    qaNoAnswersYet: '아직 답변이 없습니다.',
    footerColShop: '스토어',
    footerColShopping: '쇼핑',
    footerColSupport: '고객 지원',
    footerColLegal: '약관',
    footerBrandHint: '온라인 쇼핑 — 설명과 일치하는 상품, 전국 배송.',
    footerCopyright: '© {year} {shop}. 모든 권리 보유.',
    footerPaymentHint: '결제: 착불 · 계좌이체',
    lpExploreProducts: '상품 둘러보기',
    lpViewProducts: '상품 보기',
    lpSuggestedForYou: '당신을 위한 추천',
    homeYouMayLike: '이런 상품은 어때요',
    forYouBadge: '추천',
    lpHighlightsHeading: '구매 포인트',
    lpFaqHeading: '자주 묻는 질문',
    lpRealReviews: '{rating}/5 · 실제 후기 {count}개',
    lpViewFullCategory: '카테고리 전체 보기 →',
    lpMaterialChip: '소재: {name}',
    lpTrust1: '신중하게 고른 상품',
    lpTrust2: '간편한 주문',
    lpTrust3: '필요할 때 지원',
  },
}

export function getPartnerSiteShopCopy(locale: WebLocale): PartnerSiteShopCopy {
  return COPY[locale] ?? COPY.en
}
