import assert from 'node:assert/strict'
import test from 'node:test'
import {
  injectPartnerShopChromeLayoutCss,
  stripVisualEditorRuntimeStateClasses,
  PARTNER_SHOP_CHROME_LAYOUT_STYLE_ID,
  PARTNER_SHOP_LOGO_HOST_SCRIPT,
} from '@/lib/partner-website/shop/partner-shop-chrome-layout-css'
import { PW_SCENE_HEAD_Z } from '@/lib/partner-website/visual-editor/pw-scene'

test('chrome layout css is injected once before </head>', () => {
  const html = '<!DOCTYPE html><html><head><title>Shop</title></head><body><nav class="pw-shop-bottom-nav"></nav></body></html>'
  const once = injectPartnerShopChromeLayoutCss(html)
  const twice = injectPartnerShopChromeLayoutCss(once)
  assert.equal(once.includes(PARTNER_SHOP_CHROME_LAYOUT_STYLE_ID), true)
  assert.equal(once.includes('data-pw-chat-icon-logo'), true)
  assert.equal(once.includes('[data-pw-added-image][data-pw-image-radius]'), true)
  assert.equal(once.includes('[data-pw-chrome-btn="chat"] .pw-chrome-chat-logo'), true)
  assert.equal(once.includes('--pw-chrome-size:22px'), true)
  assert.equal(once.includes('--pw-chrome-w:var(--pw-chrome-size)'), true)
  assert.equal(once.includes('--pw-chrome-h:var(--pw-chrome-size)'), true)
  assert.equal(once.includes('--pw-chrome-label:13px'), true)
  assert.equal(once.includes('--pw-chrome-pad-x:calc(var(--pw-chrome-w,var(--pw-chrome-size,22px))*12/22)'), true)
  assert.equal(once.includes('--pw-chrome-pad-y:calc(var(--pw-chrome-h,var(--pw-chrome-size,22px))*4/22)'), true)
  assert.equal(once.includes('min-height:0!important'), true)
  assert.equal(once.includes('font-size:var(--pw-chrome-label,13px)!important'), true)
  assert.equal(once.includes('.pw-bottom-nav .pw-shop-icon-label'), true)
  assert.equal(once.includes(':not(.pw-chrome-icon-only)'), true)
  assert.equal(once.includes('[data-pw-chrome-btn="chat-zalo"] .pw-chrome-icon-wrap'), true)
  assert.equal(once.includes('border-radius:999px!important'), true)
  assert.equal(once.includes('.pw-chrome-icon-square'), true)
  assert.equal(once.includes('.pw-chrome-icon-circle'), true)
  assert.equal(once.includes('data-pw-chrome-style="icon-circle"'), true)
  assert.equal(once.includes('data-pw-chrome-style="icon-square"'), true)
  assert.equal(once.includes('border-radius:10px!important'), true)
  assert.equal(once.includes('[data-pw-chrome-style="text"] .pw-chrome-icon-wrap'), true)
  assert.equal(once.includes('.pw-chrome-link .pw-chrome-icon-wrap'), true)
  assert.equal(once.includes('.pw-header-actions .pw-account-btn'), true)
  assert.equal(once.includes('.pw-header .pw-account-btn'), true)
  assert.equal(once.includes('.pw-bottom-nav .pw-account-btn'), true)
  assert.match(once, /\.pw-bottom-nav \.pw-account-btn[^{]*\{[^}]*color:#6b7280!important/)
  assert.equal(/(?:^|[,}])\s*\.pw-account-btn\{color:#fff/.test(once), false)
  assert.equal(once.includes('.pw-bottom-nav svg,.pw-shop-bottom-nav svg'), true)
  assert.equal(once.includes('width:var(--pw-chrome-w,var(--pw-chrome-size,22px))!important'), true)
  assert.equal(once.includes('min-width:0!important'), true)
  assert.equal(once.includes('.pw-bottom-nav svg{width:22px!important'), false)
  assert.equal(once.includes('.pw-pdp-sticky svg,.pw-pdp-sticky-nav svg{width:22px!important'), false)
  assert.match(once, /\[data-pw-chrome-style="text"\] \.pw-chrome-icon-wrap[^{]*\{[^}]*display:none!important/)
  assert.equal(once.includes('border-radius:10px!important'), true)
  assert.equal(once.includes('data-pw-chrome-float'), true)
  assert.equal(once.includes('data-pw-pin-screen'), true)
  assert.equal(once.includes('data-pw-bg-cleared'), true)
  assert.equal(once.includes('data-pw-paper'), true)
  assert.equal(once.includes('data-pw-paper-tile'), true)
  assert.equal(once.includes('background-repeat:repeat!important'), true)
  assert.equal(once.includes('--pw-paper-pos-x'), true)
  assert.equal(once.includes('background-position:center center!important'), false)
  assert.equal(once.includes('data-pw-stay-scroll'), true)
  assert.equal(once.includes('data-pw-stay-layer'), true)
  assert.equal(once.includes('pw-shop-stay-scroll'), true)
  assert.equal(once.includes('[data-pw-hidden="1"]'), true)
  assert.equal(once.includes('[data-pw-featured-categories]'), true)
  assert.equal(once.includes('.pw-featured-cat-card'), true)
  assert.equal(once.includes('{display:none!important}'), true)
  assert.equal(once.includes('.pw-header-actions [data-pw-chrome-kit="1"][data-pw-chrome-style="icon-label-below"][data-pw-hidden="1"]'), true)
  assert.equal(once.includes('[data-pw-chrome-style="icon-label-below"]:not([data-pw-hidden="1"])'), true)
  assert.equal(
    once.includes('.pw-bottom-nav>a:not([data-pw-pdp-home]):not([data-pw-dock-show="pdp"]):not([data-pw-hidden="1"])'),
    true
  )
  assert.equal(
    once.includes('.pw-bottom-nav>a:not([data-pw-pdp-home]):not([data-pw-dock-show="pdp"]){'),
    false
  )
  assert.equal(
    once.includes("if(el.getAttribute&&el.getAttribute('data-pw-hidden')==='1')return"),
    true
  )
  assert.equal(
    once.includes('html .pw-bottom-nav[data-pw-chrome-kit="dock"] > a[data-pw-hidden="1"]'),
    true
  )
  assert.equal(once.includes('.pw-pdp-actions [data-pw-chrome-btn]'), true)
  assert.equal(once.includes(':not([data-pw-chrome-added]):not([data-pw-stay-scroll])'), true)
  assert.equal(once.includes('z-index:9999!important'), true)
  assert.equal(once.includes('pw-shop-chrome-float'), true)
  assert.equal(once.includes('pw-chrome-topup-on'), true)
  assert.equal(once.includes('flex-direction:row'), true)
  assert.equal(once.includes('pw-chrome-label-below'), true)
  assert.equal(once.includes('html [data-pw-chrome-style="icon-label-below"]'), true)
  assert.equal(once.includes(':not(.pw-chrome-label-below):not([data-pw-chrome-style="icon-label-below"])'), true)
  assert.equal(once.includes('.pw-chrome-label-left'), true)
  assert.equal(once.includes('pw-chrome-label-left'), true)
  assert.match(once, /\.pw-chrome-label-left[^{]*\{[^}]*flex-direction:row!important/)
  assert.equal(once.includes('.pw-pdp-sticky svg,.pw-pdp-sticky-nav svg'), true)
  assert.equal(once.includes('.is-fav,.pw-shop-bottom-nav[data-pw-pdp-bottom] .is-fav{color:#e11d48!important}'), false)
  assert.match(once, /is-fav\[aria-pressed="true"\]/)
  assert.match(once, /pw-pdp-like-copy/)
  assert.equal(once.includes('[data-pw-region="gallery"]'), true)
  assert.equal(once.includes('.pw-shop-footer-col a:not([data-pw-chrome-added])'), true)
  assert.equal(once.includes('html .pw-footer:not([data-pw-bg-cleared="1"]):not([data-pw-paper="image"]),html .pw-shop-footer:not([data-pw-bg-cleared="1"]):not([data-pw-paper="image"]){background:var(--pw-footer,#fff)!important}'), true)
  assert.equal(once.includes('min-height:1.45em!important'), true)
  assert.equal(once.includes('.pw-seo-row:empty'), true)
  assert.equal(once.includes('.pw-seo-row[hidden]'), true)
  assert.equal(once.includes('.pw-seo-row:not(:empty):not([hidden])'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] .pw-shop-footer-inner'), true)
  assert.equal(once.includes('html [data-pw-region="banner"] img[data-pw-el="media"]'), true)
  assert.equal(once.includes('html [data-pw-slider]'), true)
  assert.equal(once.includes('data-pw-full-slides'), true)
  assert.equal(once.includes('pw-slide-prev'), true)
  assert.equal(once.includes('html [data-pw-hrow]'), true)
  assert.equal(once.includes('object-fit:cover!important'), true)
  assert.equal(once.includes('[data-pw-chrome-btn][data-pw-scene="4"]'), true)
  assert.equal(once.includes('z-index:400!important'), true)
  assert.equal(once.includes('.pw-pdp,.pw-shop-breadcrumb'), true)
  assert.equal(once.includes('.pw-header-actions [data-pw-chrome-added]'), true)
  assert.equal(once.includes('.pw-header-search,.pw-shop-search-wrap'), true)
  assert.equal(once.includes(':not([data-pw-el="search"]):not(.pw-header-search):not(.pw-shop-search-wrap)'), true)
  assert.equal(once.includes('min-width:72px!important'), true)
  assert.equal(once.includes('min-width:96px'), true)
  assert.equal(once.includes("el.getAttribute('data-pw-user-move'))return"), true)
  assert.equal(once.includes('function isCatToggle'), false)
  assert.equal(once.includes('if(isCatToggle(el))return true'), false)
  assert.equal(once.includes('if(isPlacedChrome(el))return'), true)
  assert.equal(once.includes("if(el.getAttribute('data-pw-placement'))return true"), true)
  assert.equal(once.includes("if(el.getAttribute('data-pw-box-x')!=null)return true"), true)
  assert.equal(once.includes("if(el.getAttribute('data-pw-fixed-x')!=null)return true"), true)
  assert.equal(once.includes('function isLegacyInflowCategory(el){'), true)
  assert.equal(once.includes('if(resetLegacyInflowCategory(el))return'), true)
  assert.equal(once.includes('function resetLegacyInflowWordmark(el){'), true)
  assert.equal(once.includes("document.querySelectorAll('.pw-wordmark')"), true)
  assert.equal(once.includes('.pw-cat-btn,.pw-shop-cat-btn,[data-pw-el="cat-toggle"]'), true)
  assert.equal(once.includes('[data-pw-chrome-btn="categories"]'), true)
  assert.equal(
    once.includes('.pw-brand-cluster [data-pw-chrome-btn="categories"]:not([data-pw-placement])'),
    true
  )
  assert.equal(once.includes('.pw-cat-btn:not(.pw-stick-header-on):not([data-pw-chrome-float])'), true)
  assert.equal(once.includes('isFloatChrome'), true)
  assert.match(once, /body:not\(\.nanoai-ve-active\) \[data-pw-seo-coach\]/)
  assert.match(once, /\.nanoai-ve-active \[data-pw-article-editor\]/)
  assert.equal(once.includes("el.getAttribute('data-pw-chrome-float')==='1'"), true)
  assert.equal(once.includes("return k==='topup';"), false)
  assert.equal(once.includes("return k==='chat'||k==='chat-zalo'||k==='chat-facebook'||k==='topup';"), true)
  assert.equal(once.includes('if(isFloatChrome(el))return'), true)
  assert.equal(once.includes('[data-pw-chrome-float="1"].pw-chrome-icon-only'), true)
  assert.equal(once.includes('flex-wrap:nowrap!important;align-items:center!important;justify-content:flex-end!important'), true)
  assert.equal(once.includes('min-width:96px!important;max-width:100%!important;margin:0!important;min-height:40px!important'), true)
  assert.equal(once.includes('flex:1 1 0%'), true)
  assert.equal(once.includes('data-pw-search-width'), true)
  assert.equal(once.includes('width:calc(var(--pw-chrome-w,var(--pw-chrome-size,16px)) + 4px)!important'), true)
  assert.equal(once.includes('align-self:stretch!important'), true)
  assert.equal(once.includes('.pw-search-form .pw-search-image-btn'), true)
  assert.match(once, /\.pw-search-form \.pw-search-image-btn[^{]*\{[^}]*align-self:stretch!important/)
  assert.match(once, /\.pw-search-form \.pw-search-image-btn[^{]*\{[^}]*min-height:100%!important/)
  assert.equal(once.includes('pw-shop-search-submit-icon'), true)
  assert.equal(once.includes('content:""!important'), true)
  assert.equal(once.includes('transform:none!important'), true)
  assert.equal(once.includes('pw-shop-chrome-inset'), true)
  assert.equal(once.includes('html{overflow-x:visible!important'), true)
  assert.equal(once.includes('body{overflow-x:hidden!important'), true)
  assert.equal(once.includes('html{overflow-x:hidden!important'), false)
  assert.equal(once.includes('--pw-content:1200px;--pw-page-gutter:20px;--pw-block-w:min(calc(var(--pw-scene-w,100%) - 32px),var(--pw-content,1200px));--pw-chrome-inset:calc(var(--pw-block-w) * 0.05)'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"],html[data-pw-scene-lock="mobile"]{--pw-page-gutter:4px;--pw-block-w:min(calc(var(--pw-scene-w,100%) - 8px),var(--pw-content,1200px))}'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] .pw-page-shell .pw-container:not(.pw-header-main):not(.pw-shop-header-inner):not(.pw-topbar-inner):not(.pw-nav-main):not(.pw-shop-nav-row),html[data-pw-scene-lock="mobile"] .pw-page-shell .pw-container:not(.pw-header-main):not(.pw-shop-header-inner):not(.pw-topbar-inner):not(.pw-nav-main):not(.pw-shop-nav-row),html[data-pw-edit-device="mobile"] .pw-shop-main .pw-container:not(.pw-header-main):not(.pw-shop-header-inner):not(.pw-topbar-inner):not(.pw-nav-main):not(.pw-shop-nav-row),html[data-pw-scene-lock="mobile"] .pw-shop-main .pw-container:not(.pw-header-main):not(.pw-shop-header-inner):not(.pw-topbar-inner):not(.pw-nav-main):not(.pw-shop-nav-row){padding-left:0!important;padding-right:0!important}'), true)
  assert.equal(once.includes('html [data-pw-region="banner"] [data-pw-el="cta"]'), true)
  assert.equal(once.includes('html [data-pw-region="banner"] [data-pw-el="cta-secondary"]'), true)
  assert.equal(once.includes('html[data-pw-edit-device="desktop"] .pw-hero'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="laptop"] .pw-hero'), true)
  assert.equal(once.includes('margin-top:0!important'), true)
  assert.equal(once.includes(':not([data-pw-image-radius])'), true)
  assert.equal(once.includes('[data-pw-image-radius="0"]{border-radius:0!important}'), true)
  assert.equal(once.includes('--pw-scene-w:1440px'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"],html[data-pw-scene-lock="mobile"]{--pw-scene-w:390px}'), true)
  assert.equal(once.includes('margin-left:calc(50% - (var(--pw-scene-w) / 2))!important'), true)
  assert.equal(once.includes('[data-pw-inline-visual-root]{width:var(--pw-scene-w)!important'), true)
  assert.equal(once.includes('min-height:0!important;height:auto!important'), true)
  assert.equal(once.includes('body.nanoai-ve-active{width:var(--pw-scene-w)!important'), true)
  assert.equal(once.includes('html[data-pw-scene-zoomed="1"] [data-pw-inline-visual-root]{transform:scale(var(--pw-scene-zoom,1))}'), true)
  assert.equal(once.includes('transform:scale(var(--pw-scene-zoom,1))'), true)
  assert.equal(once.includes('[data-pw-live-chrome]'), true)
  assert.equal(once.includes('[data-pw-live-dock]'), true)
  assert.equal(once.includes('[data-pw-live-fixed-layer]'), true)
  assert.equal(once.includes('html .pw-nav-main,html .pw-shop-nav-row{width:var(--pw-block-w)!important'), true)
  assert.equal(once.includes('transform-origin:top center'), true)
  assert.equal(once.includes('pw-shop-scene-center'), true)
  assert.equal(once.includes('function hoistLiveChrome(root,scale){'), true)
  assert.equal(once.includes('function hoistLiveDock(root){'), true)
  assert.equal(once.includes('function hoistLiveFloat(root){'), true)
  assert.equal(once.includes('data-pw-live-chrome-scale'), true)
  assert.equal(once.includes('data-pw-live-dock'), true)
  assert.equal(once.includes('data-pw-scene-lock'), true)
  assert.equal(once.includes('var C=window.__pwCoordinate'), true)
  assert.equal(once.includes('C.resolveDevice({'), true)
  assert.equal(once.includes('forcedDevice:s'), true)
  assert.equal(once.includes('html:not([data-pw-edit-device="desktop"]):not([data-pw-scene-lock="desktop"]) .pw-nav-main'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="desktop"] .pw-bottom-nav'), true)
  assert.equal(once.includes('html[data-pw-edit-device="tablet"] .pw-bottom-nav'), true)
  assert.equal(once.includes('html[data-pw-edit-device="laptop"] .pw-bottom-nav'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] .pw-bottom-nav'), true)
  assert.equal(once.includes('.pw-bottom-nav[data-pw-chrome-kit="dock"]{display:flex!important'), false)
  assert.equal(once.includes('html:not([data-pw-edit-device]):not([data-pw-scene-lock]) .pw-shop-search-submit-label{display:none}'), true)
  assert.equal(once.includes('.pw-search-default-icon'), true)
  assert.equal(once.includes('.pw-search-submit:has(svg)::before'), true)
  assert.equal(once.includes('.pw-search-form .pw-search-submit::before'), true)
  assert.equal(once.includes('html:has([data-pw-pdp-add-cart])'), false)
  assert.equal(once.includes('html:has([data-pw-page="product"])'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="mobile"] .pw-bottom-nav,html[data-pw-scene-lock="mobile"] .pw-shop-bottom-nav'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="mobile"] .pw-bottom-nav,html[data-pw-scene-lock="mobile"] .pw-shop-bottom-nav{display:none!important}'), false)
  assert.equal(once.includes('data-pw-pdp-bottom'), true)
  assert.equal(once.includes('data-pw-chrome-kit="dock"'), true)
  assert.equal(once.includes('data-pw-dock-show'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="desktop"] .pw-visual-desktop{display:contents!important}'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="desktop"]:has(.pw-visual-desktop) .pw-visual-laptop'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="laptop"]:has(.pw-visual-laptop) .pw-visual-desktop'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="laptop"]:has(.pw-visual-laptop) .pw-visual-tablet'), true)
  assert.equal(once.includes('pw-shop-image-zoom'), true)
  assert.equal(once.includes("scale('+z+')"), true)
  assert.equal(once.includes('scaleY('), false)
  assert.equal(once.includes('transform-origin:50% var(--pw-zoom-oy,50%)'), true)
  assert.equal(once.includes('repeat(2,minmax(0,1fr))!important'), true)
  assert.equal(once.includes('[data-pw-catalog] [data-pw-grid]'), true)
  assert.equal(once.includes('[data-pw-edit-device="mobile"] .pw-product-grid'), true)
  assert.equal(once.includes('grid-template-columns:repeat(2,minmax(0,1fr))!important'), true)
  assert.equal(once.includes('[data-pw-catalog] [data-pw-grid]'), true)
  assert.equal(once.includes('data-pw-edit-device="mobile"] .pw-product-grid'), true)
  assert.equal(once.includes('html[data-pw-edit-device="desktop"] .pw-product-grid'), true)
  assert.equal(once.includes('[data-pw-related] [data-pw-grid]'), true)
  assert.equal(once.includes('[data-pw-outfit] [data-pw-grid]'), true)
  assert.equal(once.includes('aspect-ratio:1/1!important'), true)
  assert.equal(once.includes('color:transparent!important'), true)
  assert.equal(once.includes('html[data-pw-edit-device="laptop"] .pw-product-grid'), true)
  assert.equal(once.includes('grid-template-columns:repeat(4,minmax(0,1fr))!important'), true)
  assert.equal(once.includes('grid-template-columns:repeat(5,minmax(0,1fr))!important'), true)
  assert.equal(once.includes('min-width:1440px'), true)
  assert.equal(once.includes('z-index:200'), true)
  assert.equal(once.includes(`z-index:${PW_SCENE_HEAD_Z}!important`), true)
  assert.equal(once.includes(`.pw-header,.pw-shop-header{position:sticky!important;top:0!important;z-index:${PW_SCENE_HEAD_Z}!important`), true)
  assert.equal(once.includes('.pw-topbar,.pw-shop-topbar'), true)
  assert.equal(once.includes('min-height:36px'), true)
  assert.equal(once.includes('z-index:150'), true)
  assert.equal(once.includes('.pw-logo-frame:not([data-pw-z])'), true)
  assert.equal(once.includes("el.style.setProperty('z-index',z,'important')"), true)
  assert.equal(once.includes("header.querySelector('.pw-header-main,.pw-shop-header-inner')"), true)
  assert.equal(once.includes('host.appendChild(el)'), true)
  assert.equal(once.includes('[data-pw-scene="0"]{z-index:0!important}'), true)
  assert.equal(once.includes('z-index:210'), false)
  assert.equal(once.includes('.pw-header,.pw-shop-header{position:sticky!important;top:0!important;z-index:200!important;isolation:isolate'), false)
  assert.equal(once.includes(`.pw-header,.pw-shop-header{position:sticky!important;top:0!important;z-index:${PW_SCENE_HEAD_Z}!important;isolation:isolate`), false)
  assert.equal(once.includes('position:fixed!important'), true)
  assert.equal(once.includes('z-index:160'), true)
  assert.equal(once.includes('html .pw-header-main,html .pw-shop-header-inner{display:flex!important'), true)
  assert.equal(once.includes('min-width:0;position:relative!important;max-width:var(--pw-block-w)!important'), true)
  assert.equal(once.includes('html .pw-topbar-inner,html .pw-shop-topbar-inner{display:flex!important;justify-content:flex-end!important'), true)
  assert.equal(once.includes('align-self:center!important;box-sizing:border-box'), true)
  assert.equal(once.includes('html .pw-hero,html .pw-banner,html .pw-shop-hero,html .pw-shop-banner,html [data-pw-region="banner"]{max-width:var(--pw-block-w)!important'), true)
  assert.equal(once.includes('[data-pw-region="banner"][data-pw-placement="scene-absolute"]'), true)
  assert.equal(once.includes('html [data-pw-region="banner"][data-pw-scene],html [data-pw-region="categories"][data-pw-scene]'), true)
  assert.equal(once.includes('[data-pw-added-bg-slot]'), true)
  assert.equal(once.includes('html [data-pw-block-w]:not([data-pw-region="header"])'), true)
  assert.equal(once.includes(':not([data-pw-added-bg]){width:var(--pw-block-w)!important'), true)
  assert.equal(
    once.includes(
      'html [data-pw-block-h]:not([data-pw-added-bg]):not([data-pw-added-catalog]):not([data-pw-featured-categories]):not([data-pw-region="catalog"]){min-height:var(--pw-block-h)!important'
    ),
    true
  )
  assert.equal(once.includes('border-radius:var(--pw-image-radius,0px)!important'), true)
  assert.equal(once.includes('html [data-pw-hrow]>[data-pw-added-bg="1"]:not([data-pw-added-bg-slot]){flex:0 0 auto!important'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] .pw-header-main'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="mobile"] .pw-header-main'), true)
  assert.equal(once.includes('max-width:none!important'), true)
  assert.equal(once.includes('@media (min-width:900px){html:not([data-pw-edit-device]):not([data-pw-scene-lock]) .pw-header-main'), true)
  assert.equal(once.includes('html[data-pw-edit-device="desktop"] .pw-header-search'), true)
  assert.equal(once.includes('html[data-pw-edit-device="laptop"] .pw-header-search'), true)
  assert.equal(once.includes('left:50%!important'), true)
  assert.equal(once.includes('transform:translate(-50%,-50%)!important'), true)
  assert.equal(once.includes('transform:translateX(var(--pw-kit-x, 0px))'), true)
  assert.equal(once.includes('gap:var(--pw-kit-gap, 8px)'), true)
  assert.equal(once.includes('gap:var(--pw-kit-gap, 4px)'), true)
  assert.equal(once.includes("el.style.removeProperty('position')"), true)
  assert.equal(once.includes("el.style.setProperty('margin-left','auto','important')"), false)
  assert.equal(once.includes('min-width:180px!important'), true)
  assert.equal(once.includes('max-width:380px!important'), true)
  assert.equal(once.includes('left:calc(50% - 190px - 50px + var(--pw-logo-x, 0px))!important'), true)
  assert.equal(once.includes('top:calc(50% + var(--pw-logo-y, 0px))!important'), true)
  assert.equal(once.includes('transform:translate(-100%, -50%)!important'), true)
  assert.equal(once.includes('.pw-footer .pw-shop-footer-brand>a'), true)
  assert.equal(once.includes('transform:translate(var(--pw-logo-x, 0px), var(--pw-logo-y, 0px))!important'), true)
  assert.equal(once.includes('.pw-footer .pw-shop-footer-brand>a,.pw-shop-footer .pw-shop-footer-brand>a'), true)
  assert.equal(once.includes('.pw-footer .pw-header-main a.pw-brand'), false)
  assert.equal(once.includes('margin-right:calc(190px + 50px)!important'), false)
  assert.equal(once.includes('flex:1 1 0%!important'), true)
  assert.equal(once.includes('justify-content:flex-end!important'), true)
  assert.equal(once.includes('padding:8px var(--pw-chrome-inset,60px)!important'), true)
  assert.equal(once.includes('padding-left:var(--pw-chrome-inset,60px)!important'), true)
  assert.equal(once.includes('--pw-chrome-size:20px'), true)
  assert.equal(once.includes('--pw-chrome-size:18px'), true)
  assert.equal(once.includes('[data-pw-chrome-size="22"]'), false)
  assert.equal(once.includes('isInflowHeaderSearch'), true)
  assert.equal(once.includes('max-width:360px!important'), false)
  assert.equal(once.includes('data-pw-logo-frame'), true)
  assert.equal(once.includes('.pw-logo-frame .pw-logo'), true)
  assert.equal(once.includes('[data-pw-logo-frame="1"] img{height:100%!important'), true)
  assert.equal(once.includes('.pw-logo-frame img'), true)
  assert.equal(once.includes('object-position:center center!important'), true)
  assert.equal(once.includes('data-pw-logo-float'), true)
  assert.equal(once.includes('overflow:hidden!important;pointer-events:auto!important'), true)
  assert.equal(once.includes('data-pw-logo-empty'), true)
  assert.equal(once.includes('.pw-logo-frame:not([data-pw-logo-float="1"]) ~ .pw-logo-frame:not([data-pw-logo-float="1"])'), true)
  assert.equal(once.includes('[data-pw-logo-float="1"]:not([data-pw-z])'), true)
  assert.equal(once.includes('body:not(.nanoai-ve-active) a[data-pw-logo-home]'), true)
  assert.equal(once.includes('a[data-pw-logo-home]:not([data-pw-logo-float]){display:inline-flex!important'), true)
  assert.equal(once.includes('width:max-content!important'), true)
  assert.equal(once.includes('max-width:180px!important'), true)
  assert.equal(once.includes('cursor:pointer!important'), true)
  assert.equal(once.includes('body:not(.nanoai-ve-active) .pw-topbar,body:not(.nanoai-ve-active) .pw-shop-topbar{pointer-events:none!important}'), true)
  assert.equal(once.includes('[data-pw-chrome-badge][hidden]'), true)
  assert.equal(once.includes('-webkit-text-fill-color'), true)
  assert.equal(once.includes('overflow:visible!important'), true)
  assert.equal(once.includes('.pw-shop-brand-cluster{pointer-events:none!important}'), true)
  assert.equal(once.includes('.pw-chrome-cat-wrap'), true)
  assert.equal(once.includes('[data-pw-image-search]'), true)
  assert.equal(once.includes('.pw-shop-brand-cluster > *'), true)
  assert.equal(once.includes('pointer-events:auto!important'), true)
  assert.equal(once.includes('html:not([data-pw-edit-device]):not([data-pw-scene-lock]) [data-pw-chrome-added][data-pw-device="mobile"]'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] [data-pw-chrome-added]'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] .pw-cat-btn:not([data-pw-chrome-added])>span:not(.pw-chrome-icon-wrap)'), true)
  assert.equal(
    once.includes(
      'html[data-pw-edit-device="tablet"] .pw-cat-btn:not([data-pw-chrome-added]):not(.pw-chrome-icon-only):not([data-pw-chrome-style="icon"])'
    ),
    true
  )
  assert.equal(once.includes('[data-pw-chrome-style="icon"]'), true)
  assert.equal(once.includes('.pw-account-btn-label'), true)
  assert.equal(once.includes('html[data-pw-edit-device] :is(.pw-chrome-icon-only'), true)
  assert.equal(once.includes('[data-pw-chrome-style^="icon"]'), false)
  assert.equal(once.includes('.pw-cat-btn:not([data-pw-chrome-style="text"]):not(.pw-chrome-link) .pw-chrome-icon-wrap'), true)
  assert.equal(once.includes('.pw-cat-btn:not([data-pw-chrome-style="text"]):not(.pw-chrome-link) svg'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] .pw-header-actions [data-pw-chrome-btn="cart"]'), true)
  assert.equal(once.includes('pw-shop-mobile-header-logo'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] header [data-pw-chrome-btn="try-on"]'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] header [data-pw-chrome-btn="favorite-product"]'), true)
  assert.equal(once.includes('html[data-pw-edit-device="mobile"] main > .pw-shop-btn[data-pw-chrome-btn="try-on"]'), true)
  assert.equal(once.includes('data-pw-head-logo-collapsed'), true)
  assert.equal(once.includes('order:-1!important'), true)
  assert.equal(once.includes('max-width:46%!important'), true)
  assert.equal(once.includes('background:var(--pw-primary)!important'), true)
  assert.equal(once.includes('html[data-pw-scene-lock="mobile"] [data-pw-chrome-added]'), true)
  assert.equal(once.includes('[data-pw-chrome-added].pw-cat-btn'), true)
  assert.equal(once.includes('appearance:none'), true)
  assert.equal(once.includes('data-pw-device="mobile"'), true)
  assert.equal(once.includes('data-pw-device="tablet"'), true)
  assert.equal(once.includes('data-pw-device="laptop"'), true)
  assert.equal(once.includes('[data-pw-chrome-btn="favorites-link"][data-pw-chrome-added]'), true)
  assert.equal(once.includes('main > .pw-topbar-inner'), true)
  assert.equal(once.includes(':not([data-pw-chrome-count])'), false)
  assert.equal(once.includes('min-width:768px'), true)
  assert.equal(once.includes('min-width:1280px'), true)
  assert.equal(once.includes('max-width:1279px'), true)
  assert.equal(once.includes('white-space:normal'), true)
  assert.equal(once.includes('flex-wrap:nowrap'), true)
  assert.equal(once.includes('max-width:1439px'), true)
  assert.equal(once.includes('flex-direction:column!important'), true)
  assert.equal(once.includes('.pw-nav-main>a.pw-nav-sale'), true)
  assert.equal(once.includes('data-pw-search-history-on'), false)
  assert.equal(once.includes('[data-pw-search-history]'), true)
  assert.equal(once.includes('[data-pw-search-history-clear]'), true)
  assert.equal(once.includes('top:100%'), true)
  assert.equal(once.includes('color:#374151!important'), true)
  assert.equal(once.includes('.pw-cat-mega-l2:hover'), true)
  assert.equal(once.includes('.pw-cat-mega-l3:hover'), true)
  assert.equal(once.includes('color:var(--pw-primary)!important'), true)
  assert.equal(once.includes('pw-shop-chrome-badge-pin'), true)
  assert.equal(once.includes('pw-shop-stick-header'), true)
  assert.equal(once.includes('pw-shop-logo-host'), true)
  assert.equal(PARTNER_SHOP_LOGO_HOST_SCRIPT.includes("el.style.setProperty('left','0px','important')"), true)
  assert.equal(PARTNER_SHOP_LOGO_HOST_SCRIPT.includes('getBoundingClientRect'), true)
  assert.equal(once.includes('data-pw-stick-header'), true)
  assert.equal(once.includes('__pwStickHeaderSync'), true)
  assert.equal(twice, once)
  const stale = once.replace('flex-direction:row', 'flex-direction:column')
  const refreshed = injectPartnerShopChromeLayoutCss(stale)
  assert.equal(refreshed.includes('flex-direction:row'), true)
  assert.equal((refreshed.match(/id="pw-shop-chrome-layout"/g) || []).length, 1)
  const duped = `${once}<style id="pw-shop-chrome-layout">.old{}</style>`
  const collapsed = injectPartnerShopChromeLayoutCss(duped)
  assert.equal((collapsed.match(/id="pw-shop-chrome-layout"/g) || []).length, 1)
  assert.equal(collapsed.includes('flex:1 1 0%'), true)
  assert.equal(collapsed.includes('data-pw-search-width'), true)
})

test('saved html never keeps the editor runtime state on <body>', () => {
  const saved =
    '<!DOCTYPE html><html><head></head><body class="antialiased nanoai-ve-mobile nanoai-ve-active" data-pw-bg-role="canvas"><header class="pw-shop-header"></header></body></html>'
  const out = injectPartnerShopChromeLayoutCss(saved)
  assert.equal(/<body[^>]*\bnanoai-ve-active\b/.test(out), false)
  // Device isolation classes and other body attributes must survive.
  assert.equal(out.includes('nanoai-ve-mobile'), true)
  assert.equal(out.includes('antialiased'), true)
  assert.equal(out.includes('data-pw-bg-role="canvas"'), true)

  const onlyState = stripVisualEditorRuntimeStateClasses('<body class="nanoai-ve-active"><p>x</p></body>')
  assert.equal(onlyState.includes('class='), false)
  assert.equal(onlyState.includes('<p>x</p>'), true)

  const clean = '<body class="antialiased"><p>x</p></body>'
  assert.equal(stripVisualEditorRuntimeStateClasses(clean), clean)
})
