import type { WebLocale } from '@/lib/i18n/config'

export type PartnerSiteShopCopy = {
  navHome: string
  navProducts: string
  navRecentlyViewed: string
  navFavorites: string
  navRecommended: string
  navCart: string
  navChat: string
  navCategories: string
  catalogTitle: string
  catalogEmpty: string
  loadMore: string
  productDetail: string
  addToCart: string
  buyNow: string
  addedToCart: string
  consultChat: string
  cartTitle: string
  cartEmpty: string
  cartSubtotal: string
  cartCheckout: string
  cartCheckingOut: string
  cartRemove: string
  checkoutName: string
  checkoutPhone: string
  checkoutAddress: string
  checkoutNote: string
  checkoutSuccess: string
  checkoutAuthRequired: string
  checkoutGuestHint: string
  checkoutAuthLink: string
  quantity: string
  backToShop: string
  navOrders: string
  sizeLabel: string
  colorLabel: string
  searchPlaceholder: string
  searchButton: string
  searchByImage: string
  searchSearching: string
  searchResults: string
  searchEmpty: string
  searchError: string
  relatedProducts: string
  tryOnLink: string
  ordersTitle: string
  ordersEmpty: string
  authSendOtp: string
  authVerifyOtp: string
  authSuccess: string
  authFailed: string
  authOtpSent: string
  authEmailLogin: string
  authChangeEmail: string
  authEmailRequired: string
  authGoogleLogin: string
  authShopOtpOr: string
  authLoginSubtitle: string
  authQuickLoginFailed: string
  authNanoAiLoginHint: string
  authRememberDevice: string
  orderIdLabel: string
  depositAmount: string
  paymentReference: string
  depositPolicyNote: string
  productDescriptionTitle: string
  productDetailImagesTitle: string
  productVideoTitle: string
  favoriteAdd: string
  favoriteRemove: string
  wishlistTitle: string
  wishlistEmpty: string
  recentlyViewedTitle: string
  recentlyViewedEmpty: string
  chatOpenLabel: string
  chatCloseLabel: string
  chatFullPageLabel: string
  chatLanguageLabel: string
  navAccount: string
  accountEditProfile: string
  accountViewedProducts: string
  accountAddressBook: string
  accountEmailLabel: string
  accountSave: string
  accountSaved: string
  accountSaveFailed: string
  addressesHint: string
  accountWelcome: string
  accountQuickLinks: string
  accountSectionEditProfile: string
  orderStatusLabel: string
  orderStatusAwaitingPayment: string
  orderStatusPaymentChecking: string
  orderStatusPaidVerified: string
  orderStatusPendingManualReview: string
  orderStatusCancelled: string
  orderShippingStatusLabel: string
  orderShippingPending: string
  orderShippingConfirmed: string
  orderShippingPacking: string
  orderShippingShipping: string
  orderShippingDelivered: string
  orderShippingReturned: string
  orderShippingCancelled: string
  orderDateLabel: string
  orderViewPayment: string
  orderHidePayment: string
  orderQuantityLabel: string
  recentlyViewedClear: string
  recentlyViewedCleared: string
  addressesEmptyHint: string
}

const COPY: Record<WebLocale, PartnerSiteShopCopy> = {
  vi: {
    navHome: 'Trang chủ',
    navProducts: 'Sản phẩm',
    navRecentlyViewed: 'Vừa xem',
    navFavorites: 'Yêu thích',
    navRecommended: 'Gợi ý',
    navCart: 'Giỏ hàng',
    navChat: 'Chat mua',
    navCategories: 'Danh mục',
    catalogTitle: 'Tất cả sản phẩm',
    catalogEmpty: 'Chưa có sản phẩm.',
    loadMore: 'Xem thêm',
    productDetail: 'Chi tiết sản phẩm',
    addToCart: 'Thêm vào giỏ',
    buyNow: 'Mua ngay',
    addedToCart: 'Đã thêm vào giỏ.',
    consultChat: 'Chat tư vấn',
    cartTitle: 'Giỏ hàng',
    cartEmpty: 'Giỏ hàng trống.',
    cartSubtotal: 'Tạm tính',
    cartCheckout: 'Thanh toán',
    cartCheckingOut: 'Đang tạo đơn…',
    cartRemove: 'Xóa',
    checkoutName: 'Họ tên',
    checkoutPhone: 'Số điện thoại',
    checkoutAddress: 'Địa chỉ giao hàng',
    checkoutNote: 'Ghi chú',
    checkoutSuccess: 'Đã tạo đơn — shop sẽ liên hệ sớm.',
    checkoutAuthRequired: 'Vui lòng đăng nhập để tiếp tục.',
    checkoutGuestHint: 'Bạn có thể đặt hàng mà không cần đăng nhập — chỉ cần điền thông tin giao hàng.',
    checkoutAuthLink: 'Đăng nhập / xác minh tại chat shop',
    quantity: 'Số lượng',
    backToShop: 'Tiếp tục mua',
    navOrders: 'Đơn hàng',
    sizeLabel: 'Size',
    colorLabel: 'Màu',
    searchPlaceholder: 'Tìm sản phẩm…',
    searchButton: 'Tìm',
    searchByImage: 'Tìm bằng ảnh',
    searchSearching: 'Đang tìm…',
    searchResults: 'Kết quả tìm kiếm',
    searchEmpty: 'Không tìm thấy sản phẩm phù hợp.',
    searchError: 'Không tìm được. Thử lại.',
    relatedProducts: 'Sản phẩm liên quan',
    tryOnLink: 'Thử đồ AI',
    ordersTitle: 'Đơn hàng của bạn',
    ordersEmpty: 'Chưa có đơn hàng.',
    authSendOtp: 'Gửi mã OTP',
    authVerifyOtp: 'Xác minh',
    authSuccess: 'Đã xác minh email — có thể thanh toán.',
    authFailed: 'Không xác minh được. Thử lại.',
    authOtpSent: 'Đã gửi mã OTP tới email.',
    authEmailLogin: 'Đăng nhập bằng email',
    authChangeEmail: 'Đổi email khác',
    authEmailRequired: 'Vui lòng nhập email.',
    authGoogleLogin: 'Đăng nhập bằng Google',
    authShopOtpOr: 'Hoặc nhập email để nhận mã',
    authLoginSubtitle: 'Google hoặc mã OTP qua email',
    authQuickLoginFailed: 'Chưa đăng nhập được — dùng email OTP bên dưới.',
    authNanoAiLoginHint: 'Nhập email — bạn sẽ nhận mã OTP qua email.',
    authRememberDevice: 'Giữ đăng nhập trên thiết bị này (lần sau có thể không cần OTP).',
    orderIdLabel: 'Mã đơn',
    depositAmount: 'Số tiền cọc',
    paymentReference: 'Nội dung chuyển khoản',
    depositPolicyNote: 'Cọc theo cài đặt shop — quét QR hoặc chuyển khoản đúng nội dung.',
    productDescriptionTitle: 'Mô tả sản phẩm',
    productDetailImagesTitle: 'Ảnh chi tiết',
    productVideoTitle: 'Video sản phẩm',
    favoriteAdd: 'Thêm yêu thích',
    favoriteRemove: 'Bỏ yêu thích',
    wishlistTitle: 'Yêu thích',
    wishlistEmpty: 'Chưa có sản phẩm yêu thích.',
    recentlyViewedTitle: 'Vừa xem',
    recentlyViewedEmpty: 'Chưa xem sản phẩm nào.',
    chatOpenLabel: 'Mở chat',
    chatCloseLabel: 'Đóng',
    chatFullPageLabel: 'Mở toàn trang',
    chatLanguageLabel: 'Ngôn ngữ',
    navAccount: 'Tài khoản',
    accountEditProfile: 'Chỉnh sửa hồ sơ',
    accountViewedProducts: 'Sản phẩm đã xem',
    accountAddressBook: 'Sổ địa chỉ',
    accountEmailLabel: 'Email',
    accountSave: 'Lưu thay đổi',
    accountSaved: 'Đã lưu hồ sơ.',
    accountSaveFailed: 'Không lưu được. Thử lại.',
    addressesHint: 'Địa chỉ mặc định khi thanh toán.',
    accountWelcome: 'Xin chào',
    accountQuickLinks: 'Truy cập nhanh',
    accountSectionEditProfile: 'Chỉnh sửa hồ sơ',
    orderStatusLabel: 'Trạng thái',
    orderStatusAwaitingPayment: 'Chờ thanh toán',
    orderStatusPaymentChecking: 'Đang kiểm tra thanh toán',
    orderStatusPaidVerified: 'Đã thanh toán',
    orderStatusPendingManualReview: 'Chờ xác nhận',
    orderStatusCancelled: 'Đã hủy',
    orderShippingStatusLabel: 'Giao hàng',
    orderShippingPending: 'Chờ xử lý',
    orderShippingConfirmed: 'Đã xác nhận',
    orderShippingPacking: 'Đang đóng gói',
    orderShippingShipping: 'Đang giao',
    orderShippingDelivered: 'Đã giao',
    orderShippingReturned: 'Đã trả hàng',
    orderShippingCancelled: 'Đã hủy giao',
    orderDateLabel: 'Ngày đặt',
    orderViewPayment: 'Xem QR / thanh toán',
    orderHidePayment: 'Ẩn thanh toán',
    orderQuantityLabel: 'Số lượng',
    recentlyViewedClear: 'Xóa lịch sử',
    recentlyViewedCleared: 'Đã xóa lịch sử xem.',
    addressesEmptyHint: 'Chưa có địa chỉ — thêm địa chỉ giao hàng mặc định.',
  },
  en: {
    navHome: 'Home',
    navProducts: 'Products',
    navRecentlyViewed: 'Recent',
    navFavorites: 'Favorites',
    navRecommended: 'For you',
    navCart: 'Cart',
    navChat: 'Chat',
    navCategories: 'Categories',
    catalogTitle: 'All products',
    catalogEmpty: 'No products yet.',
    loadMore: 'Load more',
    productDetail: 'Product details',
    addToCart: 'Add to cart',
    buyNow: 'Buy now',
    addedToCart: 'Added to cart.',
    consultChat: 'Chat for advice',
    cartTitle: 'Shopping cart',
    cartEmpty: 'Your cart is empty.',
    cartSubtotal: 'Subtotal',
    cartCheckout: 'Checkout',
    cartCheckingOut: 'Placing order…',
    cartRemove: 'Remove',
    checkoutName: 'Full name',
    checkoutPhone: 'Phone',
    checkoutAddress: 'Shipping address',
    checkoutNote: 'Note',
    checkoutSuccess: 'Order placed — the shop will contact you soon.',
    checkoutAuthRequired: 'Please sign in to continue.',
    checkoutGuestHint: 'You can checkout without signing in — just fill in delivery details.',
    checkoutAuthLink: 'Sign in / verify via shop chat',
    quantity: 'Quantity',
    backToShop: 'Continue shopping',
    navOrders: 'Orders',
    sizeLabel: 'Size',
    colorLabel: 'Color',
    searchPlaceholder: 'Search products…',
    searchButton: 'Search',
    searchByImage: 'Search by image',
    searchSearching: 'Searching…',
    searchResults: 'Search results',
    searchEmpty: 'No matching products.',
    searchError: 'Search failed. Try again.',
    relatedProducts: 'Related products',
    tryOnLink: 'AI try-on',
    ordersTitle: 'Your orders',
    ordersEmpty: 'No orders yet.',
    authSendOtp: 'Send OTP',
    authVerifyOtp: 'Verify',
    authSuccess: 'Email verified — you can checkout.',
    authFailed: 'Verification failed. Try again.',
    authOtpSent: 'OTP sent to your email.',
    authEmailLogin: 'Sign in with email',
    authChangeEmail: 'Use a different email',
    authEmailRequired: 'Please enter your email.',
    authGoogleLogin: 'Sign in with Google',
    authShopOtpOr: 'Or enter email to receive a code',
    authLoginSubtitle: 'Google or OTP via email',
    authQuickLoginFailed: 'Could not sign in — use email OTP below.',
    authNanoAiLoginHint: 'Enter your email — you will receive an OTP code by email.',
    authRememberDevice: 'Keep me signed in on this device (you may skip OTP next time).',
    orderIdLabel: 'Order ID',
    depositAmount: 'Deposit amount',
    paymentReference: 'Transfer reference',
    depositPolicyNote: 'Deposit per shop settings — scan QR or transfer with the reference.',
    productDescriptionTitle: 'Product description',
    productDetailImagesTitle: 'Detail images',
    productVideoTitle: 'Product video',
    favoriteAdd: 'Add to favorites',
    favoriteRemove: 'Remove from favorites',
    wishlistTitle: 'Favorites',
    wishlistEmpty: 'No favorite products yet.',
    recentlyViewedTitle: 'Recently viewed',
    recentlyViewedEmpty: 'No recently viewed products.',
    chatOpenLabel: 'Open chat',
    chatCloseLabel: 'Close',
    chatFullPageLabel: 'Open full page',
    chatLanguageLabel: 'Language',
    navAccount: 'Account',
    accountEditProfile: 'Edit profile',
    accountViewedProducts: 'Viewed products',
    accountAddressBook: 'Address book',
    accountEmailLabel: 'Email',
    accountSave: 'Save changes',
    accountSaved: 'Profile saved.',
    accountSaveFailed: 'Could not save. Try again.',
    addressesHint: 'Default address used at checkout.',
    accountWelcome: 'Hello',
    accountQuickLinks: 'Quick links',
    accountSectionEditProfile: 'Edit profile',
    orderStatusLabel: 'Status',
    orderStatusAwaitingPayment: 'Awaiting payment',
    orderStatusPaymentChecking: 'Checking payment',
    orderStatusPaidVerified: 'Paid',
    orderStatusPendingManualReview: 'Pending review',
    orderStatusCancelled: 'Cancelled',
    orderShippingStatusLabel: 'Shipping',
    orderShippingPending: 'Pending',
    orderShippingConfirmed: 'Confirmed',
    orderShippingPacking: 'Packing',
    orderShippingShipping: 'In transit',
    orderShippingDelivered: 'Delivered',
    orderShippingReturned: 'Returned',
    orderShippingCancelled: 'Shipping cancelled',
    orderDateLabel: 'Order date',
    orderViewPayment: 'View payment QR',
    orderHidePayment: 'Hide payment',
    orderQuantityLabel: 'Quantity',
    recentlyViewedClear: 'Clear history',
    recentlyViewedCleared: 'View history cleared.',
    addressesEmptyHint: 'No address yet — add your default shipping address.',
  },
  zh: {
    navHome: '首页',
    navProducts: '产品',
    navRecentlyViewed: '最近浏览',
    navFavorites: '收藏',
    navRecommended: '推荐',
    navCart: '购物车',
    navChat: '聊天购买',
    navCategories: '分类',
    catalogTitle: '全部产品',
    catalogEmpty: '暂无产品。',
    loadMore: '加载更多',
    productDetail: '产品详情',
    addToCart: '加入购物车',
    buyNow: '立即购买',
    addedToCart: '已加入购物车。',
    consultChat: '咨询聊天',
    cartTitle: '购物车',
    cartEmpty: '购物车为空。',
    cartSubtotal: '小计',
    cartCheckout: '结账',
    cartCheckingOut: '正在下单…',
    cartRemove: '删除',
    checkoutName: '姓名',
    checkoutPhone: '电话',
    checkoutAddress: '收货地址',
    checkoutNote: '备注',
    checkoutSuccess: '订单已创建 — 店铺将尽快联系。',
    checkoutAuthRequired: '请登录后继续。',
    checkoutGuestHint: '无需登录即可下单 — 填写收货信息即可。',
    checkoutAuthLink: '在店铺聊天中登录/验证',
    quantity: '数量',
    backToShop: '继续购物',
    navOrders: '订单',
    sizeLabel: '尺码',
    colorLabel: '颜色',
    searchPlaceholder: '搜索产品…',
    searchButton: '搜索',
    searchByImage: '以图搜图',
    searchSearching: '搜索中…',
    searchResults: '搜索结果',
    searchEmpty: '未找到匹配商品。',
    searchError: '搜索失败，请重试。',
    relatedProducts: '相关产品',
    tryOnLink: 'AI 试穿',
    ordersTitle: '我的订单',
    ordersEmpty: '暂无订单。',
    authSendOtp: '发送验证码',
    authVerifyOtp: '验证',
    authSuccess: '邮箱已验证 — 可以结账。',
    authFailed: '验证失败，请重试。',
    authOtpSent: '验证码已发送到邮箱。',
    authEmailLogin: '邮箱登录',
    authChangeEmail: '更换邮箱',
    authEmailRequired: '请输入邮箱。',
    authGoogleLogin: '使用 Google 登录',
    authShopOtpOr: '或输入邮箱获取验证码',
    authLoginSubtitle: 'Google 或邮箱 OTP',
    authQuickLoginFailed: '无法登录 — 请使用下方邮箱 OTP。',
    authNanoAiLoginHint: '输入邮箱 — 您将通过邮件收到验证码。',
    authRememberDevice: '在此设备保持登录（下次可能免 OTP）。',
    orderIdLabel: '订单号',
    depositAmount: '定金金额',
    paymentReference: '转账备注',
    depositPolicyNote: '按店铺设置支付定金 — 扫码或转账并填写备注。',
    productDescriptionTitle: '产品描述',
    productDetailImagesTitle: '细节图片',
    productVideoTitle: '产品视频',
    favoriteAdd: '加入收藏',
    favoriteRemove: '取消收藏',
    wishlistTitle: '收藏',
    wishlistEmpty: '暂无收藏商品。',
    recentlyViewedTitle: '最近浏览',
    recentlyViewedEmpty: '暂无浏览记录。',
    chatOpenLabel: '打开聊天',
    chatCloseLabel: '关闭',
    chatFullPageLabel: '全页打开',
    chatLanguageLabel: '语言',
    navAccount: '账户',
    accountEditProfile: '编辑资料',
    accountViewedProducts: '浏览记录',
    accountAddressBook: '地址簿',
    accountEmailLabel: '邮箱',
    accountSave: '保存更改',
    accountSaved: '资料已保存。',
    accountSaveFailed: '保存失败，请重试。',
    addressesHint: '结账时使用的默认地址。',
    accountWelcome: '您好',
    accountQuickLinks: '快捷入口',
    accountSectionEditProfile: '编辑资料',
    orderStatusLabel: '状态',
    orderStatusAwaitingPayment: '待付款',
    orderStatusPaymentChecking: '核对付款中',
    orderStatusPaidVerified: '已付款',
    orderStatusPendingManualReview: '待确认',
    orderStatusCancelled: '已取消',
    orderShippingStatusLabel: '配送',
    orderShippingPending: '待处理',
    orderShippingConfirmed: '已确认',
    orderShippingPacking: '打包中',
    orderShippingShipping: '配送中',
    orderShippingDelivered: '已送达',
    orderShippingReturned: '已退货',
    orderShippingCancelled: '配送取消',
    orderDateLabel: '下单日期',
    orderViewPayment: '查看付款 QR',
    orderHidePayment: '隐藏付款',
    orderQuantityLabel: '数量',
    recentlyViewedClear: '清除记录',
    recentlyViewedCleared: '浏览记录已清除。',
    addressesEmptyHint: '暂无地址 — 请添加默认收货地址。',
  },
  ja: {
    navHome: 'ホーム',
    navProducts: '商品',
    navRecentlyViewed: '最近見た',
    navFavorites: 'お気に入り',
    navRecommended: 'おすすめ',
    navCart: 'カート',
    navChat: 'チャット',
    navCategories: 'カテゴリ',
    catalogTitle: 'すべての商品',
    catalogEmpty: '商品がありません。',
    loadMore: 'もっと見る',
    productDetail: '商品詳細',
    addToCart: 'カートに追加',
    buyNow: '今すぐ購入',
    addedToCart: 'カートに追加しました。',
    consultChat: 'チャット相談',
    cartTitle: 'ショッピングカート',
    cartEmpty: 'カートは空です。',
    cartSubtotal: '小計',
    cartCheckout: 'レジに進む',
    cartCheckingOut: '注文処理中…',
    cartRemove: '削除',
    checkoutName: '氏名',
    checkoutPhone: '電話番号',
    checkoutAddress: '配送先',
    checkoutNote: 'メモ',
    checkoutSuccess: '注文を受け付けました — ショップから連絡があります。',
    checkoutAuthRequired: '続行するにはログインしてください。',
    checkoutGuestHint: 'ログイン不要で注文できます — 配送情報を入力してください。',
    checkoutAuthLink: 'ショップチャットでログイン/認証',
    quantity: '数量',
    backToShop: '買い物を続ける',
    navOrders: '注文',
    sizeLabel: 'サイズ',
    colorLabel: '色',
    searchPlaceholder: '商品を検索…',
    searchButton: '検索',
    searchByImage: '画像で検索',
    searchSearching: '検索中…',
    searchResults: '検索結果',
    searchEmpty: '該当する商品がありません。',
    searchError: '検索に失敗しました。',
    relatedProducts: '関連商品',
    tryOnLink: 'AI試着',
    ordersTitle: '注文履歴',
    ordersEmpty: '注文はまだありません。',
    authSendOtp: 'OTP送信',
    authVerifyOtp: '確認',
    authSuccess: 'メール確認済み — 決済できます。',
    authFailed: '確認に失敗しました。',
    authOtpSent: 'OTPをメールに送信しました。',
    authEmailLogin: 'メールでログイン',
    authChangeEmail: '別のメールを使う',
    authEmailRequired: 'メールアドレスを入力してください。',
    authGoogleLogin: 'Googleでログイン',
    authShopOtpOr: 'またはメールでコードを受け取る',
    authLoginSubtitle: 'Google またはメール OTP',
    authQuickLoginFailed: 'ログインできません — 下のメール OTP をお試しください。',
    authNanoAiLoginHint: 'メールアドレスを入力 — OTPコードをメールで受け取ります。',
    authRememberDevice: 'この端末でログイン状態を保持（次回 OTP 省略の場合あり）。',
    orderIdLabel: '注文ID',
    depositAmount: 'デポジット',
    paymentReference: '振込参照',
    depositPolicyNote: 'ショップ設定に従いデポジットをお支払いください。',
    productDescriptionTitle: '商品説明',
    productDetailImagesTitle: '詳細画像',
    productVideoTitle: '商品動画',
    favoriteAdd: 'お気に入りに追加',
    favoriteRemove: 'お気に入りから削除',
    wishlistTitle: 'お気に入り',
    wishlistEmpty: 'お気に入りはまだありません。',
    recentlyViewedTitle: '最近見た商品',
    recentlyViewedEmpty: '閲覧履歴はありません。',
    chatOpenLabel: 'チャットを開く',
    chatCloseLabel: '閉じる',
    chatFullPageLabel: '全画面で開く',
    chatLanguageLabel: '言語',
    navAccount: 'アカウント',
    accountEditProfile: 'プロフィール編集',
    accountViewedProducts: '閲覧履歴',
    accountAddressBook: '住所録',
    accountEmailLabel: 'メール',
    accountSave: '変更を保存',
    accountSaved: 'プロフィールを保存しました。',
    accountSaveFailed: '保存できませんでした。もう一度お試しください。',
    addressesHint: '決済時に使用する既定の住所。',
    accountWelcome: 'こんにちは',
    accountQuickLinks: 'クイックリンク',
    accountSectionEditProfile: 'プロフィール編集',
    orderStatusLabel: 'ステータス',
    orderStatusAwaitingPayment: '支払い待ち',
    orderStatusPaymentChecking: '支払い確認中',
    orderStatusPaidVerified: '支払い済み',
    orderStatusPendingManualReview: '確認待ち',
    orderStatusCancelled: 'キャンセル',
    orderShippingStatusLabel: '配送',
    orderShippingPending: '処理待ち',
    orderShippingConfirmed: '確認済み',
    orderShippingPacking: '梱包中',
    orderShippingShipping: '配送中',
    orderShippingDelivered: '配達完了',
    orderShippingReturned: '返品',
    orderShippingCancelled: '配送キャンセル',
    orderDateLabel: '注文日',
    orderViewPayment: 'QR / 支払いを見る',
    orderHidePayment: '支払いを隠す',
    orderQuantityLabel: '数量',
    recentlyViewedClear: '履歴を削除',
    recentlyViewedCleared: '閲覧履歴を削除しました。',
    addressesEmptyHint: '住所がありません — 既定の配送先を追加してください。',
  },
  ko: {
    navHome: '홈',
    navProducts: '상품',
    navRecentlyViewed: '최근 본',
    navFavorites: '찜',
    navRecommended: '추천',
    navCart: '장바구니',
    navChat: '채팅',
    navCategories: '카테고리',
    catalogTitle: '전체 상품',
    catalogEmpty: '상품이 없습니다.',
    loadMore: '더 보기',
    productDetail: '상품 상세',
    addToCart: '장바구니 담기',
    buyNow: '바로 구매',
    addedToCart: '장바구니에 담았습니다.',
    consultChat: '채팅 상담',
    cartTitle: '장바구니',
    cartEmpty: '장바구니가 비었습니다.',
    cartSubtotal: '소계',
    cartCheckout: '결제',
    cartCheckingOut: '주문 처리 중…',
    cartRemove: '삭제',
    checkoutName: '이름',
    checkoutPhone: '전화번호',
    checkoutAddress: '배송 주소',
    checkoutNote: '메모',
    checkoutSuccess: '주문이 접수되었습니다 — 곧 연락드립니다.',
    checkoutAuthRequired: '계속하려면 로그인해 주세요.',
    checkoutGuestHint: '로그인 없이 주문할 수 있습니다 — 배송 정보만 입력하세요.',
    checkoutAuthLink: '샵 채팅에서 로그인/인증',
    quantity: '수량',
    backToShop: '쇼핑 계속',
    navOrders: '주문',
    sizeLabel: '사이즈',
    colorLabel: '색상',
    searchPlaceholder: '상품 검색…',
    searchButton: '검색',
    searchByImage: '이미지로 검색',
    searchSearching: '검색 중…',
    searchResults: '검색 결과',
    searchEmpty: '일치하는 상품이 없습니다.',
    searchError: '검색에 실패했습니다.',
    relatedProducts: '관련 상품',
    tryOnLink: 'AI 피팅',
    ordersTitle: '내 주문',
    ordersEmpty: '주문이 없습니다.',
    authSendOtp: 'OTP 전송',
    authVerifyOtp: '인증',
    authSuccess: '이메일 인증 완료 — 결제 가능합니다.',
    authFailed: '인증 실패. 다시 시도하세요.',
    authOtpSent: 'OTP가 이메일로 전송되었습니다.',
    authEmailLogin: '이메일로 로그인',
    authChangeEmail: '다른 이메일 사용',
    authEmailRequired: '이메일을 입력해 주세요.',
    authGoogleLogin: 'Google로 로그인',
    authShopOtpOr: '또는 이메일로 코드 받기',
    authLoginSubtitle: 'Google 또는 이메일 OTP',
    authQuickLoginFailed: '로그인할 수 없습니다 — 아래 이메일 OTP를 사용하세요.',
    authNanoAiLoginHint: '이메일 입력 — OTP 코드를 이메일로 받습니다.',
    authRememberDevice: '이 기기에 로그인 유지(다음에 OTP 생략될 수 있음).',
    orderIdLabel: '주문 ID',
    depositAmount: '보증금',
    paymentReference: '입금 참조',
    depositPolicyNote: '샵 설정에 따른 보증금 — QR 또는 참조번호로 입금.',
    productDescriptionTitle: '상품 설명',
    productDetailImagesTitle: '상세 이미지',
    productVideoTitle: '상품 영상',
    favoriteAdd: '찜하기',
    favoriteRemove: '찜 해제',
    wishlistTitle: '찜',
    wishlistEmpty: '찜한 상품이 없습니다.',
    recentlyViewedTitle: '최근 본 상품',
    recentlyViewedEmpty: '최근 본 상품이 없습니다.',
    chatOpenLabel: '채팅 열기',
    chatCloseLabel: '닫기',
    chatFullPageLabel: '전체 페이지 열기',
    chatLanguageLabel: '언어',
    navAccount: '계정',
    accountEditProfile: '프로필 수정',
    accountViewedProducts: '최근 본 상품',
    accountAddressBook: '주소록',
    accountEmailLabel: '이메일',
    accountSave: '변경 저장',
    accountSaved: '프로필이 저장되었습니다.',
    accountSaveFailed: '저장하지 못했습니다. 다시 시도하세요.',
    addressesHint: '결제 시 사용하는 기본 주소입니다.',
    accountWelcome: '안녕하세요',
    accountQuickLinks: '빠른 메뉴',
    accountSectionEditProfile: '프로필 수정',
    orderStatusLabel: '상태',
    orderStatusAwaitingPayment: '결제 대기',
    orderStatusPaymentChecking: '결제 확인 중',
    orderStatusPaidVerified: '결제 완료',
    orderStatusPendingManualReview: '확인 대기',
    orderStatusCancelled: '취소됨',
    orderShippingStatusLabel: '배송',
    orderShippingPending: '처리 대기',
    orderShippingConfirmed: '확인됨',
    orderShippingPacking: '포장 중',
    orderShippingShipping: '배송 중',
    orderShippingDelivered: '배송 완료',
    orderShippingReturned: '반품',
    orderShippingCancelled: '배송 취소',
    orderDateLabel: '주문일',
    orderViewPayment: 'QR / 결제 보기',
    orderHidePayment: '결제 숨기기',
    orderQuantityLabel: '수량',
    recentlyViewedClear: '기록 삭제',
    recentlyViewedCleared: '최근 본 기록을 삭제했습니다.',
    addressesEmptyHint: '주소 없음 — 기본 배송 주소를 추가하세요.',
  },
}

export function getPartnerSiteShopCopy(locale: WebLocale): PartnerSiteShopCopy {
  return COPY[locale] ?? COPY.en
}
