import assert from 'node:assert/strict'
import test from 'node:test'
import {
  injectPartnerShopChromeLayoutCss,
  stripVisualEditorRuntimeStateClasses,
  PARTNER_SHOP_CHROME_LAYOUT_STYLE_ID,
  PARTNER_SHOP_LOGO_HOST_SCRIPT,
} from '@/lib/partner-website/shop/partner-shop-chrome-layout-css'

test('chrome layout css is injected once before </head>', () => {
  const html = '<!DOCTYPE html><html><head><title>Shop</title></head><body><nav class="pw-shop-bottom-nav"></nav></body></html>'
  const once = injectPartnerShopChromeLayoutCss(html)
  const twice = injectPartnerShopChromeLayoutCss(once)
  assert.equal(once.includes(PARTNER_SHOP_CHROME_LAYOUT_STYLE_ID), true)
  assert.equal(once.includes('data-pw-chat-icon-logo'), true)
  assert.equal(once.includes('[data-pw-chrome-btn="chat"] .pw-chrome-chat-logo'), true)
  assert.equal(once.includes('--pw-chrome-size:22px'), true)
  assert.equal(once.includes('--pw-chrome-label:calc(var(--pw-chrome-size,22px)*13/22)'), true)
  assert.equal(once.includes('font-size:var(--pw-chrome-label,13px)!important'), true)
  assert.equal(once.includes(':not(.pw-chrome-icon-only)'), true)
  assert.equal(once.includes('[data-pw-chrome-btn="chat-zalo"] .pw-chrome-icon-wrap'), true)
  assert.equal(once.includes('border-radius:999px!important'), true)
  assert.equal(once.includes('.pw-chrome-icon-square'), true)
  assert.equal(once.includes('border-radius:10px!important'), true)
  assert.equal(once.includes('data-pw-chrome-float'), true)
  assert.equal(once.includes('z-index:9999!important'), true)
  assert.equal(once.includes('pw-shop-chrome-float'), true)
  assert.equal(once.includes('pw-chrome-topup-on'), true)
  assert.equal(once.includes('flex-direction:row'), true)
  assert.equal(once.includes('pw-chrome-label-below'), true)
  assert.equal(once.includes('.pw-chrome-label-left'), true)
  assert.equal(once.includes('pw-chrome-label-left'), true)
  assert.match(once, /\.pw-chrome-label-left[^{]*\{[^}]*flex-direction:row!important/)
  assert.equal(once.includes('.pw-header-actions [data-pw-chrome-added]'), true)
  assert.equal(once.includes('.pw-header-search,.pw-shop-search-wrap'), true)
  assert.equal(once.includes(':not([data-pw-el="search"]):not(.pw-header-search):not(.pw-shop-search-wrap)'), true)
  assert.equal(once.includes('min-width:72px!important'), true)
  assert.equal(once.includes('min-width:96px'), true)
  assert.equal(once.includes("el.getAttribute('data-pw-user-move'))return"), true)
  assert.equal(once.includes('isFloatChrome'), true)
  assert.equal(once.includes("el.getAttribute('data-pw-chrome-float')==='1'"), true)
  assert.equal(once.includes("return k==='topup';"), false)
  assert.equal(once.includes("return k==='chat'||k==='chat-zalo'||k==='chat-facebook'||k==='topup';"), true)
  assert.equal(once.includes('if(isFloatChrome(el))return'), true)
  assert.equal(once.includes('[data-pw-chrome-float="1"].pw-chrome-icon-only'), true)
  assert.equal(once.includes('.pw-header-search[data-pw-user-move],.pw-shop-search-wrap[data-pw-user-move]'), true)
  assert.equal(once.includes('flex:1 1 0%'), true)
  assert.equal(once.includes('data-pw-search-width'), true)
  assert.equal(once.includes('pw-shop-search-submit-icon'), true)
  assert.equal(once.includes('content:""!important'), true)
  assert.equal(once.includes('transform:none!important'), true)
  assert.equal(once.includes('pw-shop-chrome-inset'), true)
  assert.equal(once.includes('html,body{overflow-x:hidden!important'), true)
  assert.equal(once.includes('z-index:200'), true)
  assert.equal(once.includes('.pw-topbar,.pw-shop-topbar'), true)
  assert.equal(once.includes('z-index:180'), true)
  assert.equal(once.includes('position:fixed!important'), true)
  assert.equal(once.includes('z-index:160'), true)
  assert.equal(once.includes('min-width:0;position:relative!important;max-width:none!important'), true)
  assert.equal(once.includes('data-pw-logo-frame'), true)
  assert.equal(once.includes('data-pw-logo-float'), true)
  assert.equal(once.includes('data-pw-logo-empty'), true)
  assert.equal(once.includes('.pw-logo-frame:not([data-pw-logo-float="1"]) ~ .pw-logo-frame:not([data-pw-logo-float="1"])'), true)
  assert.equal(once.includes('[data-pw-logo-float="1"]:not([data-pw-z])'), true)
  assert.equal(once.includes('[data-pw-chrome-badge][hidden]'), true)
  assert.equal(once.includes('-webkit-text-fill-color'), true)
  assert.equal(once.includes('overflow:visible!important'), true)
  assert.equal(once.includes('.pw-shop-brand-cluster{pointer-events:none!important}'), true)
  assert.equal(once.includes('.pw-shop-brand-cluster > *'), true)
  assert.equal(once.includes('pointer-events:auto!important'), true)
  assert.equal(once.includes('data-pw-device="mobile"'), true)
  assert.equal(once.includes('data-pw-device="tablet"'), true)
  assert.equal(once.includes('data-pw-device="laptop"'), true)
  assert.equal(once.includes(':not([data-pw-chrome-count])'), true)
  assert.equal(once.includes('min-width:768px'), true)
  assert.equal(once.includes('min-width:1280px'), true)
  assert.equal(once.includes('max-width:1279px'), true)
  assert.equal(once.includes('white-space:normal'), true)
  assert.equal(once.includes('flex-wrap:nowrap'), true)
  assert.equal(once.includes('max-width:1439px'), true)
  assert.equal(once.includes('flex-direction:column!important'), true)
  assert.equal(once.includes('.pw-nav-main>a.pw-nav-sale'), true)
  assert.equal(once.includes('color:#374151!important'), true)
  assert.equal(once.includes('pw-shop-chrome-badge-pin'), true)
  assert.equal(once.includes('pw-shop-stick-header'), true)
  assert.equal(once.includes('pw-shop-logo-host'), true)
  assert.equal(PARTNER_SHOP_LOGO_HOST_SCRIPT.includes("el.style.setProperty('left','0px','important')"), true)
  assert.equal(PARTNER_SHOP_LOGO_HOST_SCRIPT.includes('getBoundingClientRect'), false)
  assert.equal(once.includes('data-pw-stick-header'), true)
  assert.equal(once.includes('__pwStickHeaderSync'), true)
  assert.equal(twice, once)
  const stale = once.replace('flex-direction:row', 'flex-direction:column')
  const refreshed = injectPartnerShopChromeLayoutCss(stale)
  assert.equal(refreshed.includes('flex-direction:row'), true)
  assert.equal((refreshed.match(/id="pw-shop-chrome-layout"/g) || []).length, 1)
  const duped = `${once}<style id="pw-shop-chrome-layout">.old{}</style>`
  const collapsed = injectPartnerShopChromeLayoutCss(duped)
  assert.equal((collapsed.match(/id="pw-shop-chrome-layout"/g) || []).length, 1)
  assert.equal(collapsed.includes('flex:1 1 0%'), true)
  assert.equal(collapsed.includes('data-pw-search-width'), true)
})

test('saved html never keeps the editor runtime state on <body>', () => {
  const saved =
    '<!DOCTYPE html><html><head></head><body class="antialiased nanoai-ve-mobile nanoai-ve-active" data-pw-bg-role="canvas"><header class="pw-shop-header"></header></body></html>'
  const out = injectPartnerShopChromeLayoutCss(saved)
  assert.equal(/<body[^>]*\bnanoai-ve-active\b/.test(out), false)
  // Device isolation classes and other body attributes must survive.
  assert.equal(out.includes('nanoai-ve-mobile'), true)
  assert.equal(out.includes('antialiased'), true)
  assert.equal(out.includes('data-pw-bg-role="canvas"'), true)

  const onlyState = stripVisualEditorRuntimeStateClasses('<body class="nanoai-ve-active"><p>x</p></body>')
  assert.equal(onlyState.includes('class='), false)
  assert.equal(onlyState.includes('<p>x</p>'), true)

  const clean = '<body class="antialiased"><p>x</p></body>'
  assert.equal(stripVisualEditorRuntimeStateClasses(clean), clean)
})
