import type { Metadata } from 'next'
import { redirectToLogin } from '@/lib/auth/login-redirect'
import { getUserOrBypass } from '@/lib/auth'
import { getCurrentWebLocale } from '@/lib/i18n/server'
import { buildMetadata } from '@/lib/seo'
import { getUserAiApiKeyPublicRow } from '@/lib/db/user-ai-api-keys-pg'
import { CustomerApiKeysClient, type CustomerApiKeysCopy } from './customer-api-keys-client'
import { getByokSubscriptionForUser, listByokPlanPaymentsForUser } from '@/lib/db/user-ai-api-key-billing-pg'

export function generateMetadata(): Metadata {
  const copy = copyForLocale(getCurrentWebLocale())
  return buildMetadata({
    title: copy.title,
    description: copy.subtitle,
    path: '/dashboard/customer-api-keys',
    noIndex: true,
  })
}

function copyForLocale(locale: string): CustomerApiKeysCopy {
  if (locale === 'en') {
    return {
      title: 'Rent AI platform',
      subtitle: 'Rent the NanoAI platform and use your own Gemini key for AI tools, workflows, and storage.',
      overviewTitle: 'How it works',
      overviewBody: 'When enabled, supported AI requests use your Gemini API key first. If no valid user key is available, the server key can still be used where the feature allows it.',
      geminiTitle: 'Gemini API key',
      geminiDescription: 'The key is encrypted before storage and is never shown again after saving.',
      apiKeyLabel: 'Google AI Studio API key',
      apiKeyPlaceholder: 'Paste your Gemini API key',
      saveAndCheck: 'Save and test',
      checkConnection: 'Test connection',
      deleteKey: 'Delete key',
      enabled: 'Enabled',
      noKey: 'No Gemini API key has been saved yet.',
      keyHint: 'Saved key',
      status: 'Status',
      valid: 'Valid',
      invalid: 'Invalid',
      unchecked: 'Unchecked',
      lastChecked: 'Last checked',
      lastError: 'Last error',
      guideTitle: 'How to get a Gemini key',
      guideSteps: ['Open Google AI Studio.', 'Create or select an API key.', 'Enable billing if Google asks for it.', 'Paste the key here and test the connection.'],
      securityTitle: 'Security notes',
      securityItems: ['The full key is encrypted in the database.', 'The page only shows a masked hint.', 'You can disable or delete the key anytime.', 'Never share the key in chat or screenshots.'],
      scopeTitle: 'Current scope',
      scopeBody: 'This first version focuses on Gemini/Google AI calls that run with a logged-in user context. Background workers without a user continue to use the server key.',
      apiFeeTitle: 'Important: API usage fees are not included',
      apiFeeBody: 'The plan price below is the NanoAI platform fee only. You provide your own Gemini API key, and Google bills all Gemini usage directly to your Google Cloud/AI Studio account according to Google pricing. NanoAI does not include Gemini credits, quota, or API charges.',
      includedFeaturesTitle: 'Features currently included',
      includedFeaturesSubtitle: 'Your key is used only by the supported Gemini flows listed below. All plans currently have the same technical feature coverage.',
      includedFeatures: [
        'AI image tools: generate, edit, combine, restore, enhance, remove backgrounds or objects, replace product backgrounds, and create banners, logos, labels, packaging, portraits, ID photos, invitations, interior/exterior designs, and related images.',
        'Virtual try-on for signed-in user flows.',
        'AI language learning: Gemini conversation chat.',
        'Generate and verify slide quizzes in integrated flows.',
        'Encrypted API key storage and the ability to disable or delete the key at any time.',
      ],
      notIncludedTitle: 'Not currently using your key',
      notIncludedFeatures: [
        'Curriculum, worksheet, and slide-generation workflows not listed above.',
        'Veo video, textbook infographic, background workers, and automated shop messaging.',
        'TTS, OpenAI, DeepSeek, Pexels, or any non-Gemini provider usage.',
      ],
      pricingTitle: 'BYOK monthly plans',
      pricingSubtitle: 'First month 30% off. You pay the AI provider directly for API usage.',
      firstMonthSaleBadge: '30% off first month',
      originalPriceLabel: 'Regular',
      firstMonthPriceLabel: 'First month promo price',
      perMonthLabel: '/ month',
      choosePlan: 'Choose plan',
      pricingNote: 'You are paying only for access to the NanoAI platform. Gemini API charges are separate and are paid by you directly to Google.',
      currentPlanTitle: 'Current BYOK subscription',
      noActivePlan: 'No active BYOK plan yet. Choose a plan below to activate your own API key for AI calls.',
      activeUntil: 'Active until',
      pendingPaymentTitle: 'Pending payment',
      transferContent: 'Transfer content',
      paymentAmount: 'Amount',
      scanQr: 'Scan QR to pay',
      paymentAutoActivateHint:
        'When your transfer matches the amount and transfer content, SePay notifies us and your BYOK plan turns on automatically—usually within seconds or a few minutes. Use the button below only if this page has not updated yet.',
      refreshPaymentStatus: 'Refresh payment status',
      paymentCompleted: 'Payment completed. Your BYOK plan is active.',
      plans: [
        { id: 'basic', name: 'BYOK Basic', audience: 'Individuals and light use', monthlyPriceVnd: 199000, features: ['All currently supported features', 'Use your own Gemini key', 'Encrypted key storage', 'Basic support'] },
        { id: 'pro', name: 'BYOK Pro', audience: 'Power users, teachers, shops', monthlyPriceVnd: 299000, recommended: true, features: ['All currently supported features', 'Use your own Gemini key', 'Encrypted key storage', 'Priority support'] },
        { id: 'business', name: 'BYOK Business', audience: 'Teams, agencies, small businesses', monthlyPriceVnd: 699000, features: ['All currently supported features', 'Encrypted key storage', 'Onboarding support', 'Business workflow consultation'] },
      ],
      successSaved: 'API key saved.',
      successChecked: 'Connection works.',
      successDeleted: 'API key deleted.',
      successUpdated: 'Setting updated.',
    }
  }
  if (locale === 'zh') {
    return {
      title: '租用 AI 平台',
      subtitle: '租用 NanoAI 平台，并使用你自己的 Gemini 密钥运行 AI 工具、工作流和存储。',
      overviewTitle: '工作方式',
      overviewBody: '启用后，支持的 AI 请求会优先使用你的 Gemini API 密钥。如果没有有效的用户密钥，允许的功能仍可回退到服务器密钥。',
      geminiTitle: 'Gemini API 密钥',
      geminiDescription: '密钥会先加密再保存，保存后不会再次完整显示。',
      apiKeyLabel: 'Google AI Studio API 密钥',
      apiKeyPlaceholder: '粘贴你的 Gemini API 密钥',
      saveAndCheck: '保存并测试',
      checkConnection: '测试连接',
      deleteKey: '删除密钥',
      enabled: '已启用',
      noKey: '尚未保存 Gemini API 密钥。',
      keyHint: '已保存密钥',
      status: '状态',
      valid: '有效',
      invalid: '无效',
      unchecked: '未检查',
      lastChecked: '上次检查',
      lastError: '最近错误',
      guideTitle: '如何获取 Gemini 密钥',
      guideSteps: ['打开 Google AI Studio。', '创建或选择一个 API 密钥。', '如果 Google 要求，请启用结算。', '将密钥粘贴到这里并测试连接。'],
      securityTitle: '安全说明',
      securityItems: ['完整密钥会在数据库中加密保存。', '页面只显示掩码提示。', '你可以随时停用或删除密钥。', '不要在聊天或截图中分享密钥。'],
      scopeTitle: '当前范围',
      scopeBody: '第一版聚焦于带登录用户上下文运行的 Gemini/Google AI 调用。没有用户上下文的后台任务继续使用服务器密钥。',
      apiFeeTitle: '重要：套餐不包含 API 使用费',
      apiFeeBody: '下方价格仅为 NanoAI 平台服务费。你需要提供自己的 Gemini API 密钥，所有 Gemini 用量由 Google 按其价格直接向你的 Google Cloud/AI Studio 账户收费。NanoAI 不提供 Gemini 点数、额度或 API 费用。',
      includedFeaturesTitle: '当前包含的功能',
      includedFeaturesSubtitle: '你的密钥只用于下列已支持的 Gemini 流程。目前所有套餐的技术功能范围相同。',
      includedFeatures: [
        'AI 图片工具：生成、编辑、拼接、修复、增强、去背景或物体、替换商品背景，以及制作横幅、Logo、标签、包装、人像、证件照、邀请函、室内外设计等图片。',
        '登录用户流程中的虚拟试穿。',
        'AI 语言学习中的 Gemini 对话聊天。',
        '在已集成流程中生成和检查幻灯片测验。',
        'API 密钥加密保存，并可随时停用或删除。',
      ],
      notIncludedTitle: '目前不会使用你的密钥',
      notIncludedFeatures: [
        '上方未列出的课程、练习表和幻灯片生成流程。',
        'Veo 视频、教材信息图、后台任务和店铺自动消息。',
        'TTS、OpenAI、DeepSeek、Pexels 或任何非 Gemini 服务。',
      ],
      pricingTitle: 'BYOK 月度套餐',
      pricingSubtitle: '首月优惠 30%。API 使用费用由你的 AI 服务商账户直接收取。',
      firstMonthSaleBadge: '首月减 30%',
      originalPriceLabel: '原价',
      firstMonthPriceLabel: '首月优惠价',
      perMonthLabel: '/ 月',
      choosePlan: '选择套餐',
      pricingNote: '你支付的仅是 NanoAI 平台使用费。Gemini API 费用另计，并由你直接向 Google 支付。',
      currentPlanTitle: '当前 BYOK 订阅',
      noActivePlan: '尚无有效 BYOK 套餐。请选择一个套餐以启用自带 API 密钥。',
      activeUntil: '有效期至',
      pendingPaymentTitle: '待支付',
      transferContent: '转账备注',
      paymentAmount: '金额',
      scanQr: '扫码支付',
      paymentAutoActivateHint:
        '转账金额与备注完全一致后，SePay 会通知系统并自动开通 BYOK 套餐，通常在几秒到几分钟内。若页面未更新可点击下方按钮刷新。',
      refreshPaymentStatus: '刷新支付状态',
      paymentCompleted: '支付已完成，BYOK 套餐已启用。',
      plans: [
        { id: 'basic', name: 'BYOK Basic', audience: '个人和轻度使用', monthlyPriceVnd: 199000, features: ['当前所有支持功能', '使用自己的 Gemini 密钥', '密钥加密保存', '基础支持'] },
        { id: 'pro', name: 'BYOK Pro', audience: '高频用户、教师、店铺', monthlyPriceVnd: 299000, recommended: true, features: ['当前所有支持功能', '使用自己的 Gemini 密钥', '密钥加密保存', '优先支持'] },
        { id: 'business', name: 'BYOK Business', audience: '团队、代理、小企业', monthlyPriceVnd: 699000, features: ['当前所有支持功能', '密钥加密保存', '上线协助', '业务流程咨询'] },
      ],
      successSaved: 'API 密钥已保存。',
      successChecked: '连接正常。',
      successDeleted: 'API 密钥已删除。',
      successUpdated: '设置已更新。',
    }
  }
  if (locale === 'ja') {
    return {
      title: 'AI プラットフォーム利用',
      subtitle: 'NanoAI プラットフォームを利用し、自分の Gemini キーで AI ツール、ワークフロー、保存機能を使えます。',
      overviewTitle: '仕組み',
      overviewBody: '有効にすると、対応する AI リクエストはまずあなたの Gemini API キーを使います。有効なユーザーキーがない場合、許可された機能ではサーバーキーに戻ります。',
      geminiTitle: 'Gemini API キー',
      geminiDescription: 'キーは保存前に暗号化され、保存後に全文が表示されることはありません。',
      apiKeyLabel: 'Google AI Studio API キー',
      apiKeyPlaceholder: 'Gemini API キーを貼り付け',
      saveAndCheck: '保存してテスト',
      checkConnection: '接続テスト',
      deleteKey: 'キーを削除',
      enabled: '有効',
      noKey: 'Gemini API キーはまだ保存されていません。',
      keyHint: '保存済みキー',
      status: '状態',
      valid: '有効',
      invalid: '無効',
      unchecked: '未確認',
      lastChecked: '最終確認',
      lastError: '直近のエラー',
      guideTitle: 'Gemini キーの取得方法',
      guideSteps: ['Google AI Studio を開きます。', 'API キーを作成または選択します。', 'Google が求める場合は請求を有効にします。', 'ここにキーを貼り付けて接続をテストします。'],
      securityTitle: 'セキュリティ',
      securityItems: ['完全なキーはデータベースで暗号化されます。', '画面にはマスクされたヒントだけ表示されます。', 'いつでも無効化または削除できます。', 'チャットやスクリーンショットでキーを共有しないでください。'],
      scopeTitle: '現在の適用範囲',
      scopeBody: '初版ではログインユーザーの文脈で動く Gemini/Google AI 呼び出しを対象にします。ユーザー文脈のないバックグラウンド処理はサーバーキーを使い続けます。',
      apiFeeTitle: '重要：API 利用料はプラン料金に含まれません',
      apiFeeBody: '下記料金は NanoAI プラットフォーム利用料のみです。Gemini API キーはご自身で用意し、Gemini の利用料は Google の料金に従って Google Cloud/AI Studio アカウントへ直接請求されます。NanoAI は Gemini クレジット、割り当て、API 料金を提供しません。',
      includedFeaturesTitle: '現在含まれる機能',
      includedFeaturesSubtitle: 'あなたのキーは、以下の対応済み Gemini フローでのみ使われます。現在、すべてのプランで技術的な機能範囲は同じです。',
      includedFeatures: [
        'AI 画像ツール：生成、編集、合成、修復、高画質化、背景・物体除去、商品背景変更、バナー、ロゴ、ラベル、パッケージ、人物、証明写真、招待状、内外装などの画像作成。',
        'ログインユーザー向けフローのバーチャル試着。',
        'AI 語学学習の Gemini 会話チャット。',
        '対応済みフローでのスライドクイズ生成・検証。',
        'API キーの暗号化保存と、いつでも無効化・削除できる機能。',
      ],
      notIncludedTitle: '現在あなたのキーを使わない機能',
      notIncludedFeatures: [
        '上記にない教材、ワークシート、スライド生成フロー。',
        'Veo 動画、教科書インフォグラフィック、バックグラウンド処理、店舗の自動メッセージ。',
        'TTS、OpenAI、DeepSeek、Pexels、その他 Gemini 以外のサービス。',
      ],
      pricingTitle: 'BYOK 月額プラン',
      pricingSubtitle: '初月 30% オフ。API 利用料は AI プロバイダー側で直接請求されます。',
      firstMonthSaleBadge: '初月 30% オフ',
      originalPriceLabel: '通常',
      firstMonthPriceLabel: '初月プロモ価格',
      perMonthLabel: '/ 月',
      choosePlan: 'プランを選択',
      pricingNote: 'お支払いは NanoAI プラットフォーム利用料のみです。Gemini API 料金は別途、お客様から Google へ直接お支払いいただきます。',
      currentPlanTitle: '現在の BYOK サブスクリプション',
      noActivePlan: '有効な BYOK プランはまだありません。プランを選ぶと自分の API キーを AI 呼び出しに使えます。',
      activeUntil: '有効期限',
      pendingPaymentTitle: '支払い待ち',
      transferContent: '振込内容',
      paymentAmount: '金額',
      scanQr: 'QR をスキャンして支払い',
      paymentAutoActivateHint:
        '金額と振込内容が一致すると、SePay から通知があり、BYOK プランは自動で有効になります（通常は数秒〜数分）。画面が更新されないときだけ下のボタンで状態を更新してください。',
      refreshPaymentStatus: '支払い状態を更新',
      paymentCompleted: '支払いが完了しました。BYOK プランが有効です。',
      plans: [
        { id: 'basic', name: 'BYOK Basic', audience: '個人・ライト利用', monthlyPriceVnd: 199000, features: ['現在対応するすべての機能', '自分の Gemini キーを利用', 'キーの暗号化保存', '基本サポート'] },
        { id: 'pro', name: 'BYOK Pro', audience: '高頻度ユーザー、教師、ショップ', monthlyPriceVnd: 299000, recommended: true, features: ['現在対応するすべての機能', '自分の Gemini キーを利用', 'キーの暗号化保存', '優先サポート'] },
        { id: 'business', name: 'BYOK Business', audience: 'チーム、代理店、小規模事業者', monthlyPriceVnd: 699000, features: ['現在対応するすべての機能', 'キーの暗号化保存', 'オンボーディング支援', '業務フロー相談'] },
      ],
      successSaved: 'API キーを保存しました。',
      successChecked: '接続できました。',
      successDeleted: 'API キーを削除しました。',
      successUpdated: '設定を更新しました。',
    }
  }
  if (locale === 'ko') {
    return {
      title: 'AI 플랫폼 임대',
      subtitle: 'NanoAI 플랫폼을 이용하고 내 Gemini 키로 AI 도구, 워크플로, 저장 기능을 사용합니다.',
      overviewTitle: '작동 방식',
      overviewBody: '활성화하면 지원되는 AI 요청은 먼저 사용자의 Gemini API 키를 사용합니다. 유효한 사용자 키가 없으면 허용된 기능에서 서버 키로 돌아갈 수 있습니다.',
      geminiTitle: 'Gemini API 키',
      geminiDescription: '키는 저장 전에 암호화되며 저장 후 전체 키는 다시 표시되지 않습니다.',
      apiKeyLabel: 'Google AI Studio API 키',
      apiKeyPlaceholder: 'Gemini API 키 붙여넣기',
      saveAndCheck: '저장 및 테스트',
      checkConnection: '연결 테스트',
      deleteKey: '키 삭제',
      enabled: '사용',
      noKey: '아직 저장된 Gemini API 키가 없습니다.',
      keyHint: '저장된 키',
      status: '상태',
      valid: '유효',
      invalid: '무효',
      unchecked: '미확인',
      lastChecked: '마지막 확인',
      lastError: '최근 오류',
      guideTitle: 'Gemini 키 받는 방법',
      guideSteps: ['Google AI Studio를 엽니다.', 'API 키를 만들거나 선택합니다.', 'Google에서 요구하면 결제를 활성화합니다.', '여기에 키를 붙여넣고 연결을 테스트합니다.'],
      securityTitle: '보안 안내',
      securityItems: ['전체 키는 데이터베이스에 암호화되어 저장됩니다.', '페이지에는 마스킹된 힌트만 표시됩니다.', '언제든지 비활성화하거나 삭제할 수 있습니다.', '채팅이나 스크린샷으로 키를 공유하지 마세요.'],
      scopeTitle: '현재 범위',
      scopeBody: '첫 버전은 로그인 사용자 컨텍스트가 있는 Gemini/Google AI 호출에 집중합니다. 사용자 컨텍스트가 없는 백그라운드 작업은 서버 키를 계속 사용합니다.',
      apiFeeTitle: '중요: API 사용료는 요금제에 포함되지 않습니다',
      apiFeeBody: '아래 가격은 NanoAI 플랫폼 이용료만 포함합니다. Gemini API 키는 고객이 직접 제공하며, 모든 Gemini 사용량은 Google 요금에 따라 고객의 Google Cloud/AI Studio 계정에 직접 청구됩니다. NanoAI는 Gemini 크레딧, 할당량 또는 API 비용을 제공하지 않습니다.',
      includedFeaturesTitle: '현재 포함된 기능',
      includedFeaturesSubtitle: '고객 키는 아래의 지원되는 Gemini 흐름에서만 사용됩니다. 현재 모든 요금제의 기술 기능 범위는 같습니다.',
      includedFeatures: [
        'AI 이미지 도구: 생성, 편집, 합성, 복원, 보정, 배경·개체 제거, 상품 배경 변경 및 배너, 로고, 라벨, 패키지, 인물, 증명사진, 초대장, 실내외 디자인 등의 이미지 제작.',
        '로그인 사용자 흐름의 가상 피팅.',
        'AI 언어 학습의 Gemini 대화 채팅.',
        '통합된 흐름에서 슬라이드 퀴즈 생성 및 검증.',
        'API 키 암호화 저장 및 언제든지 비활성화·삭제 가능.',
      ],
      notIncludedTitle: '현재 고객 키를 사용하지 않는 기능',
      notIncludedFeatures: [
        '위에 표시되지 않은 교재, 워크시트 및 슬라이드 생성 흐름.',
        'Veo 영상, 교과서 인포그래픽, 백그라운드 작업 및 쇼핑몰 자동 메시지.',
        'TTS, OpenAI, DeepSeek, Pexels 또는 Gemini 이외 서비스.',
      ],
      pricingTitle: 'BYOK 월간 요금제',
      pricingSubtitle: '첫 달 30% 할인. API 사용료는 AI 제공업체 계정에서 직접 청구됩니다.',
      firstMonthSaleBadge: '첫 달 30% 할인',
      originalPriceLabel: '정가',
      firstMonthPriceLabel: '첫 달 할인가',
      perMonthLabel: '/ 월',
      choosePlan: '요금제 선택',
      pricingNote: '결제 금액은 NanoAI 플랫폼 이용료만 포함합니다. Gemini API 비용은 별도이며 고객이 Google에 직접 지불합니다.',
      currentPlanTitle: '현재 BYOK 구독',
      noActivePlan: '아직 활성 BYOK 요금제가 없습니다. 요금제를 선택하면 내 API 키를 AI 호출에 사용할 수 있습니다.',
      activeUntil: '활성 기한',
      pendingPaymentTitle: '결제 대기',
      transferContent: '입금 내용',
      paymentAmount: '금액',
      scanQr: 'QR 스캔 결제',
      paymentAutoActivateHint:
        '입금 금액과 내용이 일치하면 SePay 알림으로 BYOK 요금제가 자동 활성화됩니다(보통 수초~수분). 화면이 갱신되지 않을 때만 아래 버튼을 누르세요.',
      refreshPaymentStatus: '결제 상태 새로고침',
      paymentCompleted: '결제가 완료되었습니다. BYOK 요금제가 활성화되었습니다.',
      plans: [
        { id: 'basic', name: 'BYOK Basic', audience: '개인 및 가벼운 사용', monthlyPriceVnd: 199000, features: ['현재 지원되는 모든 기능', '내 Gemini 키 사용', '키 암호화 저장', '기본 지원'] },
        { id: 'pro', name: 'BYOK Pro', audience: '고사용자, 교사, 쇼핑몰', monthlyPriceVnd: 299000, recommended: true, features: ['현재 지원되는 모든 기능', '내 Gemini 키 사용', '키 암호화 저장', '우선 지원'] },
        { id: 'business', name: 'BYOK Business', audience: '팀, 에이전시, 소규모 비즈니스', monthlyPriceVnd: 699000, features: ['현재 지원되는 모든 기능', '키 암호화 저장', '온보딩 지원', '비즈니스 워크플로 상담'] },
      ],
      successSaved: 'API 키를 저장했습니다.',
      successChecked: '연결이 정상입니다.',
      successDeleted: 'API 키를 삭제했습니다.',
      successUpdated: '설정을 업데이트했습니다.',
    }
  }
  return {
    title: 'Thuê nền tảng AI',
    subtitle: 'Thuê nền tảng NanoAI để dùng công cụ, workflow và lưu trữ; khách dùng Gemini API key riêng của mình.',
    overviewTitle: 'Cách hoạt động',
    overviewBody: 'Khi bật, các yêu cầu AI được hỗ trợ sẽ ưu tiên dùng Gemini API key của bạn. Nếu chưa có key hợp lệ, hệ thống vẫn có thể dùng key server ở những tính năng cho phép fallback.',
    geminiTitle: 'Gemini API key',
    geminiDescription: 'Key được mã hóa trước khi lưu và không bao giờ hiển thị lại đầy đủ sau khi lưu.',
    apiKeyLabel: 'Google AI Studio API key',
    apiKeyPlaceholder: 'Dán Gemini API key của bạn',
    saveAndCheck: 'Lưu và kiểm tra',
    checkConnection: 'Kiểm tra kết nối',
    deleteKey: 'Xóa key',
    enabled: 'Đang bật',
    noKey: 'Chưa lưu Gemini API key.',
    keyHint: 'Key đã lưu',
    status: 'Trạng thái',
    valid: 'Hợp lệ',
    invalid: 'Không hợp lệ',
    unchecked: 'Chưa kiểm tra',
    lastChecked: 'Kiểm tra lần cuối',
    lastError: 'Lỗi gần nhất',
    guideTitle: 'Cách lấy Gemini key',
    guideSteps: ['Mở Google AI Studio.', 'Tạo hoặc chọn một API key.', 'Bật billing nếu Google yêu cầu.', 'Dán key vào đây và kiểm tra kết nối.'],
    securityTitle: 'Lưu ý bảo mật',
    securityItems: ['Key đầy đủ được mã hóa trong database.', 'Trang chỉ hiển thị dạng che.', 'Bạn có thể tắt hoặc xóa key bất cứ lúc nào.', 'Không chia sẻ key trong chat hoặc ảnh chụp màn hình.'],
    scopeTitle: 'Phạm vi hiện tại',
    scopeBody: 'Bản đầu tập trung vào các lệnh gọi Gemini/Google AI có ngữ cảnh người dùng đăng nhập. Worker nền không có user vẫn dùng key server.',
    apiFeeTitle: 'Quan trọng: Gói thuê không bao gồm phí sử dụng API',
    apiFeeBody: 'Giá gói bên dưới chỉ là phí sử dụng nền tảng NanoAI. Khách hàng tự cung cấp Gemini API key và toàn bộ chi phí sử dụng Gemini sẽ do Google thu trực tiếp trên tài khoản Google Cloud/AI Studio của khách theo bảng giá của Google. NanoAI không cấp credit, hạn mức hoặc thanh toán phí API Gemini thay khách hàng.',
    includedFeaturesTitle: 'Các tính năng hiện có trong gói thuê',
    includedFeaturesSubtitle: 'Gemini API key của khách chỉ được dùng cho các luồng đã hỗ trợ dưới đây. Hiện tại cả ba gói có cùng phạm vi tính năng kỹ thuật.',
    includedFeatures: [
      'Công cụ ảnh AI: tạo, chỉnh sửa, ghép, phục dựng, làm đẹp/làm nét, xóa nền/vật thể, thay nền sản phẩm; tạo banner, logo, nhãn, bao bì, ảnh chân dung, ảnh thẻ, thiệp mời, thiết kế nội/ngoại thất và các công cụ ảnh liên quan.',
      'Thử đồ online trong các luồng có người dùng đăng nhập.',
      'Học ngoại ngữ AI: chat hội thoại bằng Gemini.',
      'Tạo và kiểm tra quiz slide trong các luồng đã tích hợp.',
      'Lưu API key dưới dạng mã hóa; có thể tắt hoặc xóa key bất cứ lúc nào.',
    ],
    notIncludedTitle: 'Hiện chưa dùng API key của khách',
    notIncludedFeatures: [
      'Các luồng tạo giáo trình, worksheet và slide chưa được liệt kê ở trên.',
      'Video Veo, infographic sách giáo khoa, worker nền và AI nhắn tin tự động của shop.',
      'TTS, OpenAI, DeepSeek, Pexels hoặc bất kỳ dịch vụ nào không phải Gemini.',
    ],
    pricingTitle: 'Gói BYOK theo tháng',
    pricingSubtitle: 'Sale tháng đầu giảm 30%. Khách tự thanh toán phí API trực tiếp cho nhà cung cấp AI.',
    firstMonthSaleBadge: 'Giảm 30% tháng đầu',
    originalPriceLabel: 'Giá gốc',
    firstMonthPriceLabel: 'Giá ưu đãi tháng đầu',
    perMonthLabel: '/ tháng',
    choosePlan: 'Chọn gói',
    pricingNote: 'Khách hàng chỉ thanh toán phí sử dụng nền tảng NanoAI tại đây. Phí API Gemini là khoản riêng và khách hàng tự thanh toán trực tiếp cho Google.',
    currentPlanTitle: 'Gói BYOK hiện tại',
    noActivePlan: 'Chưa có gói BYOK đang hoạt động. Chọn một gói bên dưới để bật API key riêng cho các lệnh gọi AI.',
    activeUntil: 'Hiệu lực đến',
    pendingPaymentTitle: 'Thanh toán đang chờ',
    transferContent: 'Nội dung chuyển khoản',
    paymentAmount: 'Số tiền',
    scanQr: 'Quét QR để thanh toán',
    paymentAutoActivateHint:
      'Chuyển khoản đúng số tiền và đúng nội dung (SePay sẽ khớp), máy chủ nhận thông báo và tự kích hoạt gói BYOK — thường vài giây đến vài phút. Nút bên dưới chỉ để làm mới trang nếu chưa thấy cập nhật.',
    refreshPaymentStatus: 'Làm mới trạng thái thanh toán',
    paymentCompleted: 'Thanh toán đã hoàn tất. Gói BYOK đã được kích hoạt.',
    plans: [
      { id: 'basic', name: 'BYOK Basic', audience: 'Cá nhân, dùng nhẹ', monthlyPriceVnd: 199000, features: ['Toàn bộ tính năng hiện đang hỗ trợ', 'Dùng Gemini API key riêng', 'Key được mã hóa khi lưu', 'Hỗ trợ cơ bản'] },
      { id: 'pro', name: 'BYOK Pro', audience: 'Dùng nhiều, giáo viên, shop', monthlyPriceVnd: 299000, recommended: true, features: ['Toàn bộ tính năng hiện đang hỗ trợ', 'Dùng Gemini API key riêng', 'Key được mã hóa khi lưu', 'Hỗ trợ ưu tiên'] },
      { id: 'business', name: 'BYOK Business', audience: 'Team, agency, doanh nghiệp nhỏ', monthlyPriceVnd: 699000, features: ['Toàn bộ tính năng hiện đang hỗ trợ', 'Key được mã hóa khi lưu', 'Hỗ trợ onboarding', 'Tư vấn workflow kinh doanh'] },
    ],
    successSaved: 'Đã lưu API key.',
    successChecked: 'Kết nối hoạt động.',
    successDeleted: 'Đã xóa API key.',
    successUpdated: 'Đã cập nhật cài đặt.',
  }
}

export default async function CustomerApiKeysPage() {
  const user = await getUserOrBypass()
  if (!user) redirectToLogin()
  const row = await getUserAiApiKeyPublicRow(user.id, 'google_gemini')
  const subscription = await getByokSubscriptionForUser(user.id)
  const payments = await listByokPlanPaymentsForUser(user.id, 5)
  return (
    <CustomerApiKeysClient
      initialRow={row}
      initialSubscription={subscription}
      initialPayments={payments}
      copy={copyForLocale(getCurrentWebLocale())}
    />
  )
}
