import type { Metadata } from 'next'
import { redirectToLogin } from '@/lib/auth/login-redirect'
import { getUserOrBypass } from '@/lib/auth'
import { getCurrentWebLocale } from '@/lib/i18n/server'
import { buildMetadata } from '@/lib/seo'
import { getUserAiApiKeyPublicRow } from '@/lib/db/user-ai-api-keys-pg'
import { CustomerApiKeysClient, type CustomerApiKeysCopy } from './customer-api-keys-client'
import { getByokSubscriptionForUser, listByokPlanPaymentsForUser } from '@/lib/db/user-ai-api-key-billing-pg'

export function generateMetadata(): Metadata {
  const copy = copyForLocale(getCurrentWebLocale())
  return buildMetadata({
    title: copy.title,
    description: copy.subtitle,
    path: '/dashboard/customer-api-keys',
    noIndex: true,
  })
}

function copyForLocale(locale: string): CustomerApiKeysCopy {
  if (locale === 'en') {
    return {
      title: 'Your API keys',
      subtitle: 'Use your own Gemini key for AI tools while NanoAI provides the interface and workflows.',
      overviewTitle: 'How it works',
      overviewBody: 'When enabled, supported AI requests use your Gemini API key first. If no valid user key is available, the server key can still be used where the feature allows it.',
      geminiTitle: 'Gemini API key',
      geminiDescription: 'The key is encrypted before storage and is never shown again after saving.',
      apiKeyLabel: 'Google AI Studio API key',
      apiKeyPlaceholder: 'Paste your Gemini API key',
      saveAndCheck: 'Save and test',
      checkConnection: 'Test connection',
      deleteKey: 'Delete key',
      enabled: 'Enabled',
      noKey: 'No Gemini API key has been saved yet.',
      keyHint: 'Saved key',
      status: 'Status',
      valid: 'Valid',
      invalid: 'Invalid',
      unchecked: 'Unchecked',
      lastChecked: 'Last checked',
      lastError: 'Last error',
      guideTitle: 'How to get a Gemini key',
      guideSteps: ['Open Google AI Studio.', 'Create or select an API key.', 'Enable billing if Google asks for it.', 'Paste the key here and test the connection.'],
      securityTitle: 'Security notes',
      securityItems: ['The full key is encrypted in the database.', 'The page only shows a masked hint.', 'You can disable or delete the key anytime.', 'Never share the key in chat or screenshots.'],
      scopeTitle: 'Current scope',
      scopeBody: 'This first version focuses on Gemini/Google AI calls that run with a logged-in user context. Background workers without a user continue to use the server key.',
      pricingTitle: 'BYOK monthly plans',
      pricingSubtitle: 'First month 30% off. You pay the AI provider directly for API usage.',
      firstMonthSaleBadge: '30% off first month',
      originalPriceLabel: 'Regular',
      firstMonthPriceLabel: 'First month promo price',
      perMonthLabel: '/ month',
      choosePlan: 'Choose plan',
      pricingNote: 'Platform fee only. Gemini/OpenAI usage is charged by your provider account.',
      currentPlanTitle: 'Current BYOK subscription',
      noActivePlan: 'No active BYOK plan yet. Choose a plan below to activate your own API key for AI calls.',
      activeUntil: 'Active until',
      pendingPaymentTitle: 'Pending payment',
      transferContent: 'Transfer content',
      paymentAmount: 'Amount',
      scanQr: 'Scan QR to pay',
      paymentCompleted: 'Payment completed. Your BYOK plan is active.',
      plans: [
        { id: 'basic', name: 'BYOK Basic', audience: 'Individuals and light use', monthlyPriceVnd: 199000, features: ['Use your own Gemini key', 'Core AI tools', 'Encrypted key storage', 'Basic support'] },
        { id: 'pro', name: 'BYOK Pro', audience: 'Power users, teachers, shops', monthlyPriceVnd: 299000, recommended: true, features: ['Everything in Basic', 'Higher workflow priority', 'More AI tool coverage', 'Priority support'] },
        { id: 'business', name: 'BYOK Business', audience: 'Teams, agencies, small businesses', monthlyPriceVnd: 699000, features: ['Everything in Pro', 'Team/workspace use guidance', 'Onboarding support', 'Business workflow consultation'] },
      ],
      successSaved: 'API key saved.',
      successChecked: 'Connection works.',
      successDeleted: 'API key deleted.',
      successUpdated: 'Setting updated.',
    }
  }
  if (locale === 'zh') {
    return {
      title: '我的 API 密钥',
      subtitle: '使用你自己的 Gemini 密钥运行 AI 工具，NanoAI 提供界面和工作流。',
      overviewTitle: '工作方式',
      overviewBody: '启用后，支持的 AI 请求会优先使用你的 Gemini API 密钥。如果没有有效的用户密钥，允许的功能仍可回退到服务器密钥。',
      geminiTitle: 'Gemini API 密钥',
      geminiDescription: '密钥会先加密再保存，保存后不会再次完整显示。',
      apiKeyLabel: 'Google AI Studio API 密钥',
      apiKeyPlaceholder: '粘贴你的 Gemini API 密钥',
      saveAndCheck: '保存并测试',
      checkConnection: '测试连接',
      deleteKey: '删除密钥',
      enabled: '已启用',
      noKey: '尚未保存 Gemini API 密钥。',
      keyHint: '已保存密钥',
      status: '状态',
      valid: '有效',
      invalid: '无效',
      unchecked: '未检查',
      lastChecked: '上次检查',
      lastError: '最近错误',
      guideTitle: '如何获取 Gemini 密钥',
      guideSteps: ['打开 Google AI Studio。', '创建或选择一个 API 密钥。', '如果 Google 要求，请启用结算。', '将密钥粘贴到这里并测试连接。'],
      securityTitle: '安全说明',
      securityItems: ['完整密钥会在数据库中加密保存。', '页面只显示掩码提示。', '你可以随时停用或删除密钥。', '不要在聊天或截图中分享密钥。'],
      scopeTitle: '当前范围',
      scopeBody: '第一版聚焦于带登录用户上下文运行的 Gemini/Google AI 调用。没有用户上下文的后台任务继续使用服务器密钥。',
      pricingTitle: 'BYOK 月度套餐',
      pricingSubtitle: '首月优惠 30%。API 使用费用由你的 AI 服务商账户直接收取。',
      firstMonthSaleBadge: '首月减 30%',
      originalPriceLabel: '原价',
      firstMonthPriceLabel: '首月优惠价',
      perMonthLabel: '/ 月',
      choosePlan: '选择套餐',
      pricingNote: '这里只是平台服务费。Gemini/OpenAI API 用量由你的服务商账户计费。',
      currentPlanTitle: '当前 BYOK 订阅',
      noActivePlan: '尚无有效 BYOK 套餐。请选择一个套餐以启用自带 API 密钥。',
      activeUntil: '有效期至',
      pendingPaymentTitle: '待支付',
      transferContent: '转账备注',
      paymentAmount: '金额',
      scanQr: '扫码支付',
      paymentCompleted: '支付已完成，BYOK 套餐已启用。',
      plans: [
        { id: 'basic', name: 'BYOK Basic', audience: '个人和轻度使用', monthlyPriceVnd: 199000, features: ['使用自己的 Gemini 密钥', '核心 AI 工具', '密钥加密保存', '基础支持'] },
        { id: 'pro', name: 'BYOK Pro', audience: '高频用户、教师、店铺', monthlyPriceVnd: 299000, recommended: true, features: ['包含 Basic 全部内容', '更高工作流优先级', '覆盖更多 AI 工具', '优先支持'] },
        { id: 'business', name: 'BYOK Business', audience: '团队、代理、小企业', monthlyPriceVnd: 699000, features: ['包含 Pro 全部内容', '团队/工作区使用指导', '上线协助', '业务流程咨询'] },
      ],
      successSaved: 'API 密钥已保存。',
      successChecked: '连接正常。',
      successDeleted: 'API 密钥已删除。',
      successUpdated: '设置已更新。',
    }
  }
  if (locale === 'ja') {
    return {
      title: '自分の API キー',
      subtitle: '自分の Gemini キーで AI ツールを使い、NanoAI は画面とワークフローを提供します。',
      overviewTitle: '仕組み',
      overviewBody: '有効にすると、対応する AI リクエストはまずあなたの Gemini API キーを使います。有効なユーザーキーがない場合、許可された機能ではサーバーキーに戻ります。',
      geminiTitle: 'Gemini API キー',
      geminiDescription: 'キーは保存前に暗号化され、保存後に全文が表示されることはありません。',
      apiKeyLabel: 'Google AI Studio API キー',
      apiKeyPlaceholder: 'Gemini API キーを貼り付け',
      saveAndCheck: '保存してテスト',
      checkConnection: '接続テスト',
      deleteKey: 'キーを削除',
      enabled: '有効',
      noKey: 'Gemini API キーはまだ保存されていません。',
      keyHint: '保存済みキー',
      status: '状態',
      valid: '有効',
      invalid: '無効',
      unchecked: '未確認',
      lastChecked: '最終確認',
      lastError: '直近のエラー',
      guideTitle: 'Gemini キーの取得方法',
      guideSteps: ['Google AI Studio を開きます。', 'API キーを作成または選択します。', 'Google が求める場合は請求を有効にします。', 'ここにキーを貼り付けて接続をテストします。'],
      securityTitle: 'セキュリティ',
      securityItems: ['完全なキーはデータベースで暗号化されます。', '画面にはマスクされたヒントだけ表示されます。', 'いつでも無効化または削除できます。', 'チャットやスクリーンショットでキーを共有しないでください。'],
      scopeTitle: '現在の適用範囲',
      scopeBody: '初版ではログインユーザーの文脈で動く Gemini/Google AI 呼び出しを対象にします。ユーザー文脈のないバックグラウンド処理はサーバーキーを使い続けます。',
      pricingTitle: 'BYOK 月額プラン',
      pricingSubtitle: '初月 30% オフ。API 利用料は AI プロバイダー側で直接請求されます。',
      firstMonthSaleBadge: '初月 30% オフ',
      originalPriceLabel: '通常',
      firstMonthPriceLabel: '初月プロモ価格',
      perMonthLabel: '/ 月',
      choosePlan: 'プランを選択',
      pricingNote: 'これはプラットフォーム利用料のみです。Gemini/OpenAI の利用料はプロバイダーアカウントに請求されます。',
      currentPlanTitle: '現在の BYOK サブスクリプション',
      noActivePlan: '有効な BYOK プランはまだありません。プランを選ぶと自分の API キーを AI 呼び出しに使えます。',
      activeUntil: '有効期限',
      pendingPaymentTitle: '支払い待ち',
      transferContent: '振込内容',
      paymentAmount: '金額',
      scanQr: 'QR をスキャンして支払い',
      paymentCompleted: '支払いが完了しました。BYOK プランが有効です。',
      plans: [
        { id: 'basic', name: 'BYOK Basic', audience: '個人・ライト利用', monthlyPriceVnd: 199000, features: ['自分の Gemini キーを利用', '主要 AI ツール', 'キーの暗号化保存', '基本サポート'] },
        { id: 'pro', name: 'BYOK Pro', audience: '高頻度ユーザー、教師、ショップ', monthlyPriceVnd: 299000, recommended: true, features: ['Basic のすべて', 'ワークフロー優先度アップ', 'より多くの AI ツール対応', '優先サポート'] },
        { id: 'business', name: 'BYOK Business', audience: 'チーム、代理店、小規模事業者', monthlyPriceVnd: 699000, features: ['Pro のすべて', 'チーム/ワークスペース利用ガイド', 'オンボーディング支援', '業務フロー相談'] },
      ],
      successSaved: 'API キーを保存しました。',
      successChecked: '接続できました。',
      successDeleted: 'API キーを削除しました。',
      successUpdated: '設定を更新しました。',
    }
  }
  if (locale === 'ko') {
    return {
      title: '내 API 키',
      subtitle: '내 Gemini 키로 AI 도구를 사용하고 NanoAI는 화면과 워크플로를 제공합니다.',
      overviewTitle: '작동 방식',
      overviewBody: '활성화하면 지원되는 AI 요청은 먼저 사용자의 Gemini API 키를 사용합니다. 유효한 사용자 키가 없으면 허용된 기능에서 서버 키로 돌아갈 수 있습니다.',
      geminiTitle: 'Gemini API 키',
      geminiDescription: '키는 저장 전에 암호화되며 저장 후 전체 키는 다시 표시되지 않습니다.',
      apiKeyLabel: 'Google AI Studio API 키',
      apiKeyPlaceholder: 'Gemini API 키 붙여넣기',
      saveAndCheck: '저장 및 테스트',
      checkConnection: '연결 테스트',
      deleteKey: '키 삭제',
      enabled: '사용',
      noKey: '아직 저장된 Gemini API 키가 없습니다.',
      keyHint: '저장된 키',
      status: '상태',
      valid: '유효',
      invalid: '무효',
      unchecked: '미확인',
      lastChecked: '마지막 확인',
      lastError: '최근 오류',
      guideTitle: 'Gemini 키 받는 방법',
      guideSteps: ['Google AI Studio를 엽니다.', 'API 키를 만들거나 선택합니다.', 'Google에서 요구하면 결제를 활성화합니다.', '여기에 키를 붙여넣고 연결을 테스트합니다.'],
      securityTitle: '보안 안내',
      securityItems: ['전체 키는 데이터베이스에 암호화되어 저장됩니다.', '페이지에는 마스킹된 힌트만 표시됩니다.', '언제든지 비활성화하거나 삭제할 수 있습니다.', '채팅이나 스크린샷으로 키를 공유하지 마세요.'],
      scopeTitle: '현재 범위',
      scopeBody: '첫 버전은 로그인 사용자 컨텍스트가 있는 Gemini/Google AI 호출에 집중합니다. 사용자 컨텍스트가 없는 백그라운드 작업은 서버 키를 계속 사용합니다.',
      pricingTitle: 'BYOK 월간 요금제',
      pricingSubtitle: '첫 달 30% 할인. API 사용료는 AI 제공업체 계정에서 직접 청구됩니다.',
      firstMonthSaleBadge: '첫 달 30% 할인',
      originalPriceLabel: '정가',
      firstMonthPriceLabel: '첫 달 할인가',
      perMonthLabel: '/ 월',
      choosePlan: '요금제 선택',
      pricingNote: '플랫폼 이용료만 포함됩니다. Gemini/OpenAI 사용량은 제공업체 계정에서 과금됩니다.',
      currentPlanTitle: '현재 BYOK 구독',
      noActivePlan: '아직 활성 BYOK 요금제가 없습니다. 요금제를 선택하면 내 API 키를 AI 호출에 사용할 수 있습니다.',
      activeUntil: '활성 기한',
      pendingPaymentTitle: '결제 대기',
      transferContent: '입금 내용',
      paymentAmount: '금액',
      scanQr: 'QR 스캔 결제',
      paymentCompleted: '결제가 완료되었습니다. BYOK 요금제가 활성화되었습니다.',
      plans: [
        { id: 'basic', name: 'BYOK Basic', audience: '개인 및 가벼운 사용', monthlyPriceVnd: 199000, features: ['내 Gemini 키 사용', '핵심 AI 도구', '키 암호화 저장', '기본 지원'] },
        { id: 'pro', name: 'BYOK Pro', audience: '고사용자, 교사, 쇼핑몰', monthlyPriceVnd: 299000, recommended: true, features: ['Basic 전체 포함', '워크플로 우선순위 향상', '더 많은 AI 도구 적용', '우선 지원'] },
        { id: 'business', name: 'BYOK Business', audience: '팀, 에이전시, 소규모 비즈니스', monthlyPriceVnd: 699000, features: ['Pro 전체 포함', '팀/워크스페이스 사용 가이드', '온보딩 지원', '비즈니스 워크플로 상담'] },
      ],
      successSaved: 'API 키를 저장했습니다.',
      successChecked: '연결이 정상입니다.',
      successDeleted: 'API 키를 삭제했습니다.',
      successUpdated: '설정을 업데이트했습니다.',
    }
  }
  return {
    title: 'API key riêng',
    subtitle: 'Dùng Gemini API key của khách, còn NanoAI cung cấp giao diện, workflow và công cụ.',
    overviewTitle: 'Cách hoạt động',
    overviewBody: 'Khi bật, các yêu cầu AI được hỗ trợ sẽ ưu tiên dùng Gemini API key của bạn. Nếu chưa có key hợp lệ, hệ thống vẫn có thể dùng key server ở những tính năng cho phép fallback.',
    geminiTitle: 'Gemini API key',
    geminiDescription: 'Key được mã hóa trước khi lưu và không bao giờ hiển thị lại đầy đủ sau khi lưu.',
    apiKeyLabel: 'Google AI Studio API key',
    apiKeyPlaceholder: 'Dán Gemini API key của bạn',
    saveAndCheck: 'Lưu và kiểm tra',
    checkConnection: 'Kiểm tra kết nối',
    deleteKey: 'Xóa key',
    enabled: 'Đang bật',
    noKey: 'Chưa lưu Gemini API key.',
    keyHint: 'Key đã lưu',
    status: 'Trạng thái',
    valid: 'Hợp lệ',
    invalid: 'Không hợp lệ',
    unchecked: 'Chưa kiểm tra',
    lastChecked: 'Kiểm tra lần cuối',
    lastError: 'Lỗi gần nhất',
    guideTitle: 'Cách lấy Gemini key',
    guideSteps: ['Mở Google AI Studio.', 'Tạo hoặc chọn một API key.', 'Bật billing nếu Google yêu cầu.', 'Dán key vào đây và kiểm tra kết nối.'],
    securityTitle: 'Lưu ý bảo mật',
    securityItems: ['Key đầy đủ được mã hóa trong database.', 'Trang chỉ hiển thị dạng che.', 'Bạn có thể tắt hoặc xóa key bất cứ lúc nào.', 'Không chia sẻ key trong chat hoặc ảnh chụp màn hình.'],
    scopeTitle: 'Phạm vi hiện tại',
    scopeBody: 'Bản đầu tập trung vào các lệnh gọi Gemini/Google AI có ngữ cảnh người dùng đăng nhập. Worker nền không có user vẫn dùng key server.',
    pricingTitle: 'Gói BYOK theo tháng',
    pricingSubtitle: 'Sale tháng đầu giảm 30%. Khách tự thanh toán phí API trực tiếp cho nhà cung cấp AI.',
    firstMonthSaleBadge: 'Giảm 30% tháng đầu',
    originalPriceLabel: 'Giá gốc',
    firstMonthPriceLabel: 'Giá ưu đãi tháng đầu',
    perMonthLabel: '/ tháng',
    choosePlan: 'Chọn gói',
    pricingNote: 'Đây là phí nền tảng dùng công cụ. Chi phí API Gemini/OpenAI do tài khoản nhà cung cấp của khách thanh toán riêng.',
    currentPlanTitle: 'Gói BYOK hiện tại',
    noActivePlan: 'Chưa có gói BYOK đang hoạt động. Chọn một gói bên dưới để bật API key riêng cho các lệnh gọi AI.',
    activeUntil: 'Hiệu lực đến',
    pendingPaymentTitle: 'Thanh toán đang chờ',
    transferContent: 'Nội dung chuyển khoản',
    paymentAmount: 'Số tiền',
    scanQr: 'Quét QR để thanh toán',
    paymentCompleted: 'Thanh toán đã hoàn tất. Gói BYOK đã được kích hoạt.',
    plans: [
      { id: 'basic', name: 'BYOK Basic', audience: 'Cá nhân, dùng nhẹ', monthlyPriceVnd: 199000, features: ['Dùng Gemini API key riêng', 'Các công cụ AI cốt lõi', 'Key được mã hóa khi lưu', 'Hỗ trợ cơ bản'] },
      { id: 'pro', name: 'BYOK Pro', audience: 'Dùng nhiều, giáo viên, shop', monthlyPriceVnd: 299000, recommended: true, features: ['Bao gồm toàn bộ Basic', 'Ưu tiên workflow cao hơn', 'Phủ nhiều công cụ AI hơn', 'Hỗ trợ ưu tiên'] },
      { id: 'business', name: 'BYOK Business', audience: 'Team, agency, doanh nghiệp nhỏ', monthlyPriceVnd: 699000, features: ['Bao gồm toàn bộ Pro', 'Hướng dẫn dùng theo team/workspace', 'Hỗ trợ onboarding', 'Tư vấn workflow kinh doanh'] },
    ],
    successSaved: 'Đã lưu API key.',
    successChecked: 'Kết nối hoạt động.',
    successDeleted: 'Đã xóa API key.',
    successUpdated: 'Đã cập nhật cài đặt.',
  }
}

export default async function CustomerApiKeysPage() {
  const user = await getUserOrBypass()
  if (!user) redirectToLogin()
  const row = await getUserAiApiKeyPublicRow(user.id, 'google_gemini')
  const subscription = await getByokSubscriptionForUser(user.id)
  const payments = await listByokPlanPaymentsForUser(user.id, 5)
  return (
    <CustomerApiKeysClient
      initialRow={row}
      initialSubscription={subscription}
      initialPayments={payments}
      copy={copyForLocale(getCurrentWebLocale())}
    />
  )
}
