import { describe, expect, it } from 'vitest'
import {
  clampOverlayPct,
  clampPaddingPx,
  extractFirstCssUrl,
  inferVisualEditImageKind,
  replaceCssBackgroundUrl,
  shouldUseCurrentImageAsRef,
} from './visual-editor-css-url'
import { buildVisualEditorScript } from './build-visual-editor-script'

describe('visual-editor css url', () => {
  it('extracts url from hero gradient + image', () => {
    const css =
      "linear-gradient(90deg,rgba(249,115,22,.55),rgba(0,0,0,.25)),url('https://cdn.example/hero.jpg')"
    expect(extractFirstCssUrl(css)).toBe('https://cdn.example/hero.jpg')
  })

  it('replaces only the url() and keeps the gradient', () => {
    const css = "linear-gradient(#0000,#000),url(\"old.png\")"
    expect(replaceCssBackgroundUrl(css, 'https://cdn.example/new.jpg')).toBe(
      "linear-gradient(#0000,#000),url('https://cdn.example/new.jpg')"
    )
  })

  it('sets url when there is no existing background image', () => {
    expect(replaceCssBackgroundUrl('', 'https://cdn.example/a.png')).toBe(
      "url('https://cdn.example/a.png')"
    )
  })

  it('infers logo / banner / product kinds', () => {
    expect(inferVisualEditImageKind({ isLogo: true })).toEqual({ kind: 'logo', aspectRatio: '1:1' })
    expect(inferVisualEditImageKind({ isLogo: true, width: 160, height: 36 })).toEqual({
      kind: 'logo',
      aspectRatio: '4:1',
    })
    expect(inferVisualEditImageKind({ isBgImage: true, width: 1200, height: 400 })).toEqual({
      kind: 'banner',
      aspectRatio: '21:9',
    })
    expect(inferVisualEditImageKind({ width: 800, height: 400 })).toEqual({
      kind: 'banner',
      aspectRatio: '16:9',
    })
    expect(inferVisualEditImageKind({ width: 300, height: 480 })).toEqual({
      kind: 'product_photo',
      aspectRatio: '2:3',
    })
  })

  it('enables current-image reference for banner photos, not empty logos', () => {
    expect(shouldUseCurrentImageAsRef({ src: 'https://cdn.example/hero.jpg', isBgImage: true })).toBe(true)
    expect(shouldUseCurrentImageAsRef({ src: 'https://cdn.example/p.jpg', isImage: true })).toBe(true)
    expect(shouldUseCurrentImageAsRef({ src: '', isBgImage: true })).toBe(false)
    expect(
      shouldUseCurrentImageAsRef({ src: 'https://cdn.example/logo.png', isLogo: true, logoFace: 'image' })
    ).toBe(true)
    expect(
      shouldUseCurrentImageAsRef({ src: 'https://cdn.example/logo.png', isLogo: true, logoFace: 'empty' })
    ).toBe(false)
  })
})

describe('visual-editor runtime script', () => {
  it('includes click-to-edit hooks for images, buttons, and AI replace', () => {
    const s = buildVisualEditorScript('vi')
    expect(s).toContain('setHref')
    expect(s).toContain('isBtnEl')
    expect(s).toContain('isChromeBtn')
    expect(s).toContain('insertChromeBtn')
    expect(s).toContain("k === 'categories'")
    expect(s).toContain("k === 'search'")
    expect(s).toContain("k === 'search-image'")
    expect(s).toContain('data-pw-device')
    expect(s).toContain("editDevice === 'mobile'")
    expect(s).toContain('insertText')
    expect(s).toContain('insertButton')
    expect(s).toContain('insertBg')
    expect(s).toContain('lastInsertBgAt')
    expect(s).toContain('__nanoaiVeInsertBgAt')
    expect(s).toContain('__nanoaiVeOnMessage')
    expect(s).toContain('data-pw-added-bg')
    expect(s).toContain('bringAddedBgFront')
    expect(s).toContain('sendAddedBgBack')
    expect(s).toContain('ensureBgStack')
    expect(s).toContain('stepBgStack')
    expect(s).toContain('detachAddedBgFromChrome')
    expect(s).toContain('.pw-topbar,.nanoai-ve-active .pw-shop-topbar')
    expect(s).toContain('bgLayer:')
    expect(s).toContain('layerAddedBg')
    expect(s).toContain("d.type === 'setTheme'")
    expect(s).toContain('applyThemeVars')
    expect(s).toContain('pw-theme-root')
    expect(s).toContain("d.type === 'sendBgBack'")
    expect(s).toContain("d.type === 'layerBgUp'")
    expect(s).toContain("d.type === 'layerBgDown'")
    expect(s).toContain('stepElementLayer')
    expect(s).toContain('bringElementFront')
    expect(s).toContain('sendElementBack')
    expect(s).toContain('layerPromoteHost')
    expect(s).toContain("walkCls.indexOf('pw-shop-brand-cluster')")
    expect(s).toContain('isFullBleedChrome')
    expect(s).toContain('revealLayeredLogo')
    expect(s).toContain('listLayerPack')
    expect(s).toContain('layerIndex:')
    expect(s).toContain('data-pw-z')
    expect(s).toContain(':not([data-pw-z])')
    expect(s).toContain('editKindOf')
    expect(s).toContain('editKind:')
    expect(s).toContain('chromeKind:')
    expect(s).toContain('canDelete:')
    expect(s).toContain('isCatToggleEl')
    expect(s).toContain('catToggleElOf')
    expect(s).toContain('chromeBtnElOf')
    expect(s).toContain('canSetHrefEl')
    expect(s).toContain('isCatToggle:')
    expect(s).toContain('isAddedBtn:')
    expect(s).toContain("'nav-link'")
    expect(s).toContain('data-pw-cat-toggle')
    expect(s).toContain('canStickHeader')
    expect(s).toContain('detachForStickHeader')
    expect(s).toContain('data-pw-stick-header')
    expect(s).toContain('stickHeaderRelease')
    expect(s).toContain("d.type === 'serialize'")
    expect(s).toContain("post('html', { html: document.documentElement.outerHTML })")
    expect(s).toContain('__pwStickHeaderApply')
    expect(s).toContain("d.type === 'layerElUp'")
    expect(s).toContain("d.type === 'layerElDown'")
    expect(s).toContain("d.type === 'layerElFront'")
    expect(s).toContain("d.type === 'layerElBack'")
    expect(s).toContain('not([data-pw-added-bg])')
    expect(s).toContain('not([data-pw-added-text])')
    expect(s).toContain('not([data-pw-added-btn])')
    expect(s).toContain('isAddedOverlay')
    expect(s).toContain('sawContent')
    expect(s).not.toContain("node.setAttribute('data-pw-bg-layer'")
    expect(s).toContain('setChromeStyle')
    expect(s).toContain('setButtonStyle')
    expect(s).toContain('applyBtnStyle')
    expect(s).toContain('placeOverlayButton')
    expect(s).toContain('placeOverlayText')
    expect(s).toContain('placeOverlayNode')
    expect(s).toContain('freeAddedTextOverlays')
    expect(s).toContain('overlayRoot')
    expect(s).toContain('nextAddedOverlayZ')
    expect(s).toContain('applyAddedTextHref')
    expect(s).toContain("return 'added-text'")
    expect(s).toContain('isChromeTextTrap')
    expect(s).toContain('isEditableTextTarget')
    expect(s).toContain("d.type === 'setTextContent'")
    expect(s).toContain('findBannerHost')
    expect(s).toContain('r.height / 2')
    expect(s).toContain('__nanoaiVeBound')
    expect(s).toContain('__nanoaiVeActivate')
    expect(s).toContain('__nanoaiVeDeactivate')
    expect(s).toContain('unbindVeListeners')
    expect(s).toContain('bindVeListeners')
    expect(s).toContain('veListening')
    expect(s).toContain('activateFromHost')
    expect(s).toContain('lastInsertButtonAt')
    expect(s).toContain('placeCaretAtPoint')
    expect(s).toContain('caretRangeFromPoint')
    expect(s).toContain('setButtonLabel')
    expect(s).toContain('setButtonColor')
    expect(s).toContain('setButtonBorder')
    expect(s).toContain('setIconColor')
    expect(s).toContain('setDotColor')
    expect(s).toContain('setPlaceholderColor')
    expect(s).toContain('bottomNavItemOf')
    expect(s).toContain('searchSubmitElOf')
    expect(s).toContain('isWordmarkTextEl')
    expect(s).toContain('dotsElOf')
    expect(s).toContain('fieldElOf')
    expect(s).toContain("d.type === 'setDotActiveColor'")
    expect(s).toContain('applyWidgetIconColor')
    expect(s).toContain('applyWidgetBg')
    expect(s).toContain('isWidgetSurfaceEl')
    expect(s).toContain('data-pw-icon-color')
    expect(s).toContain('restoreWidgetColors')
    expect(s).toContain('applyWidgetTextColor')
    expect(s).toContain('applyWidgetBorder')
    expect(s).toContain('data-pw-btn-text')
    expect(s).toContain('data-pw-btn-border')
    expect(s).toContain('.pw-header-actions [data-pw-chrome-added]')
    expect(s).toContain('.pw-header-search,.pw-shop-search-wrap')
    expect(s).toContain('flex:1 1 auto!important')
    expect(s).toContain('data-pw-search-width')
    expect(s).toContain('lockSearchBox')
    expect(s).toContain('is-search-width')
    expect(s).toContain('search-width')
    expect(s).toContain('z-index:200')
    expect(s).toContain('z-index:90')
    expect(s).toContain('z-index:180!important')
    expect(s).toContain('z-index:160')
    expect(s).toContain('applyDefaultZ')
    expect(s).toContain('z-index:15!important')
    expect(s).toContain('[data-pw-edit-device="mobile"] .pw-bottom-nav')
    expect(s).not.toContain('.nanoai-ve-active .pw-bottom-nav,.nanoai-ve-active .pw-shop-bottom-nav{z-index:1!important')
    expect(s).toContain('ensureLogoFrame')
    expect(s).toContain('setLogoZoom')
    expect(s).toContain("d.type === 'setBannerZoom'")
    expect(s).toContain('data-pw-logo-frame')
    expect(s).toContain('logoMoveEl')
    expect(s).toContain("'logo-box'")
    expect(s).toContain("'logo-pan'")
    expect(s).toContain('unlockLogoImage')
    expect(s).toContain('logoZoomed')
    expect(s).toContain('applyLogoPan')
    expect(s).toContain('applyLogoCrop')
    expect(s).toContain('function onWheel(')
    expect(s).toContain("d.type === 'setLogoReset'")
    expect(s).toContain("d.type === 'openLogoCrop'")
    expect(s).toContain('function openLogoCropOverlay(')
    expect(s).toContain('nanoai-ve-logo-live-crop')
    expect(s).toContain('liveCropEdgeDir')
    expect(s).toContain('logoCrop.live')
    expect(s).toContain('beginLiveCropPointer')
    expect(s).toContain('bindLiveCropPointers')
    expect(s).toContain("drag.mode = 'logo-box'")
    expect(s).toContain('transform-origin:center center')
    expect(s).toContain('cropLogo')
    expect(s).toContain('if (logoCrop.live && !forceMove && zImg)')
    expect(s).toContain('logoPanLimit')
    expect(s).toContain('cursor:grab!important')
    expect(s).toContain('data-pw-logo-pan-x')
    expect(s).toContain('data-pw-logo-crop-x')
    expect(s).toContain('data-pw-logo-crop-y')
    expect(s).toContain("clipPath = 'inset(")
    expect(s).toContain('syncLogoLayerVisual')
    expect(s).toContain('logoLayerNow')
    expect(s).toContain('img.pw-logo.nanoai-ve-highlight')
    expect(s).not.toContain('[data-pw-logo-added].nanoai-ve-highlight{outline:2px solid #2563eb!important;outline-offset:1px!important;background:transparent!important')
    expect(s).not.toContain('.pw-logo-frame.nanoai-ve-highlight{outline:2px solid #fff!important;outline-offset:0!important;background:transparent!important')
    expect(s).not.toContain('if (logoLink) releaseFloatedBrandLink(logoLink)')
    expect(s).toContain(':not([data-pw-logo-added]):not(.pw-logo)')
    expect(s).toContain("if (selected && isLogoTarget(selected)) {\n      hideLayerSwitches()\n      return")
    expect(s).toContain('resize.startW + dx')
    expect(s).toContain('clampLogoBox')
    expect(() => {
      // eslint-disable-next-line @typescript-eslint/no-implied-eval
      new Function(s)
    }).not.toThrow()
    expect(s).toContain('flex-direction:row!important')
    expect(s).toContain('deleteChromeBtn')
    expect(s).toContain('ensureChromeHost')
    expect(s).toContain('nanoai-ve-move-handle')
    expect(s).toContain('beginHandleDrag')
    expect(s).toContain('beginHandleDrag(e, true)')
    expect(s).toContain('logoFaceOf(logoImgOf(el) || el)')
    expect(s).toContain('deleteSelectedUnit')
    expect(s).toContain('pruneEmptyLogoFrames')
    expect(s).toContain('isShopRegionHost')
    expect(s).toContain('isIgnored(e.target)')
    expect(s).toContain("key === 'Delete'")
    expect(s).toContain('Math.max(4, r.top - 9)')
    expect(s).toContain('nanoai-ve-guide-h')
    expect(s).toContain('nanoai-ve-guide-v')
    expect(s).toContain('positionAlignGuides')
    expect(s).toContain('nudgeSelected')
    expect(s).toContain('function isNudgeTypingTarget')
    expect(s).toContain('isNudgeTypingTarget(e.target)')
    expect(s).toContain('.nanoai-ve-active input[data-pw-search]{pointer-events:none!important')
    expect(s).toContain('target.style.transform = \'translate(\' + (p.x + dx) + \'px,\' + (p.y + dy) + \'px)\'')
    expect(s).toContain('function nudgeSelected(dx, dy) {\n    if (!selected || !canDragEl(selected)) return\n    if (isLogoTarget(selected)) {\n      var frameTarget = (isInHeader(selected) && headerLogoUnit(selected)) || logoMoveEl(selected) || selected')
    expect(s).toContain('stopImmediatePropagation')
    expect(s).toContain('isBgImageEl')
    expect(s).toContain('findBgImageEl')
    expect(s).toContain('div[data-pw-bg-layer]')
    expect(s).toContain('data-pw-move-block')
    expect(s).toContain('ensureImageLayer')
    expect(s).toContain('isLockedCatalogEl')
    expect(s).toContain('isProductCardEl')
    expect(s).toContain('[data-pw-el="card"]')
    expect(s).toContain('isHeroBannerContext')
    expect(s).toContain('isHeroBannerEl')
    expect(s).toContain('data-pw-add-cart')
    expect(s).toContain('pw-shop-grid')
    expect(s).toContain('stampCatalogLocks')
    expect(s).toContain('looksLikeProductCardShape')
    expect(s).toContain('data-pw-catalog-lock')
    expect(s).toContain('siblingProductCardCount')
    expect(s).toContain('looksLikeBannerHost')
    expect(s).toContain('containsForeignShopRegion')
    expect(s).toContain('isNonBannerShopRegion')
    expect(s).toContain("region !== 'banner'")
    expect(s).not.toContain('thêm vào giỏ|add to cart|mua ngay')
    expect(s).toContain('repairMisidentifiedBannerHosts')
    expect(s).toContain('unwrapEditorWrap')
    expect(s).toContain('bannerHostOf')
    expect(s).toContain('bannerLayerTarget')
    expect(s).toContain('resolveBannerClickTarget')
    expect(s).toContain('clearEditorMarks')
    expect(s).toContain('clearForeignEditorMarks')
    expect(s).toContain('if (nextBanner && nextBanner !== selected) return')
    expect(s).toContain('selectedBanner && foundBanner && selectedBanner === foundBanner')
    expect(s).toContain('resolvePointerTarget')
    expect(s).toContain('findCategoriesSelectable')
    expect(s).toContain('pointInEl(selectedBanner')
    expect(s).toContain('[data-pw-region="categories"]')
    expect(s).toContain('pwRegionOf(el) === \'categories\'')
    expect(s).toContain('isBannerHostEl')
    expect(s).toContain('.nanoai-ve-highlight[data-pw-region="banner"]')
    expect(s).toContain('isBannerMediaChild')
    expect(s).toContain('data-pw-banner-copy')
    expect(s).toContain('panBannerPhoto')
    expect(s).toContain('applyBannerPhoto')
    expect(s).toContain('parseBannerPan')
    expect(s).toContain('is-banner-zoom')
    expect(s).toContain('photoSrcOf')
    expect(s).toContain('photoSrcOf(logoImgSrc)')
    expect(s).toContain('pointer-events:none!important')
    expect(s).toContain('pwApplyDemoChromeCountBadges')
    expect(s).toContain('pwSetChromeCountBadgeByKind')
    expect(s).toContain('.pw-shop-brand-cluster{pointer-events:none!important}')
    expect(s).toContain('.pw-shop-brand-cluster > *')
    expect(s).toContain('isPointerPassthrough')
    expect(s).toContain('clusterChildAtPoint')
    expect(s).toContain('isBrandClusterEl')
    expect(s).toContain("var layerMode = 'block'")
    expect(s).toContain('closestEditable')
    expect(s).toContain('.nanoai-ve-active .pw-shop-cat-panel:not(.is-open)')
    expect(s).toContain('.nanoai-ve-active [data-pw-el="nav-link"]')
    expect(s).toContain('.nanoai-ve-active [data-pw-el="link"]')
    expect(s).toContain('.nanoai-ve-active .pw-shop-header-inner{overflow:visible!important')
    expect(s).toContain('.pw-header-main,.pw-shop-header-inner{display:flex!important;flex-wrap:nowrap!important;align-items:center!important;min-width:0;position:relative!important;max-width:none!important;width:100%!important;margin-left:0!important;margin-right:0!important}')
    expect(s).not.toContain('overflow-x:clip!important')
    expect(s).toContain('.pw-hero-inner,.nanoai-ve-active .pw-banner-inner')
    expect(s).not.toContain('.nanoai-ve-active .pw-hero-inner,.nanoai-ve-active .pw-banner-inner{pointer-events:auto')
    expect(s).toContain('stampMoveBlock')
    expect(s).toContain(':scope > .pw-hero-inner')
    expect(s).toContain('overflow:visible!important')
    expect(s).toContain('movePick')
    expect(s).toContain('moveNow')
    expect(s).toContain("canImageLayer(el) && layerMode === 'block'")
    expect(s).toContain('prepareImageLayerBlocks')
    expect(s).toContain('ungroupMoveBlock')
    expect(s).toContain('groupIntoBlock')
    expect(s).toContain('isMoveBlockEl')
    expect(s).toContain("d.type === 'ungroupBlock'")
    expect(s).toContain("d.type === 'groupBlock'")
    expect(s).toContain("'bg-pan'")
    expect(s).toContain('if (layerBanner && layerMode === \'block\') return layerBanner')
    expect(s).toContain("layerMode === 'image' ? bannerLayerTarget(bannerHost, 'image') : bannerHost")
    expect(s).not.toContain('nanoai-ve-photo-edit [data-pw-el="title"]{pointer-events:auto')
    expect(s).toContain('nanoai-ve-layer-switch')
    expect(s).toContain('stickyChromeBottom')
    expect(s).toContain('data-ve-clipped')
    expect(s).toContain('layerSwitchInView')
    expect(s).toContain('visibleBottom - visibleTop >= 28')
    expect(s).toContain('.nanoai-ve-layer-switch[data-ve-clipped="1"]')
    expect(s).not.toContain("box.style.top = Math.max(8, r.top - 8) + 'px'")
    expect(s).toContain('applyLayerMode')
    expect(s).toContain('heroImgIn')
    expect(s).toContain('data-pw-edit="heroImage"')
    expect(s).toContain('setLayerMode')
    expect(s).toContain('layerBlock')
    expect(s).toContain('Khối')
    expect(s).toContain('HISTORY_MAX = 30')
    expect(s).toContain('undoHistory')
    expect(s).toContain('redoHistory')
    expect(s).toContain("d.type === 'undo'")
    expect(s).toContain('ownPwRegion')
    expect(s).toContain("region !== 'banner'")
    expect(s).not.toContain("new RegExp('pw-(hero|")
    expect(s).toContain('setImageSrc')
    expect(s).toContain('sampleSurroundingBg')
    expect(s).toContain('applyLogoToEl')
    expect(s).toContain('hideSiblingWordmarks')
    expect(s).toContain('hideBrandLinkText')
    expect(s).toContain('applyLeftoverTextLogos')
    expect(s).toContain('.pw-shop-footer-name')
    expect(s).toContain('listLogoSlots')
    expect(s).toContain('.pw-wordmark, a.pw-shop-brand, a.pw-brand')
    expect(s).toContain('hasClassToken')
    expect(s).toContain('nanoai-ve-logo-btn')
    expect(s).toContain('logoCreate')
    expect(s).toContain('allSlots')
    expect(s).toContain('Tạo logo')
    expect(s).toContain('Tạo lại logo')
    expect(s).toContain('logoFaceOf')
    expect(s).toContain('recreateLogo')
    expect(s).toContain('startAddLogo')
    expect(s).toContain('placeHeaderLogoFromToolbar')
    expect(s).toContain('placeHeaderLogo')
    expect(s).toContain('data-pw-logo-added')
    expect(s).toContain('nanoai-ve-logo-rect')
    expect(s).toContain('finishAddLogo')
    expect(s).toContain('logoInsertHost')
    expect(s).toContain('rescueHeaderLogos')
    expect(s).toContain('revealHeaderLogo')
    expect(s).toContain('placeLogoInCluster')
    expect(s).toContain('sealAppliedLogo')
    expect(s).toContain('clearLogoSlotPaint')
    expect(s).toContain('fitLogoFrameToImage')
    expect(s).toContain('afterLogoImageReady')
    expect(s).toContain('resetLogoImageLayout')
    expect(s).toContain('sanitizeHeaderLogoLayout')
    expect(s).toContain('[data-pw-hidden="1"]{display:none!important}')
    expect(s).toContain('dedupeHeaderLogos')
    expect(s).toContain('keepFrame')
    expect(s).toContain('restoreBrandWordmarks')
    expect(s).toContain('headerLogoFreeCap')
    expect(s).toContain('pinHeaderLogoFloat')
    expect(s).toContain('headerLogoHost')
    expect(s).toContain('ensureHeaderLogoHostPos')
    expect(s).toContain('already && sameHost')
    expect(s).toContain('Math.max(0, isFinite(left) ? left : 0)')
    expect(s).toContain('releaseFloatedBrandLink')
    expect(s).toContain('data-pw-logo-float')
    expect(s).toContain('headerLogoMaxBox')
    expect(s).toContain('reflowHeaderChrome')
    expect(s).toContain("d.type === 'resetHistory'")
    expect(s).toContain('resetHistoryBaseline')
    expect(s).not.toContain("if (reflowHeaderChrome()) post('dirty', {})")
    expect(s).toContain('data-pw-edit-device')
    expect(s).toContain('nanoai-ve-mobile')
    expect(s).toContain('max-width:200px')
    expect(s).toContain('max-width:none')
    expect(s).toContain('flex:1 1 0%')
    expect(s).toContain("hasClassToken(el, 'pw-brand')")
    expect(s).toContain("hasClassToken(el, 'pw-cat-btn')")
    expect(s).toContain("pwElOf(el) === 'cat-toggle'")
    expect(s).toContain('padding:8px 10px')
    expect(s).not.toContain('applyLeftoverTextLogos(d.logoUrl)')
    expect(s).toContain('shopHomeHref')
    expect(s).toContain('ensureLogoHomeLink')
    expect(s).toContain('data-pw-logo-home')
    expect(s).toContain('isTextEl(el)')
    expect(s).toContain('ensureDragDisplay')
    expect(s).toContain('hideBlock')
    expect(s).toContain('duplicateBlock')
    expect(s).toContain('setOverlay')
    expect(s).toContain('setPadding')
    expect(s).toContain('chromeSlotAtX')
    expect(s).toContain('chromeHostChildren')
    expect(s).toContain('pinChromeIconBadges')
    expect(s).toContain("if (isAddedChrome(el) || isChromeBtn(el) || isHeaderWidget(el))")
    expect(s).toContain("} else if (drag.mode === 'reorder') {")
    expect(s).not.toContain("drag.mode === 'reorder' || isAddedChrome(selected)")
  })
})

describe('visual-editor header logo geometry is settled while editing', () => {
  const s = buildVisualEditorScript('vi')

  it('caps the header logo by the authored device width, not the live viewport', () => {
    expect(s).toContain('headerLogoDeviceWidth')
    expect(s).toContain("if (editDevice === 'mobile') return 390")
    expect(s).toContain("if (editDevice === 'tablet') return 768")
    expect(s).toContain('return 1200')
    expect(s).toContain('Math.min(headerLogoDeviceWidth(), Math.round(viewW))')
  })

  it('snaps a dropped float logo back inside the header on mouse up', () => {
    expect(s).toContain("Math.max(0, Math.round(bakeR.left - bakeHr.left)) + 'px'")
    expect(s).toContain("Math.max(0, Math.round(bakeR.top - bakeHr.top)) + 'px'")
  })
})

describe('visual-editor block clamps', () => {
  it('clamps overlay and padding', () => {
    expect(clampOverlayPct(-4)).toBe(0)
    expect(clampOverlayPct(99)).toBe(80)
    expect(clampOverlayPct(32.4)).toBe(32)
    expect(clampPaddingPx(200)).toBe(160)
    expect(clampPaddingPx(12.6)).toBe(13)
  })
})
